import { Experience, Artisan, CulturalExperience } from '../types';
import { SupportedLanguage } from './translations';

export const LOCALIZED_EXPERIENCES: Record<SupportedLanguage, Experience[]> = {
  en: [
    {
      id: 'exp_kolhapur_01',
      artisan_id: 'art_kolhapur_01',
      artisan_name: 'Santosh Kamble',
      artisan_avatar: '/assets/images/Home%20page/Kolhapuri_Chappals_in_roadside_shop_in_Kolhapur3.jpeg',
      trust_score: 98,
      title: 'Heritage Kolhapuri Chappal Crafting Masterclass',
      description: 'Learn ancestral vegetable tanning using myrobalan and babool bark. Sit alongside 4th-generation master cobblers, shape traditional wooden lasts, hand-punch intricate motifs, and braid genuine leather straps.',
      category: 'Leathercraft',
      price_inr: 1850,
      duration_mins: 150,
      max_participants: 8,
      lat: 16.7050,
      lng: 74.2433,
      location_name: 'Shivaji Market, Kolhapur',
      district: 'Kolhapur',
      state: 'Maharashtra',
      cover_image: '/assets/images/Home%20page/Kolhapuri_Chappals_in_roadside_shop_in_Kolhapur3.jpeg',
      odop_tag: 'ODOP-MH-KOLHAPUR-LEATHER',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_chanderi_01',
      artisan_id: 'art_chanderi_01',
      artisan_name: 'Kamla Bai',
      artisan_avatar: '/assets/images/01-Hero/Chanderi_Craft_Village_–_Traditional_Weaving_and_Handicrafts_in_Madhya_Pradesh_01.jpg',
      trust_score: 97,
      title: 'Royal Chanderi Silk Pit-Loom Weaving & Zari Interlacing',
      description: 'Immerse yourself in 700-year-old Bundelkhand royalty. Sit in an earthen pit loom, handle pure mulberry silk and electroplated gold zari, and weave royal peacock motifs.',
      category: 'Handloom',
      price_inr: 2200,
      duration_mins: 180,
      max_participants: 6,
      lat: 24.7120,
      lng: 78.1380,
      location_name: 'Pranpur Craft Village, Chanderi',
      district: 'Ashoknagar',
      state: 'Madhya Pradesh',
      cover_image: '/assets/images/01-Hero/Chanderi_Craft_Village_–_Traditional_Weaving_and_Handicrafts_in_Madhya_Pradesh_01.jpg',
      odop_tag: 'ODOP-MP-CHANDERI-SILK',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_majuli_01',
      artisan_id: 'art_majuli_01',
      artisan_name: 'Hemanta Bora',
      artisan_avatar: '/assets/images/04-Bamboo-Cane/Innovative_Bamboo_Crafts_of_Assam.jpg',
      trust_score: 96,
      title: 'Neo-Vaishnavite Mukha Bamboo Mask Sculpting Masterclass',
      description: 'Learn the 500-year-old art of crafting mythical character masks (Mukha) using bamboo splits, organic Brahmaputra riverbed silt, and natural vegetable pigments.',
      category: 'Bamboo-Cane',
      price_inr: 1950,
      duration_mins: 180,
      max_participants: 8,
      lat: 26.9500,
      lng: 94.2167,
      location_name: 'Natun Samaguri Satra, Majuli Island',
      district: 'Majuli',
      state: 'Assam',
      cover_image: '/assets/images/04-Bamboo-Cane/Innovative_Bamboo_Crafts_of_Assam.jpg',
      odop_tag: 'ODOP-AS-MAJULI-MASKS',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_srinagar_01',
      artisan_id: 'art_srinagar_01',
      artisan_name: 'Ghulam Mohammad Zargar',
      artisan_avatar: '/assets/images/05-Wood-Pottery/Kashmiri_Woodcarving_And_Paper_maché.jpg',
      trust_score: 99,
      title: 'Master Walnut Wood Undercut Relief & Chinar Carving',
      description: 'Master delicate chisel channelling and deep 3D floral undercut carving on seasoned Kashmir walnut wood root blocks in the heart of Old Srinagar.',
      category: 'Woodwork',
      price_inr: 2500,
      duration_mins: 180,
      max_participants: 6,
      lat: 34.0837,
      lng: 74.7973,
      location_name: 'Zadibal Guild, Old Srinagar',
      district: 'Srinagar',
      state: 'Jammu and Kashmir',
      cover_image: '/assets/images/05-Wood-Pottery/Kashmiri_Woodcarving_And_Paper_maché.jpg',
      odop_tag: 'ODOP-JK-SRINAGAR-WALNUT',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_bishnupur_01',
      artisan_id: 'art_bishnupur_01',
      artisan_name: 'Subhas Kumbhakar',
      artisan_avatar: '/assets/images/05-Wood-Pottery/Artisan_decorating_ceramic_plate.jpg',
      trust_score: 96,
      title: 'Living Terracotta Temple Tile & Bankura Horse Modeling',
      description: 'Shape the iconic long-eared Bankura horse in five distinct hollow parts on a potter wheel, burnish with river stones, and fire in traditional wood kilns.',
      category: 'Pottery',
      price_inr: 1450,
      duration_mins: 150,
      max_participants: 8,
      lat: 23.0760,
      lng: 87.3190,
      location_name: 'Panchmura Village, Bankura',
      district: 'Bankura',
      state: 'West Bengal',
      cover_image: '/assets/images/05-Wood-Pottery/Artisan_decorating_ceramic_plate.jpg',
      odop_tag: 'ODOP-WB-BANKURA-HORSE',
      women_friendly: true,
      elderly_friendly: true
    }
  ],

  hi: [
    {
      id: 'exp_kolhapur_01',
      artisan_id: 'art_kolhapur_01',
      artisan_name: 'संतोष कांबले',
      artisan_avatar: '/assets/images/Home%20page/Kolhapuri_Chappals_in_roadside_shop_in_Kolhapur3.jpeg',
      trust_score: 98,
      title: 'पारंपरिक कोल्हापुरी चप्पल हस्तशिल्प मास्टरक्लास',
      description: 'बबूल की छाल और हरड़ से प्राकृतिक चमड़ा पकाना सीखें। चौथी पीढ़ी के मास्टर कारीगरों के साथ बैठकर पारंपरिक लकड़ी के सांचों पर अपने हाथों से असली कोल्हापुरी चप्पल बनाएं।',
      category: 'चमड़ा शिल्प',
      price_inr: 1850,
      duration_mins: 150,
      max_participants: 8,
      lat: 16.7050,
      lng: 74.2433,
      location_name: 'शिवाजी मार्केट, कोल्हापुर',
      district: 'कोल्हापुर',
      state: 'महाराष्ट्र',
      cover_image: '/assets/images/Home%20page/Kolhapuri_Chappals_in_roadside_shop_in_Kolhapur3.jpeg',
      odop_tag: 'ODOP-MH-कोल्हापुरी-चप्पल',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_chanderi_01',
      artisan_id: 'art_chanderi_01',
      artisan_name: 'कमला बाई',
      artisan_avatar: '/assets/images/01-Hero/Chanderi_Craft_Village_–_Traditional_Weaving_and_Handicrafts_in_Madhya_Pradesh_01.jpg',
      trust_score: 97,
      title: 'शाही चंदेरी रेशम गड्ढा-करघा बुनाई और जरी कार्यशाला',
      description: '700 साल पुरानी बुंदेलखंडी बुनाई परंपरा का अनुभव लें। पारंपरिक गड्ढा-करघे पर शुद्ध शहतूत रेशम और सोने की जरी से मोर एवं कमल की बूटी बुनना सीखें।',
      category: 'हथकरघा',
      price_inr: 2200,
      duration_mins: 180,
      max_participants: 6,
      lat: 24.7120,
      lng: 78.1380,
      location_name: 'प्राणपुर क्राफ्ट विलेज, चंदेरी',
      district: 'अशोकनगर',
      state: 'मध्य प्रदेश',
      cover_image: '/assets/images/01-Hero/Chanderi_Craft_Village_–_Traditional_Weaving_and_Handicrafts_in_Madhya_Pradesh_01.jpg',
      odop_tag: 'ODOP-MP-चंदेरी-सिल्क',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_majuli_01',
      artisan_id: 'art_majuli_01',
      artisan_name: 'हेमंत बोरा',
      artisan_avatar: '/assets/images/04-Bamboo-Cane/Innovative_Bamboo_Crafts_of_Assam.jpg',
      trust_score: 96,
      title: 'माजुली नव-वैष्णव मुखौटा और बांस शिल्प मास्टरक्लास',
      description: 'ब्रह्मपुत्र नदी की गाद मिट्टी, गाय के गोबर और बांस की खपच्चियों से 500 साल पुरानी मुखौटा निर्माण कला सीखें।',
      category: 'बांस एवं बेंत शिल्प',
      price_inr: 1950,
      duration_mins: 180,
      max_participants: 8,
      lat: 26.9500,
      lng: 94.2167,
      location_name: 'सामगुरी सत्र, माजुली द्वीप',
      district: 'माजुली',
      state: 'असम',
      cover_image: '/assets/images/04-Bamboo-Cane/Innovative_Bamboo_Crafts_of_Assam.jpg',
      odop_tag: 'ODOP-AS-माजुली-मुखौटा',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_srinagar_01',
      artisan_id: 'art_srinagar_01',
      artisan_name: 'गुलाम मोहम्मद जरगर',
      artisan_avatar: '/assets/images/05-Wood-Pottery/Kashmiri_Woodcarving_And_Paper_maché.jpg',
      trust_score: 99,
      title: 'कश्मीरी अखरोट लकड़ी 3D नक्काशी और चिनार डिज़ाइन मास्टरक्लास',
      description: 'पुराने श्रीनगर के ऐतिहासिक जादीबल में 4 साल पकी अखरोट की लकड़ी पर बारीक छेनी से चिनार के पत्तों की नक्काशी सीखें।',
      category: 'काष्ठ शिल्प',
      price_inr: 2500,
      duration_mins: 180,
      max_participants: 6,
      lat: 34.0837,
      lng: 74.7973,
      location_name: 'जादीबल, पुराना श्रीनगर',
      district: 'श्रीनगर',
      state: 'जम्मू और कश्मीर',
      cover_image: '/assets/images/05-Wood-Pottery/Kashmiri_Woodcarving_And_Paper_maché.jpg',
      odop_tag: 'ODOP-JK-अखरोट-लकड़ी',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_bishnupur_01',
      artisan_id: 'art_bishnupur_01',
      artisan_name: 'सुभाष कुंभकार',
      artisan_avatar: '/assets/images/05-Wood-Pottery/Artisan_decorating_ceramic_plate.jpg',
      trust_score: 96,
      title: 'बांकुड़ा टेराकोटा घोड़ा और मंदिर टाइल मूर्तिकला कार्यशाला',
      description: 'कुम्हार के चाक पर प्रसिद्ध बांकुड़ा घोड़े को पांच खोखले हिस्सों में ढालना और पारंपरिक लकड़ी की भट्टी में पकाना सीखें।',
      category: 'टेराकोटा मिट्टी शिल्प',
      price_inr: 1450,
      duration_mins: 150,
      max_participants: 8,
      lat: 23.0760,
      lng: 87.3190,
      location_name: 'पंचमुरा गांव, बांकुड़ा',
      district: 'बांकुड़ा',
      state: 'पश्चिम बंगाल',
      cover_image: '/assets/images/05-Wood-Pottery/Artisan_decorating_ceramic_plate.jpg',
      odop_tag: 'ODOP-WB-बांकुड़ा-घोड़ा',
      women_friendly: true,
      elderly_friendly: true
    }
  ],

  mr: [
    {
      id: 'exp_kolhapur_01',
      artisan_id: 'art_kolhapur_01',
      artisan_name: 'संतोष कांबळे',
      artisan_avatar: '/assets/images/Home%20page/Kolhapuri_Chappals_in_roadside_shop_in_Kolhapur3.jpeg',
      trust_score: 98,
      title: 'अस्सल कोल्हापुरी चप्पल हस्तकला प्रत्यक्ष कार्यशाळा',
      description: 'बाभळीची साल आणि नैसर्गिक वनस्पती पद्धतीने चामडे प्रक्रिया शिकून स्वतःच्या हाताने अस्सल कोल्हापुरी चप्पल तयार करा.',
      category: 'चामडे हस्तकला',
      price_inr: 1850,
      duration_mins: 150,
      max_participants: 8,
      lat: 16.7050,
      lng: 74.2433,
      location_name: 'शिवाजी मार्केट, कोल्हापूर',
      district: 'कोल्हापूर',
      state: 'महाराष्ट्र',
      cover_image: '/assets/images/Home%20page/Kolhapuri_Chappals_in_roadside_shop_in_Kolhapur3.jpeg',
      odop_tag: 'ODOP-MH-कोल्हापूर-चप्पल',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_chanderi_01',
      artisan_id: 'art_chanderi_01',
      artisan_name: 'कमला बाई',
      artisan_avatar: '/assets/images/01-Hero/Chanderi_Craft_Village_–_Traditional_Weaving_and_Handicrafts_in_Madhya_Pradesh_01.jpg',
      trust_score: 97,
      title: 'शाही चंदेरी रेशमी हातमाग विणकाम कार्यशाळा',
      description: 'पारंपरिक खड्डा हातमागावर बसून अस्सल चंदेरी रेशीम आणि जरी विणकामाचा थेट अनुभव घ्या.',
      category: 'हातमाग',
      price_inr: 2200,
      duration_mins: 180,
      max_participants: 6,
      lat: 24.7120,
      lng: 78.1380,
      location_name: 'प्राणपूर, चंदेरी',
      district: 'अशोकनगर',
      state: 'मध्य प्रदेश',
      cover_image: '/assets/images/01-Hero/Chanderi_Craft_Village_–_Traditional_Weaving_and_Handicrafts_in_Madhya_Pradesh_01.jpg',
      odop_tag: 'ODOP-MP-चंदेरी-रेशीम',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_majuli_01',
      artisan_id: 'art_majuli_01',
      artisan_name: 'हेमंत बोरा',
      artisan_avatar: '/assets/images/04-Bamboo-Cane/Innovative_Bamboo_Crafts_of_Assam.jpg',
      trust_score: 96,
      title: 'माजुली नव-वैष्णव बांबू मुखवटा कार्यशाळा',
      description: 'ब्रह्मपुत्रा नदीकाठच्या मातीतून आणि बांबूच्या कामट्यांमधून पारंपारिक मुखवटा बनवण्याची ५०० वर्षांची कला शिका.',
      category: 'बांबू हस्तकला',
      price_inr: 1950,
      duration_mins: 180,
      max_participants: 8,
      lat: 26.9500,
      lng: 94.2167,
      location_name: 'सामगुरी सत्र, माजुली बेट',
      district: 'माजुली',
      state: 'आसाम',
      cover_image: '/assets/images/04-Bamboo-Cane/Innovative_Bamboo_Crafts_of_Assam.jpg',
      odop_tag: 'ODOP-AS-माजुली-मुखवटे',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_srinagar_01',
      artisan_id: 'art_srinagar_01',
      artisan_name: 'गुलाम मोहम्मद झरगर',
      artisan_avatar: '/assets/images/05-Wood-Pottery/Kashmiri_Woodcarving_And_Paper_maché.jpg',
      trust_score: 99,
      title: 'काश्मिरी अक्रोड लाकूड कोरीव काम कार्यशाळा',
      description: 'श्रीनगरच्या जुन्या शहरात अक्रोडाच्या लाकडावर चिनार पानांचे त्रिमितीय कोरीव काम शिका.',
      category: 'लाकूड कोरीव काम',
      price_inr: 2500,
      duration_mins: 180,
      max_participants: 6,
      lat: 34.0837,
      lng: 74.7973,
      location_name: 'जादीबल, श्रीनगर',
      district: 'श्रीनगर',
      state: 'जम्मू आणि काश्मीर',
      cover_image: '/assets/images/05-Wood-Pottery/Kashmiri_Woodcarving_And_Paper_maché.jpg',
      odop_tag: 'ODOP-JK-अक्रोड-लाकूड',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_bishnupur_01',
      artisan_id: 'art_bishnupur_01',
      artisan_name: 'सुभाष कुंभार',
      artisan_avatar: '/assets/images/05-Wood-Pottery/Artisan_decorating_ceramic_plate.jpg',
      trust_score: 96,
      title: 'बांकुडा टेराकोटा मातीकाम आणि मंदिर शिल्प कार्यशाळा',
      description: 'चाकावर प्रसिद्ध बांकुडा घोडा घडवून लाकडाच्या भट्टीत भाजण्याचे पारंपरिक तंत्र शिका.',
      category: 'टेराकोटा मातीकाम',
      price_inr: 1450,
      duration_mins: 150,
      max_participants: 8,
      lat: 23.0760,
      lng: 87.3190,
      location_name: 'पंचमुरा, बांकुडा',
      district: 'बांकुडा',
      state: 'पश्चिम बंगाल',
      cover_image: '/assets/images/05-Wood-Pottery/Artisan_decorating_ceramic_plate.jpg',
      odop_tag: 'ODOP-WB-बांकुडा-घोडा',
      women_friendly: true,
      elderly_friendly: true
    }
  ],

  ta: [
    {
      id: 'exp_kolhapur_01',
      artisan_id: 'art_kolhapur_01',
      artisan_name: 'சந்தோஷ் காம்ப்ளே',
      artisan_avatar: '/assets/images/Home%20page/Kolhapuri_Chappals_in_roadside_shop_in_Kolhapur3.jpeg',
      trust_score: 98,
      title: 'பாரம்பரிய கோலாப்பூரி செருப்பு கைவினைப் பயிற்சி',
      description: 'பாரம்பரிய முறையில் தோல் பதனிடுதல் மற்றும் கைவினை செருப்பு தயாரிக்கும் பயிற்சி.',
      category: 'தோல் கைவினை',
      price_inr: 1850,
      duration_mins: 150,
      max_participants: 8,
      lat: 16.7050,
      lng: 74.2433,
      location_name: 'சிவாஜி மார்க்கெட், கோலாப்பூர்',
      district: 'கோலாப்பூர்',
      state: 'மகாராஷ்டிரா',
      cover_image: '/assets/images/Home%20page/Kolhapuri_Chappals_in_roadside_shop_in_Kolhapur3.jpeg',
      odop_tag: 'ODOP-MH-LEATHER',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_chanderi_01',
      artisan_id: 'art_chanderi_01',
      artisan_name: 'கமலா பாய்',
      artisan_avatar: '/assets/images/01-Hero/Chanderi_Craft_Village_–_Traditional_Weaving_and_Handicrafts_in_Madhya_Pradesh_01.jpg',
      trust_score: 97,
      title: 'ராஜகம்பீர சந்தேரி பட்டு நெசவுப் பயிற்சி',
      description: 'தூய மல்பெரி பட்டு மற்றும் தங்க ஜரிகை கொண்டு நெசவு செய்யும் நேரடி பயிற்சி.',
      category: 'கைத்தறி',
      price_inr: 2200,
      duration_mins: 180,
      max_participants: 6,
      lat: 24.7120,
      lng: 78.1380,
      location_name: 'பிரான்பூர், சந்தேரி',
      district: 'அசோக்நகர்',
      state: 'மத்தியப் பிரதேசம்',
      cover_image: '/assets/images/01-Hero/Chanderi_Craft_Village_–_Traditional_Weaving_and_Handicrafts_in_Madhya_Pradesh_01.jpg',
      odop_tag: 'ODOP-MP-SILK',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_majuli_01',
      artisan_id: 'art_majuli_01',
      artisan_name: 'ஹேமந்த போரா',
      artisan_avatar: '/assets/images/04-Bamboo-Cane/Innovative_Bamboo_Crafts_of_Assam.jpg',
      trust_score: 96,
      title: 'மஜூலி மூங்கில் முகமூடி கைவினைப் பயிற்சி',
      description: 'பிரம்மபுத்திரா களிமண் மற்றும் மூங்கில் கொண்டு பாரம்பரிய முகமூடி தயாரித்தல்.',
      category: 'மூங்கில் கைவினை',
      price_inr: 1950,
      duration_mins: 180,
      max_participants: 8,
      lat: 26.9500,
      lng: 94.2167,
      location_name: 'மஜூலி தீவு',
      district: 'மஜூலி',
      state: 'அசாம்',
      cover_image: '/assets/images/04-Bamboo-Cane/Innovative_Bamboo_Crafts_of_Assam.jpg',
      odop_tag: 'ODOP-AS-MASKS',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_srinagar_01',
      artisan_id: 'art_srinagar_01',
      artisan_name: 'குலாம் முகமது ஜர்கர்',
      artisan_avatar: '/assets/images/05-Wood-Pottery/Kashmiri_Woodcarving_And_Paper_maché.jpg',
      trust_score: 99,
      title: 'காஷ்மீர் வாதுமை மரச் செதுக்கல் பயிற்சி',
      description: 'பழைய ஸ்ரீநகரில் பாரம்பரிய வாதுமை மரத்தில் பூ வேலைப்பாடுகள் செதுக்கும் கலை.',
      category: 'மரச் செதுக்கல்',
      price_inr: 2500,
      duration_mins: 180,
      max_participants: 6,
      lat: 34.0837,
      lng: 74.7973,
      location_name: 'ஸ்ரீநகர்',
      district: 'ஸ்ரீநகர்',
      state: 'ஜம்மு & காஷ்மீர்',
      cover_image: '/assets/images/05-Wood-Pottery/Kashmiri_Woodcarving_And_Paper_maché.jpg',
      odop_tag: 'ODOP-JK-WALNUT',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_bishnupur_01',
      artisan_id: 'art_bishnupur_01',
      artisan_name: 'சுபாஷ் கும்பகார்',
      artisan_avatar: '/assets/images/05-Wood-Pottery/Artisan_decorating_ceramic_plate.jpg',
      trust_score: 96,
      title: 'பாங்குரா சுடுமண் குதிரை சிற்பக் கலைப் பயிற்சி',
      description: 'பாரம்பரிய சுடுமண் குதிரை மற்றும் கோவில் சிற்பங்கள் செய்யும் கலை.',
      category: 'சுடுமண் கைவினை',
      price_inr: 1450,
      duration_mins: 150,
      max_participants: 8,
      lat: 23.0760,
      lng: 87.3190,
      location_name: 'பாங்குரா',
      district: 'பாங்குரா',
      state: 'மேற்கு வங்கம்',
      cover_image: '/assets/images/05-Wood-Pottery/Artisan_decorating_ceramic_plate.jpg',
      odop_tag: 'ODOP-WB-HORSE',
      women_friendly: true,
      elderly_friendly: true
    }
  ],

  te: [
    {
      id: 'exp_kolhapur_01',
      artisan_id: 'art_kolhapur_01',
      artisan_name: 'సంతోష్ కాంబ్లే',
      artisan_avatar: '/assets/images/Home%20page/Kolhapuri_Chappals_in_roadside_shop_in_Kolhapur3.jpeg',
      trust_score: 98,
      title: 'కొల్హాపూర్ సాంప్రదాయ తోలు చెప్పుల వర్క్‌షాప్',
      description: 'సహజసిద్ధంగా తోలును సిద్ధం చేసి సంప్రదాయ చెప్పులు తయారు చేసే కళను నేర్చుకోండి.',
      category: 'తోలు కళ',
      price_inr: 1850,
      duration_mins: 150,
      max_participants: 8,
      lat: 16.7050,
      lng: 74.2433,
      location_name: 'కొల్హాపూర్',
      district: 'కొల్హాపూర్',
      state: 'మహారాష్ట్ర',
      cover_image: '/assets/images/Home%20page/Kolhapuri_Chappals_in_roadside_shop_in_Kolhapur3.jpeg',
      odop_tag: 'ODOP-MH-LEATHER',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_chanderi_01',
      artisan_id: 'art_chanderi_01',
      artisan_name: 'కమలా బాయి',
      artisan_avatar: '/assets/images/01-Hero/Chanderi_Craft_Village_–_Traditional_Weaving_and_Handicrafts_in_Madhya_Pradesh_01.jpg',
      trust_score: 97,
      title: 'చందేరి పట్టు చేనేత & జరీ నేత కళాశాల',
      description: 'స్వచ్ఛమైన మల్బరీ పట్టు మరియు బంగారు జరీతో మగ్గంపై నేత నేర్చుకోండి.',
      category: 'చేనేత',
      price_inr: 2200,
      duration_mins: 180,
      max_participants: 6,
      lat: 24.7120,
      lng: 78.1380,
      location_name: 'చందేరి',
      district: 'అశోక్‌నగర్',
      state: 'మధ్యప్రదేశ్',
      cover_image: '/assets/images/01-Hero/Chanderi_Craft_Village_–_Traditional_Weaving_and_Handicrafts_in_Madhya_Pradesh_01.jpg',
      odop_tag: 'ODOP-MP-SILK',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_majuli_01',
      artisan_id: 'art_majuli_01',
      artisan_name: 'హేమంత బోరా',
      artisan_avatar: '/assets/images/04-Bamboo-Cane/Innovative_Bamboo_Crafts_of_Assam.jpg',
      trust_score: 96,
      title: 'మజులి వెదురు ముసుగుల సంప్రదాయ వర్క్‌షాప్',
      description: 'బ్రహ్మపుత్ర నది మట్టి మరియు వెదురుతో 500 ఏళ్ల పురాతన ముసుగుల తయారీ.',
      category: 'వెదురు కళ',
      price_inr: 1950,
      duration_mins: 180,
      max_participants: 8,
      lat: 26.9500,
      lng: 94.2167,
      location_name: 'మజులి ద్వీపం',
      district: 'మజులి',
      state: 'అస్సాం',
      cover_image: '/assets/images/04-Bamboo-Cane/Innovative_Bamboo_Crafts_of_Assam.jpg',
      odop_tag: 'ODOP-AS-MASKS',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_srinagar_01',
      artisan_id: 'art_srinagar_01',
      artisan_name: 'గులాం మొహమ్మద్ జర్గర్',
      artisan_avatar: '/assets/images/05-Wood-Pottery/Kashmiri_Woodcarving_And_Paper_maché.jpg',
      trust_score: 99,
      title: 'కాశ్మీర్ అక్రోట్ చెక్క చెక్కడాల వర్క్‌షాప్',
      description: 'పురాతన శ్రీనగర్‌లో అక్రోట్ చెక్కపై సున్నితమైన చిక్కటి చెక్కడాల శిక్షణ.',
      category: 'చెక్క కళ',
      price_inr: 2500,
      duration_mins: 180,
      max_participants: 6,
      lat: 34.0837,
      lng: 74.7973,
      location_name: 'శ్రీనగర్',
      district: 'శ్రీనగర్',
      state: 'జమ్మూ & కాశ్మీర్',
      cover_image: '/assets/images/05-Wood-Pottery/Kashmiri_Woodcarving_And_Paper_maché.jpg',
      odop_tag: 'ODOP-JK-WALNUT',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_bishnupur_01',
      artisan_id: 'art_bishnupur_01',
      artisan_name: 'సుభాష్ కుంభకార్',
      artisan_avatar: '/assets/images/05-Wood-Pottery/Artisan_decorating_ceramic_plate.jpg',
      trust_score: 96,
      title: 'బాంకురా టెర్రకోటా గుర్రం & మట్టి కుండల వర్క్‌షాప్',
      description: 'కుమ్మరి చక్రంపై ప్రసిద్ధ బాంకురా గుర్రం తయారు చేయడం నేర్చుకోండి.',
      category: 'మట్టి కళ',
      price_inr: 1450,
      duration_mins: 150,
      max_participants: 8,
      lat: 23.0760,
      lng: 87.3190,
      location_name: 'బాంకురా',
      district: 'బాంకురా',
      state: 'పశ్చిమ బెంగాల్',
      cover_image: '/assets/images/05-Wood-Pottery/Artisan_decorating_ceramic_plate.jpg',
      odop_tag: 'ODOP-WB-HORSE',
      women_friendly: true,
      elderly_friendly: true
    }
  ],

  bn: [
    {
      id: 'exp_kolhapur_01',
      artisan_id: 'art_kolhapur_01',
      artisan_name: 'সন্তোষ কাম্বলে',
      artisan_avatar: '/assets/images/Home%20page/Kolhapuri_Chappals_in_roadside_shop_in_Kolhapur3.jpeg',
      trust_score: 98,
      title: 'ঐতিহ্যবাহী কোলহাপুরী চটি চামড়া শিল্প কর্মশালা',
      description: 'বাবলা গাছের ছাল দিয়ে প্রাকৃতিক চামড়া প্রক্রিয়াকরণ ও হাতে তৈরি কোলহাপুরী চটি বানানোর প্রশিক্ষণ।',
      category: 'চামড়া শিল্প',
      price_inr: 1850,
      duration_mins: 150,
      max_participants: 8,
      lat: 16.7050,
      lng: 74.2433,
      location_name: 'কোলহাপুর',
      district: 'কোলহাপুর',
      state: 'মহারাষ্ট্র',
      cover_image: '/assets/images/Home%20page/Kolhapuri_Chappals_in_roadside_shop_in_Kolhapur3.jpeg',
      odop_tag: 'ODOP-MH-LEATHER',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_chanderi_01',
      artisan_id: 'art_chanderi_01',
      artisan_name: 'কমলা বাঈ',
      artisan_avatar: '/assets/images/01-Hero/Chanderi_Craft_Village_–_Traditional_Weaving_and_Handicrafts_in_Madhya_Pradesh_01.jpg',
      trust_score: 97,
      title: 'রাজকীয় চান্দেরি রেশম তাঁত ও জরি বয়ন কর্মশালা',
      description: 'ঐতিহ্যবাহী তাঁতে বসে খাঁটি রেশম ও সোনার জরি দিয়ে চান্দেরি শাড়ি বয়ন শিখুন।',
      category: 'তাঁত শিল্প',
      price_inr: 2200,
      duration_mins: 180,
      max_participants: 6,
      lat: 24.7120,
      lng: 78.1380,
      location_name: 'চান্দেরি',
      district: 'অশোকনগর',
      state: 'মধ্যপ্রদেশ',
      cover_image: '/assets/images/01-Hero/Chanderi_Craft_Village_–_Traditional_Weaving_and_Handicrafts_in_Madhya_Pradesh_01.jpg',
      odop_tag: 'ODOP-MP-SILK',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_majuli_01',
      artisan_id: 'art_majuli_01',
      artisan_name: 'হেমন্ত বরা',
      artisan_avatar: '/assets/images/04-Bamboo-Cane/Innovative_Bamboo_Crafts_of_Assam.jpg',
      trust_score: 96,
      title: 'মাজুলী বাঁশের মুখোশ ও বেত শিল্প কর্মশালা',
      description: 'ব্রহ্মপুত্র নদের পলিমাটি ও বাঁশ দিয়ে ৫০০ বছরের পুরনো ঐতিহ্যবাহী মুখোশ তৈরি।',
      category: 'বাঁশ ও বেত শিল্প',
      price_inr: 1950,
      duration_mins: 180,
      max_participants: 8,
      lat: 26.9500,
      lng: 94.2167,
      location_name: 'মাজুলী দ্বীপ',
      district: 'মাজুলী',
      state: 'আসাম',
      cover_image: '/assets/images/04-Bamboo-Cane/Innovative_Bamboo_Crafts_of_Assam.jpg',
      odop_tag: 'ODOP-AS-MASKS',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_srinagar_01',
      artisan_id: 'art_srinagar_01',
      artisan_name: 'গুলাম মোহাম্মদ জরগর',
      artisan_avatar: '/assets/images/05-Wood-Pottery/Kashmiri_Woodcarving_And_Paper_maché.jpg',
      trust_score: 99,
      title: 'কাশ্মীরি আখরোট কাঠের খোদাই ও চিনার নকশা কর্মশালা',
      description: 'পুরানো শ্রীনগরে আখরোট কাঠের উপর সূক্ষ্ম চিনার পাতার খোদাইয়ের সরাসরি প্রশিক্ষণ।',
      category: 'কাঠের খোদাই',
      price_inr: 2500,
      duration_mins: 180,
      max_participants: 6,
      lat: 34.0837,
      lng: 74.7973,
      location_name: 'শ্রীনগর',
      district: 'শ্রীনগর',
      state: 'জম্মু ও কাশ্মীর',
      cover_image: '/assets/images/05-Wood-Pottery/Kashmiri_Woodcarving_And_Paper_maché.jpg',
      odop_tag: 'ODOP-JK-WALNUT',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_bishnupur_01',
      artisan_id: 'art_bishnupur_01',
      artisan_name: 'সুভাষ কুম্ভকার',
      artisan_avatar: '/assets/images/05-Wood-Pottery/Artisan_decorating_ceramic_plate.jpg',
      trust_score: 96,
      title: 'বিষ্ণুপুর বাঁকুড়া পোড়ামাটির ঘোড়া ও মন্দির টেরাকোটা কর্মশালা',
      description: 'কুমোরের চাকে বিশ্বখ্যাত বাঁকুড়ার টেরাকোটা ঘোড়া তৈরি ও কাঠের চুল্লিতে পোড়ানোর পদ্ধতি শিখুন।',
      category: 'পোড়ামাটি শিল্প',
      price_inr: 1450,
      duration_mins: 150,
      max_participants: 8,
      lat: 23.0760,
      lng: 87.3190,
      location_name: 'পাঁচমুড়া, বাঁকুড়া',
      district: 'বাঁকুড়া',
      state: 'পশ্চিমবঙ্গ',
      cover_image: '/assets/images/05-Wood-Pottery/Artisan_decorating_ceramic_plate.jpg',
      odop_tag: 'ODOP-WB-HORSE',
      women_friendly: true,
      elderly_friendly: true
    }
  ]
};

export interface LocalizedSlideItem {
  id: number;
  type: 'image' | 'video';
  src: string;
  craftName: string;
  tagline: string;
  location: string;
  badge: string;
}

export const LOCALIZED_HERO_SLIDES: Record<SupportedLanguage, LocalizedSlideItem[]> = {
  en: [
    {
      id: 0,
      type: 'image',
      src: '/assets/images/Home%20page/Kolhapuri_Chappals_in_roadside_shop_in_Kolhapur3.jpeg',
      craftName: "Ancestral Leathercraft",
      tagline: "Hand-stitched vegetable-tanned Kolhapuri Chappals from 4th-generation master cobblers.",
      location: "Kolhapur, Maharashtra",
      badge: "GI Tagged • 100% Herbal Tanned"
    },
    {
      id: 1,
      type: 'video',
      src: '/assets/images/Home%20page/local%20artist.mp4',
      craftName: "Master Artisan at Work",
      tagline: "Watch hereditary artisans hand-paint intricate heritage motifs and live brushstrokes.",
      location: "Living Atelier, India",
      badge: "Master Artisan Video"
    },
    {
      id: 2,
      type: 'image',
      src: '/assets/images/01-Hero/Chanderi_Craft_Village_–_Traditional_Weaving_and_Handicrafts_in_Madhya_Pradesh_01.jpg',
      craftName: "Royal Chanderi Silk",
      tagline: "Gossamer-weight pit-loom silk woven with delicate gold zari lotus and peacock motifs.",
      location: "Chanderi, Madhya Pradesh",
      badge: "700-Year Pit-Loom Lineage"
    },
    {
      id: 3,
      type: 'video',
      src: '/assets/images/Home%20page/Bamboo_basket_making.ogv',
      craftName: "Bamboo Basketry & Weaving",
      tagline: "Live demonstration of traditional bamboo split stripping and flexible grain basket weaving.",
      location: "Majuli & Western Ghats",
      badge: "Bamboo Craft Video"
    },
    {
      id: 4,
      type: 'image',
      src: '/assets/images/04-Bamboo-Cane/Cane_and_Bamboo_handicrafts_of_Assam.jpg',
      craftName: "Neo-Vaishnavite Bamboo & Masks",
      tagline: "Mukha masks & eco-friendly cane crafts sculpted with Brahmaputra riverbed silt.",
      location: "Majuli Island, Assam",
      badge: "UNESCO Heritage Contender"
    },
    {
      id: 5,
      type: 'video',
      src: '/assets/images/Home%20page/Handmade%20craft%20stall.mp4',
      craftName: "Living Craft Ateliers",
      tagline: "Experience the vibrant energy of authentic heritage stalls and master artisans at work.",
      location: "Bhavani Mandap Guilds, Maharashtra",
      badge: "Living Heritage Video"
    },
    {
      id: 6,
      type: 'image',
      src: '/assets/images/05-Wood-Pottery/Kashmiri_Woodcarving_And_Paper_maché.jpg',
      craftName: "Kashmir Walnut Wood Carving",
      tagline: "Deep 3D undercut relief carving on 4-year seasoned wild walnut root wood.",
      location: "Old Srinagar, J&K",
      badge: "GI Registered Craft Guild"
    },
    {
      id: 7,
      type: 'video',
      src: '/assets/images/Home%20page/old%20leddy%20crafting.mp4',
      craftName: "Master Weavers of India",
      tagline: "Watch living legends hand-spin peace-silk yarns and warp traditional wooden looms.",
      location: "Pranpur & Majuli Clusters",
      badge: "Ancestral Technique Video"
    },
    {
      id: 8,
      type: 'image',
      src: '/assets/images/05-Wood-Pottery/Artisan_decorating_ceramic_plate.jpg',
      craftName: "Living Terracotta Earthenware",
      tagline: "Wheel-thrown hollow terracotta Bankura horses and classical temple relief tiles.",
      location: "Bishnupur, West Bengal",
      badge: "4,000-Year Ancient Tradition"
    }
  ],
  hi: [
    {
      id: 0,
      type: 'image',
      src: '/assets/images/Home%20page/Kolhapuri_Chappals_in_roadside_shop_in_Kolhapur3.jpeg',
      craftName: "पारंपरिक कोल्हापुरी चर्मशिल्प",
      tagline: "चौथी पीढ़ी के सिद्ध हस्तशिल्पियों द्वारा बबूल की छाल और हरड़ से तैयार प्राकृतिक कोल्हापुरी चप्पलें।",
      location: "कोल्हापुर, महाराष्ट्र",
      badge: "जीआई टैग प्रमाणित • 100% वनस्पति टैनिंग"
    },
    {
      id: 1,
      type: 'video',
      src: '/assets/images/Home%20page/local%20artist.mp4',
      craftName: "सजीव कार्यशाला में उस्ताद कारीगर",
      tagline: "पारंपरिक सिद्धहस्त शिल्पकारों को लाइव बारीक धरोहर आकृतियां और कलाकृतियां बनाते देखें।",
      location: "जीवंत कार्यशाला, भारत",
      badge: "उस्ताद कारीगर वीडियो"
    },
    {
      id: 2,
      type: 'image',
      src: '/assets/images/01-Hero/Chanderi_Craft_Village_–_Traditional_Weaving_and_Handicrafts_in_Madhya_Pradesh_01.jpg',
      craftName: "शाही चंदेरी रेशम बुनाई",
      tagline: "700 वर्ष पुरानी खड्ड करघे की परंपरा, शुद्ध रेशम और सुनहरी जरी से निर्मित मोर-कमल बूटियां।",
      location: "चंदेरी, मध्य प्रदेश",
      badge: "700 वर्षीय खड्ड करघा परंपरा"
    },
    {
      id: 3,
      type: 'video',
      src: '/assets/images/Home%20page/Bamboo_basket_making.ogv',
      craftName: "बांस टोकरी निर्माण व नक्काशी",
      tagline: "पारंपरिक बांस की पट्टियों की छिलाई और हस्तनिर्मित टोकरी बुनाई का जीवंत प्रदर्शन।",
      location: "माजुली व पश्चिमी घाट",
      badge: "बांस शिल्प वीडियो"
    },
    {
      id: 4,
      type: 'image',
      src: '/assets/images/04-Bamboo-Cane/Cane_and_Bamboo_handicrafts_of_Assam.jpg',
      craftName: "नव-वैष्णव मुखा बांस मुखौटा",
      tagline: "ब्रह्मपुत्र नदी की गाद व बांस के ढांचे से निर्मित 500 वर्ष पुराने पौराणिक मुखौटे।",
      location: "माजुली द्वीप, असम",
      badge: "यूनेस्को धरोहर दावेदार"
    },
    {
      id: 5,
      type: 'video',
      src: '/assets/images/Home%20page/Handmade%20craft%20stall.mp4',
      craftName: "जीवंत शिल्प हाट व कारीगर",
      tagline: "पारंपरिक कारीगरों के प्रामाणिक शिल्प स्टॉल और कार्यशालाओं की जीवंत ऊर्जा का अनुभव करें।",
      location: "भवानी मंडप, महाराष्ट्र",
      badge: "सजीव धरोहर वीडियो"
    },
    {
      id: 6,
      type: 'image',
      src: '/assets/images/05-Wood-Pottery/Kashmiri_Woodcarving_And_Paper_maché.jpg',
      craftName: "कश्मीरी अखरोट काष्ठ नक्काशी",
      tagline: "4 वर्ष सुखाए गए अखरोट की जड़ पर थ्री-डी उभारदार चिनार पत्तों की हस्त नक्काशी।",
      location: "पुराना श्रीनगर, जम्मू-कश्मीर",
      badge: "जीआई पंजीकृत शिल्प गिल्ड"
    },
    {
      id: 7,
      type: 'video',
      src: '/assets/images/Home%20page/old%20leddy%20crafting.mp4',
      craftName: "भारत के महान बुनकर",
      tagline: "जीवंत किंवदंतियों को पारंपरिक लकड़ी के करघों पर रेशम के धागों को बुनते हुए देखें।",
      location: "प्राणपुर व माजुली क्लस्टर",
      badge: "पारंपरिक तकनीक वीडियो"
    },
    {
      id: 8,
      type: 'image',
      src: '/assets/images/05-Wood-Pottery/Artisan_decorating_ceramic_plate.jpg',
      craftName: "जीवंत टेराकोटा व बांकुड़ा अश्व",
      tagline: "चाक पर गढ़ी खोखली टेराकोटा मूर्तियां और सदियों पुरानी प्राचीन मंदिर टाइल्स।",
      location: "विष्णुपुर, पश्चिम बंगाल",
      badge: "4,000 वर्ष प्राचीन परंपरा"
    }
  ],
  mr: [
    {
      id: 0,
      type: 'image',
      src: '/assets/images/Home%20page/Kolhapuri_Chappals_in_roadside_shop_in_Kolhapur3.jpeg',
      craftName: "अभिजात कोल्हापुरी चर्मकला",
      tagline: "चौथ्या पिढीतील कसबी कारागिरांनी बाभळीच्या सालीच्या नैसर्गिक टॅनिंगने हाताने शिवलेली चप्पल.",
      location: "कोल्हापूर, महाराष्ट्र",
      badge: "जीआय मानांकन • १००% वनस्पती टॅनिंग"
    },
    {
      id: 1,
      type: 'video',
      src: '/assets/images/Home%20page/local%20artist.mp4',
      craftName: "कार्यरत ज्येष्ठ हस्तकलाकार",
      tagline: "पारंपरिक कारागिरांना जिवंत कलेचे नक्षीकाम आणि कुंचल्याचे फटकारे मारताना प्रत्यक्ष पहा.",
      location: "प्रत्यक्ष कार्यशाळा, भारत",
      badge: "मास्टर आर्टिसन व्हिडिओ"
    },
    {
      id: 2,
      type: 'image',
      src: '/assets/images/01-Hero/Chanderi_Craft_Village_–_Traditional_Weaving_and_Handicrafts_in_Madhya_Pradesh_01.jpg',
      craftName: "शाही चंदेरी रेशीम विणकाम",
      tagline: "७०० वर्षांची खड्डा हातमाग परंपरा, शुद्ध रेशीम व सुवर्ण जरीने विणलेली मोर-कमळ बुट्टी.",
      location: "चंदेरी, मध्य प्रदेश",
      badge: "७०० वर्षांची पिढीजात परंपरा"
    },
    {
      id: 3,
      type: 'video',
      src: '/assets/images/Home%20page/Bamboo_basket_making.ogv',
      craftName: "बांबू टोपली विणकाम व कला",
      tagline: "पारंपरिक बांबूच्या कामट्या काढणे आणि मजबूत टोपल्या विणण्याचे थेट प्रात्यक्षिक.",
      location: "माजुली व सह्याद्री पट्टा",
      badge: "बांबू हस्तकला व्हिडिओ"
    },
    {
      id: 4,
      type: 'image',
      src: '/assets/images/04-Bamboo-Cane/Cane_and_Bamboo_handicrafts_of_Assam.jpg',
      craftName: "नव-वैष्णव मुखा बांबू मुखवटा",
      tagline: "ब्रह्मपुत्रेचा गाळ व बांबूच्या कामट्यांपासून बनवलेले ५०० वर्षे जुने पौराणिक मुखवटे.",
      location: "माजुली बेट, आसाम",
      badge: "युनेस्को वारसा दावेदार"
    },
    {
      id: 5,
      type: 'video',
      src: '/assets/images/Home%20page/Handmade%20craft%20stall.mp4',
      craftName: "पारंपरिक कारागीर स्टॉल्स",
      tagline: "भवानी मंडपातील कारागिरांचा थेट उत्साह आणि अस्सल हस्तकलेची ऊर्जा अनुभवा.",
      location: "भवानी मंडप, कोल्हापूर",
      badge: "वारसा व्हिडिओ"
    },
    {
      id: 6,
      type: 'image',
      src: '/assets/images/05-Wood-Pottery/Kashmiri_Woodcarving_And_Paper_maché.jpg',
      craftName: "काश्मिरी अक्रोड लाकूड कोरीवकाम",
      tagline: "४ वर्षे वाळवलेल्या अक्रोड मुळांच्या लाकडावर ३डी चिनार पानांचे हस्त कोरीवकाम.",
      location: "जुने श्रीनगर, जम्मू-काश्मीर",
      badge: "जीआय नोंदणीकृत गिल्ड"
    },
    {
      id: 7,
      type: 'video',
      src: '/assets/images/Home%20page/old%20leddy%20crafting.mp4',
      craftName: "भारतातील ज्येष्ठ विणकर",
      tagline: "पारंपरिक लाकडी हातमागांवर रेशमाचे धागे विणणाऱ्या ज्येष्ठ विणकरांची कला पहा.",
      location: "प्राणपूर व माजुली क्लस्टर",
      badge: "पारंपरिक तंत्रज्ञान व्हिडिओ"
    },
    {
      id: 8,
      type: 'image',
      src: '/assets/images/05-Wood-Pottery/Artisan_decorating_ceramic_plate.jpg',
      craftName: "जिवंत टेराकोटा मातीकाम",
      tagline: "कुंभाराच्या चाकावर बनवलेले बांकुडा घोडे आणि प्राचीन मंदिरांच्या टेराकोटा टाइल्स.",
      location: "विष्णुपूर, पश्चिम बंगाल",
      badge: "४,००० वर्षांची प्राचीन परंपरा"
    }
  ],
  ta: [
    {
      id: 0,
      type: 'image',
      src: '/assets/images/Home%20page/Kolhapuri_Chappals_in_roadside_shop_in_Kolhapur3.jpeg',
      craftName: "பழங்கால கோலாப்பூரி தோல் கைவினை",
      tagline: "4வது தலைமுறை கைவினைஞர்களின் இயற்கை தோல் பதனிடுதல் முறையில் தைக்கப்பட்ட கோலாப்பூரி செருப்புகள்.",
      location: "கோலாப்பூர், மகாராஷ்டிரா",
      badge: "புவிசார் குறியீடு • 100% மூலிகை தோல்"
    },
    {
      id: 1,
      type: 'video',
      src: '/assets/images/Home%20page/local%20artist.mp4',
      craftName: "பணியில் உள்ள முதன்மை கைவினைஞர்",
      tagline: "பாரம்பரிய கலைஞர்கள் நுணுக்கமான ஓவியங்களை வரையும் நேரலை காட்சியை காண்க.",
      location: "நேரலை பட்டறை, இந்தியா",
      badge: "முதன்மை கலைஞர் வீடியோ"
    },
    {
      id: 2,
      type: 'image',
      src: '/assets/images/01-Hero/Chanderi_Craft_Village_–_Traditional_Weaving_and_Handicrafts_in_Madhya_Pradesh_01.jpg',
      craftName: "ராஜ சந்தேரி பட்டு நெசவு",
      tagline: "700 ஆண்டுகள் பழமையான குழித்தறி நெசவு, தூய பட்டு மற்றும் தங்க ஜரிகை பூ வேலைப்பாடுகள்.",
      location: "சந்தேரி, மத்திய பிரதேசம்",
      badge: "700 ஆண்டு குழித்தறி பாரம்பரியம்"
    },
    {
      id: 3,
      type: 'video',
      src: '/assets/images/Home%20page/Bamboo_basket_making.ogv',
      craftName: "மூங்கில் கூடை முடைதல்",
      tagline: "பாரம்பரிய மூங்கில் கீற்றுகள் மற்றும் கைவினை கூடைகள் தயாரிக்கும் நேரலை செயல்முறை.",
      location: "மஜூலி & மேற்கு தொடர்ச்சி மலை",
      badge: "மூங்கில் கைவினை வீடியோ"
    },
    {
      id: 4,
      type: 'image',
      src: '/assets/images/04-Bamboo-Cane/Cane_and_Bamboo_handicrafts_of_Assam.jpg',
      craftName: "முகா மூங்கில் முகமூடி",
      tagline: "பிரம்மபுத்திரா ஆற்று வண்டல் மண் மற்றும் மூங்கில் கொண்டு செய்யப்படும் 500 ஆண்டு முகமூடிகள்.",
      location: "மஜூலி தீவு, அசாம்",
      badge: "யுனெஸ்கோ பாரம்பரிய உரிமை"
    },
    {
      id: 5,
      type: 'video',
      src: '/assets/images/Home%20page/Handmade%20craft%20stall.mp4',
      craftName: "கைவினை மையங்கள்",
      tagline: "பாரம்பரிய கைவினைஞர்களின் பட்டறைகள் மற்றும் நேரலை கலை உருவாக்கத்தை அனுபவிக்கவும்.",
      location: "பவானி மண்டபம், மகாராஷ்டிரா",
      badge: "பாரம்பரிய வீடியோ"
    },
    {
      id: 6,
      type: 'image',
      src: '/assets/images/05-Wood-Pottery/Kashmiri_Woodcarving_And_Paper_maché.jpg',
      craftName: "காஷ்மீர் வாதுமை மர செதுக்கல்",
      tagline: "4 ஆண்டுகள் பதப்படுத்தப்பட்ட வாதுமை மரத்தில் செய்யப்படும் முப்பரிமாண பூ வேலைப்பாடுகள்.",
      location: "பழைய ஸ்ரீநகர், ஜம்மு காஷ்மீர்",
      badge: "புவிசார் குறியீடு பதிவு"
    },
    {
      id: 7,
      type: 'video',
      src: '/assets/images/Home%20page/old%20leddy%20crafting.mp4',
      craftName: "இந்தியாவின் தலைசிறந்த நெசவாளர்கள்",
      tagline: "மரத்தறிகளில் பட்டு நூல்களை நெய்யும் பாரம்பரிய நெசவாளர்களை காண்க.",
      location: "பிரான்பூர் & மஜூலி",
      badge: "பாரம்பரிய நுட்ப வீடியோ"
    },
    {
      id: 8,
      type: 'image',
      src: '/assets/images/05-Wood-Pottery/Artisan_decorating_ceramic_plate.jpg',
      craftName: "சுடுமண் மண்பாண்டம் & பாங்குரா குதிரை",
      tagline: "மண்பாண்ட சக்கரத்தில் செய்யப்படும் உலகப் புகழ்பெற்ற பாங்குரா சுடுமண் குதிரைகள்.",
      location: "விஷ்ணுபூர், மேற்கு வங்காளம்",
      badge: "4,000 ஆண்டு பழமையான பாரம்பரியம்"
    }
  ],
  te: [
    {
      id: 0,
      type: 'image',
      src: '/assets/images/Home%20page/Kolhapuri_Chappals_in_roadside_shop_in_Kolhapur3.jpeg',
      craftName: "సాంప్రదాయ కొల్హాపూరి తోలు కళ",
      tagline: "4వ తరం నైపుణ్యం కలిగిన కళాకారులచే చేతితో కుట్టబడిన సహజ తోలు చెప్పులు.",
      location: "కొల్హాపూర్, మహారాష్ట్ర",
      badge: "జిఐ ట్యాగ్ గుర్తింపు • 100% మూలికా ట్యానింగ్"
    },
    {
      id: 1,
      type: 'video',
      src: '/assets/images/Home%20page/local%20artist.mp4',
      craftName: "పనిలో ఉన్న ప్రముఖ కళాకారుడు",
      tagline: "వంశపారంపర్య కళాకారులు అందమైన కళాఖండాలను తీర్చిదిద్దే ప్రత్యక్ష దృశ్యం.",
      location: "ప్రత్యక్ష వర్క్‌షాప్, భారతదేశం",
      badge: "మాస్టర్ ఆర్టిసన్ వీడియో"
    },
    {
      id: 2,
      type: 'image',
      src: '/assets/images/01-Hero/Chanderi_Craft_Village_–_Traditional_Weaving_and_Handicrafts_in_Madhya_Pradesh_01.jpg',
      craftName: "రాజ చందేరి పట్టు నేత",
      tagline: "700 సంవత్సరాల పురాతన గుంత మగ్గం నేత, స్వచ్ఛమైన పట్టు మరియు బంగారు జరీ బూటీలు.",
      location: "చందేరి, మధ్యప్రదేశ్",
      badge: "700 ఏళ్ల గుంత మగ్గం సంప్రదాయం"
    },
    {
      id: 3,
      type: 'video',
      src: '/assets/images/Home%20page/Bamboo_basket_making.ogv',
      craftName: "వెదురు బుట్టల అల్లిక & కళ",
      tagline: "సాంప్రదాయ వెదురు బద్దల తయారీ మరియు చేతితో బుట్టల అల్లిక ప్రత్యక్ష ప్రదర్శన.",
      location: "మజులి & పశ్చిమ కనుమలు",
      badge: "వెదురు హస్తకళ వీడియో"
    },
    {
      id: 4,
      type: 'image',
      src: '/assets/images/04-Bamboo-Cane/Cane_and_Bamboo_handicrafts_of_Assam.jpg',
      craftName: "ముఖా వెదురు ముసుగుల తయారీ",
      tagline: "బ్రహ్మపుత్ర నది మట్టి మరియు వెదురుతో రూపొందించిన 500 ఏళ్ల పౌరాణిక ముసుగులు.",
      location: "మజులి ద్వీపం, అస్సాం",
      badge: "యునెస్కో వారసత్వ అభ్యర్థి"
    },
    {
      id: 5,
      type: 'video',
      src: '/assets/images/Home%20page/Handmade%20craft%20stall.mp4',
      craftName: "ప్రత్యక్ష హస్తకళా కేంద్రాలు",
      tagline: "సాంప్రదాయ కళాకారుల స్టాళ్లు మరియు ప్రామాణికమైన హస్తకళల ప్రత్యక్ష అనుభూతి.",
      location: "భవాని మండపం, మహారాష్ట్ర",
      badge: "సజీవ వారసత్వ వీడియో"
    },
    {
      id: 6,
      type: 'image',
      src: '/assets/images/05-Wood-Pottery/Kashmiri_Woodcarving_And_Paper_maché.jpg',
      craftName: "కాశ్మీరీ అక్రోట్ చెక్క చెక్కడాలు",
      tagline: "4 సంవత్సరాలు ఎండబెట్టిన అక్రోట్ వేరు చెక్కపై 3D పూల చెక్కడాలు.",
      location: "పాత శ్రీనగర్, జమ్మూ కాశ్మీర్",
      badge: "జిఐ నమోదిత గిల్డ్"
    },
    {
      id: 7,
      type: 'video',
      src: '/assets/images/Home%20page/old%20leddy%20crafting.mp4',
      craftName: "భారతదేశ ప్రముఖ చేనేతకారులు",
      tagline: "చెక్క మగ్గాలపై పట్టు దారాలను నేసే వంశపారంపర్య నేత కళాకారులను వీక్షించండి.",
      location: "ప్రాణ్‌పూర్ & మజులి",
      badge: "సాంప్రదాయ పద్ధతుల వీడియో"
    },
    {
      id: 8,
      type: 'image',
      src: '/assets/images/05-Wood-Pottery/Artisan_decorating_ceramic_plate.jpg',
      craftName: "టెర్రకోట మట్టి కళ & బాంకురా గుర్రం",
      tagline: "కుమ్మరి చక్రంపై తయారు చేయబడిన ప్రపంచ ప్రసిద్ధ బాంకురా టెర్రకోట గుర్రాలు.",
      location: "విష్ణుపూర్, పశ్చిమ బెంగాల్",
      badge: "4,000 సంవత్సరాల పురాతన సంప్రదాయం"
    }
  ],
  bn: [
    {
      id: 0,
      type: 'image',
      src: '/assets/images/Home%20page/Kolhapuri_Chappals_in_roadside_shop_in_Kolhapur3.jpeg',
      craftName: "ঐতিহ্যবাহী কোলহাপুরী চামড়াশিল্প",
      tagline: "চতুর্থ প্রজন্মের অভিজ্ঞ কারিগরদের বাবলা ছাল ও হরিতকী দিয়ে সম্পূর্ণ ভেষজ পদ্ধতিতে তৈরি কোলহাপুরী চটি।",
      location: "কোলহাপুর, মহারাষ্ট্র",
      badge: "জিআই ট্যাগ প্রাপ্ত • ১০০% ভেষজ ট্যানিং"
    },
    {
      id: 1,
      type: 'video',
      src: '/assets/images/Home%20page/local%20artist.mp4',
      craftName: "কর্মরত প্রধান কারিগর",
      tagline: "বংশপরম্পরা কারিগরদের সরাসরি ঐতিহ্যবাহী নকশা ও তুলির ছোঁয়ায় শিল্পকর্ম তৈরি দেখুন।",
      location: "সরাসরি কর্মশালা, ভারত",
      badge: "মাস্টার আর্টিসান ভিডিও"
    },
    {
      id: 2,
      type: 'image',
      src: '/assets/images/01-Hero/Chanderi_Craft_Village_–_Traditional_Weaving_and_Handicrafts_in_Madhya_Pradesh_01.jpg',
      craftName: "রাজকীয় চন্দেরী সিল্ক বয়ন",
      tagline: "৭০০ বছরের প্রাচীন মাটির খাদ তাঁত ঐতিহ্য, খাঁটি রেশম ও সোনালী জরির ময়ূর-পদ্ম বুটি।",
      location: "চন্দেরী, মধ্যপ্রদেশ",
      badge: "৭০০ বছরের প্রাচীন খাদ তাঁত"
    },
    {
      id: 3,
      type: 'video',
      src: '/assets/images/Home%20page/Bamboo_basket_making.ogv',
      craftName: "বাঁশের ঝুড়ি তৈরি ও বয়ন",
      tagline: "বাঁশের ঐতিহ্যবাহী চ্যাঁটাই কাটা ও মজবুত ঝুড়ি বোনার সরাসরি প্রদর্শনী।",
      location: "মাজুলী ও পশ্চিমঘাট",
      badge: "বাঁশ শিল্প ভিডিও"
    },
    {
      id: 4,
      type: 'image',
      src: '/assets/images/04-Bamboo-Cane/Cane_and_Bamboo_handicrafts_of_Assam.jpg',
      craftName: "নব-বৈষ্ণব মুখা বাঁশের মুখোশ",
      tagline: "ব্রহ্মপুত্রের পলিমাটি ও বাঁশের কাঠামোয় তৈরি ৫০০ বছরের প্রাচীন পৌরাণিক মুখোশ।",
      location: "মাজুলী দ্বীপ, আসাম",
      badge: "ইউনেস্কো ঐতিহ্য দাবিদার"
    },
    {
      id: 5,
      type: 'video',
      src: '/assets/images/Home%20page/Handmade%20craft%20stall.mp4',
      craftName: "সরাসরি হস্তশিল্প হাট",
      tagline: "ঐতিহ্যবাহী কারিগরদের খাঁটি স্টল ও কাজের প্রাণবন্ত পরিবেশ উপভোগ করুন।",
      location: "ভবানী মণ্ডপ, মহারাষ্ট্র",
      badge: "জীবন্ত ঐতিহ্য ভিডিও"
    },
    {
      id: 6,
      type: 'image',
      src: '/assets/images/05-Wood-Pottery/Kashmiri_Woodcarving_And_Paper_maché.jpg',
      craftName: "কাশ্মীরি আখরোট কাঠ খোদাই",
      tagline: "৪ বছর শুকানো আখরোটের শিকড় কাঠের উপর ত্রিমাত্রিক চিনার পাতার সূক্ষ্ম খোদাই।",
      location: "পুরানো শ্রীনগর, জম্মু ও কাশ্মীর",
      badge: "জিআই নিবন্ধিত সমবায়"
    },
    {
      id: 7,
      type: 'video',
      src: '/assets/images/Home%20page/old%20leddy%20crafting.mp4',
      craftName: "ভারতের শ্রেষ্ঠ তাঁতশিল্পী",
      tagline: "ঐতিহ্যবাহী কাঠের তাঁতে রেশমের সুতো বুনতে থাকা বর্ষীয়ান তাঁতিদের দেখুন।",
      location: "প্রাণপুর ও মাজুলী",
      badge: "ঐতিহ্যবাহী প্রযুক্তি ভিডিও"
    },
    {
      id: 8,
      type: 'image',
      src: '/assets/images/05-Wood-Pottery/Artisan_decorating_ceramic_plate.jpg',
      craftName: "বাঁকুড়া পোড়ামাটি ও টেরাকোটা ঘোড়া",
      tagline: "কুমোরের চাকে তৈরি বিশ্বখ্যাত বাঁকুড়ার টেরাকোটা ঘোড়া ও মন্দির টালি।",
      location: "বিষ্ণুপুর, পশ্চিমবঙ্গ",
      badge: "৪,০০০ বছরের প্রাচীন ঐতিহ্য"
    }
  ]
};

export const LOCALIZED_HOMEPAGE_UI: Record<SupportedLanguage, {
  discoverHeading: string;
  verifiedArtisansBadge: string;
  giTagBadge: string;
  directIncomeBadge: string;
  searchPlaceholder: string;
  allCraftsCategory: string;
  workshopsHeading: string;
  workshopsSubtitle: string;
  viewAtelierBtn: string;
  bookBtn: string;
  trustScoreLabel: string;
  heritageMapHeading: string;
  heritageMapSubtitle: string;
  activeAteliersLabel: string;
}> = {
  en: {
    discoverHeading: "Discover India's",
    verifiedArtisansBadge: "100% Verified Hereditary Artisans",
    giTagBadge: "GI Tag Protected Crafts",
    directIncomeBadge: "96% Direct-to-Artisan Payouts",
    searchPlaceholder: "Search by craft, artisan name, village or district...",
    allCraftsCategory: "All Crafts",
    workshopsHeading: "Master Artisan Workshops",
    workshopsSubtitle: "Handcrafted living lineages, direct atelier sessions & GI-certified masterclasses",
    viewAtelierBtn: "View Atelier & Book →",
    bookBtn: "Book Workshop",
    trustScoreLabel: "Trust Score",
    heritageMapHeading: "Living Heritage Craft Map",
    heritageMapSubtitle: "Locate authentic hereditary artisan clusters across India with Survey of India administrative accuracy",
    activeAteliersLabel: "Verified Craft Ateliers Active"
  },
  hi: {
    discoverHeading: "अनुभव करें भारत का",
    verifiedArtisansBadge: "100% सत्यापित वंशानुगत कारीगर",
    giTagBadge: "जीआई टैग संरक्षित हस्तशिल्प",
    directIncomeBadge: "96% सीधा कारीगर भुगतान",
    searchPlaceholder: "शिल्प, कारीगर का नाम, गांव या जिला खोजें...",
    allCraftsCategory: "सभी हस्तशिल्प",
    workshopsHeading: "उस्ताद कारीगर कार्यशालाएं",
    workshopsSubtitle: "हस्तनिर्मित जीवंत धरोहर, प्रत्यक्ष कार्यशाला सत्र और जीआई प्रमाणित मास्टरक्लास",
    viewAtelierBtn: "कार्यशाला देखें व बुक करें →",
    bookBtn: "वर्कशॉप बुक करें",
    trustScoreLabel: "सत्यापन स्कोर",
    heritageMapHeading: "सजीव धरोहर शिल्प मानचित्र",
    heritageMapSubtitle: "सर्वे ऑफ इंडिया प्रशासनिक सटीकता के साथ भारत भर के प्रामाणिक कारीगर समूहों को खोजें",
    activeAteliersLabel: "सत्यापित शिल्प कार्यशालाएं सक्रिय"
  },
  mr: {
    discoverHeading: "अनुभवा भारताची",
    verifiedArtisansBadge: "१००% सत्यापित पिढीजात कारागीर",
    giTagBadge: "जीआय मानांकन संरक्षित कला",
    directIncomeBadge: "९६% थेट कारागिरांना उत्पन्न",
    searchPlaceholder: "हस्तकला, कारागिराचे नाव, गाव किंवा जिल्हा शोधा...",
    allCraftsCategory: "सर्व हस्तकला",
    workshopsHeading: "मास्टर कारागीर कार्यशाळा",
    workshopsSubtitle: "हस्तनिर्मित जिवंत परंपरा, प्रत्यक्ष कार्यशाळा आणि जीआय प्रमाणित मास्टरक्लास",
    viewAtelierBtn: "कार्यशाळा पहा व नोंदणी करा →",
    bookBtn: "कार्यशाळा बुक करा",
    trustScoreLabel: "सत्यापन स्कोअर",
    heritageMapHeading: "वारसा हस्तकला नकाशा",
    heritageMapSubtitle: "सर्व्हे ऑफ इंडियाच्या प्रशासकीय अचूकतेसह भारतातील अस्सल कारागीर क्लस्टर्स शोधा",
    activeAteliersLabel: "सत्यापित कार्यशाळा सक्रिय"
  },
  ta: {
    discoverHeading: "இந்தியாவின் அனுபவம்",
    verifiedArtisansBadge: "100% சரிபார்க்கப்பட்ட கைவினைஞர்கள்",
    giTagBadge: "புவிசார் குறியீடு பாதுகாக்கப்பட்ட கலை",
    directIncomeBadge: "96% நேரடி கலைஞர் வருவாய்",
    searchPlaceholder: "கைவினை, கலைஞர் பெயர், கிராமம் அல்லது மாவட்டத்தை தேடுங்கள்...",
    allCraftsCategory: "அனைத்து கைவினைகளும்",
    workshopsHeading: "முதன்மை கலைஞர் பட்டறைகள்",
    workshopsSubtitle: "பாரம்பரிய நேரடி பட்டறை அமர்வுகள் மற்றும் சான்றளிக்கப்பட்ட வகுப்புகள்",
    viewAtelierBtn: "பட்டறையை காண்க & முன்பதிவு செய்க →",
    bookBtn: "முன்பதிவு செய்க",
    trustScoreLabel: "நம்பகத்தன்மை மதிப்பீடு",
    heritageMapHeading: "பாரம்பரிய கைவினை வரைபடம்",
    heritageMapSubtitle: "இந்திய அளவிலான அதிகாரப்பூர்வ நிர்வாக துல்லியத்துடன் கலைஞர் மையங்களை கண்டறியவும்",
    activeAteliersLabel: "சரிபார்க்கப்பட்ட பட்டறைகள் இயங்குகின்றன"
  },
  te: {
    discoverHeading: "భారతదేశ అద్భుతమైన",
    verifiedArtisansBadge: "100% ధృవీకరించబడిన వంశపారంపర్య కళాకారులు",
    giTagBadge: "జిఐ ట్యాగ్ రక్షిత హస్తకళలు",
    directIncomeBadge: "96% కళాకారులకు నేరుగా చెల్లింపు",
    searchPlaceholder: "కళ, కళాకారుడి పేరు, గ్రామం లేదా జిల్లాను శోధించండి...",
    allCraftsCategory: "అన్ని హస్తకళలు",
    workshopsHeading: "మాస్టర్ ఆర్టిసన్ వర్క్‌షాప్‌లు",
    workshopsSubtitle: "హస్తకళల ప్రత్యక్ష వర్క్‌షాప్ సెషన్‌లు మరియు జిఐ సర్టిఫైడ్ మాస్టర్‌క్లాస్‌లు",
    viewAtelierBtn: "వర్క్‌షాప్‌ను వీక్షించి బుక్ చేయండి →",
    bookBtn: "బుక్ చేయండి",
    trustScoreLabel: "నమ్మక స్కోరు",
    heritageMapHeading: "సజీవ వారసత్వ హస్తకళా పటం",
    heritageMapSubtitle: "సర్వే ఆఫ్ ఇండియా ఖచ్చితత్వంతో భారతదేశం అంతటా ప్రామాణికమైన కళాకారుల క్లస్టర్‌లను గుర్తించండి",
    activeAteliersLabel: "ధృవీకరించబడిన వర్క్‌షాప్‌లు యాక్టివ్‌గా ఉన్నాయి"
  },
  bn: {
    discoverHeading: "আবিষ্কার করুন ভারতের",
    verifiedArtisansBadge: "১০০% যাচাইকৃত বংশপরম্পরা কারিগর",
    giTagBadge: "জিআই ট্যাগ সুরক্ষিত হস্তশিল্প",
    directIncomeBadge: "৯৬% সরাসরি কারিগরের আয়",
    searchPlaceholder: "শিল্প, কারিগরের নাম, গ্রাম বা জেলা খুঁজুন...",
    allCraftsCategory: "সকল শিল্পকলা",
    workshopsHeading: "উস্তাদ কারিগর কর্মশালা",
    workshopsSubtitle: "হস্তনির্মিত জীবন্ত ঐতিহ্য, সরাসরি কর্মশালা ও জিআই প্রত্যয়িত মাস্টারক্লাস",
    viewAtelierBtn: "কর্মশালা দেখুন ও বুক করুন →",
    bookBtn: "বুক করুন",
    trustScoreLabel: "যাচাইকরণ স্কোর",
    heritageMapHeading: "ঐতিহ্যবাহী হস্তশিল্প মানচিত্র",
    heritageMapSubtitle: "সার্ভে অফ ইন্ডিয়ার প্রশাসনিক নির্ভুলতার সাথে সমগ্র ভারতের খাঁটি কারিগর দল খুঁজুন",
    activeAteliersLabel: "সক্রিয় যাচাইকৃত কর্মশালা"
  }
};



export const CULTURAL_EXPERIENCES: CulturalExperience[] = [
  {
    id: 'cult_01',
    title: 'Traditional Marma & Indigenous Bone-Setting Lineage',
    tradition_name: 'Marma Chikitsa & Herbal Poultices',
    description: 'Centuries-old hereditary orthopedic healing and joint alignment practiced through botanical oils, bamboo splints, and generational touch techniques.',
    category: 'Community Medicine',
    location_name: 'Puttur & Malabar Belt',
    district: 'Chittoor',
    state: 'Andhra Pradesh',
    lat: 13.4418,
    lng: 79.5539,
    cover_image: '/assets/images/Culture/Traditional_Bone_Setting.jpg',
    season: 'Year-round traditional consultations',
    community_custodians: 'Vaidya Kshatriya & Marma Guilds',
    trust_score: 99,
    significance: 'Recognized under Ministry of AYUSH traditional indigenous medicine repositories.'
  },
  {
    id: 'cult_02',
    title: 'Bodo-Kachari Indigenous Loom Songs & Spring Customs',
    tradition_name: 'Bagurumba Dance & Dokhona Silk Rites',
    description: 'Ancestral butterfly-movement spring rituals accompanied by Kham drums, Sifung flutes, and hand-spun floral Dokhona ceremonial weaving.',
    category: 'Tribal Customs',
    location_name: 'Kokrajhar Bodoland',
    district: 'Kokrajhar',
    state: 'Assam',
    lat: 26.4014,
    lng: 90.2716,
    cover_image: '/assets/images/Culture/Bodo-Kachari_2.jpg',
    season: 'Bwisagu Spring Festival (April)',
    community_custodians: 'Bodo Women Weaving & Cultural Guild',
    trust_score: 97,
    significance: 'UNESCO Intangible Folk Heritage Documentation.'
  },
  {
    id: 'cult_03',
    title: 'Dhunuchi Naach & Kumartuli Clay Deity Invocation',
    tradition_name: 'Sacred Dhunuchi Aarti with Dhak Rhythm',
    description: 'Ecstatic clay-censer devotional dance with burning coconut husk and camphor, celebrating the living artisan deity sculpted from holy Ganges clay.',
    category: 'Sacred Rituals',
    location_name: 'Kumartuli Ghats, Kolkata',
    district: 'Kolkata',
    state: 'West Bengal',
    lat: 22.5986,
    lng: 88.3639,
    cover_image: '/assets/images/Culture/Dancing_mood_of_Durga_Puja.jpg',
    season: 'Sharadotsav (September – October)',
    community_custodians: 'Kumartuli Sculptors Guild & Dhakis',
    trust_score: 98,
    significance: 'UNESCO Representative List of the Intangible Cultural Heritage of Humanity.'
  },
  {
    id: 'cult_04',
    title: 'Kokan Shimga Palakhi Nrutya (Village Deities Palanquin Dance)',
    tradition_name: 'Shimagotsav Ancestral Palanquin Swaying',
    description: 'Spectacular village gathering where hereditary bearers dance through narrow betel-nut groves carrying sacred wooden palanquins of gram-daivatas.',
    category: 'Seasonal Festival',
    location_name: 'Konkan Coastal Villages',
    district: 'Ratnagiri',
    state: 'Maharashtra',
    lat: 16.9902,
    lng: 73.3120,
    cover_image: '/assets/images/Culture/Palakhinrutya_-_Dance_of_Palanquin_of_Village_Dities_-_Shimagotsav_in_Kokan_-_Maharashtra.jpg',
    season: 'Holi / Shimga (March)',
    community_custodians: 'Kokan Gramstha & Tarang Custodians',
    trust_score: 96,
    significance: '400-year-old coastal Konkan agrarian community cohesion ritual.'
  },
  {
    id: 'cult_05',
    title: 'Bhil & Bhilala Bhagoria Haat Festival of Colors',
    tradition_name: 'Tribal Harvest Courtship & Dhol Assemblies',
    description: 'Vibrant tribal carnival of giant dhol drums, brass ornaments, gulal celebrations, and community bonding across the Vindhyan hills.',
    category: 'Seasonal Festival',
    location_name: 'Jhabua Tribal Belt',
    district: 'Jhabua',
    state: 'Madhya Pradesh',
    lat: 22.7699,
    lng: 74.5936,
    cover_image: '/assets/images/Culture/The_Bhagoria_festival.jpg',
    season: 'Week preceding Holi (March)',
    community_custodians: 'Bhil & Bhilala Tribal Elders',
    trust_score: 97,
    significance: 'Ancient indigenous harvest Thanksgiving and agrarian matchmaking fair.'
  },
  {
    id: 'cult_06',
    title: 'Chhath Mahaparv — Vedic Riverbank Solar Worship',
    tradition_name: 'Riverbed Arghya with Handmade Bamboo Soop',
    description: 'Austerity festival honoring Surya and Chhathi Maiya on the banks of holy rivers, using 100% organic offerings and bamboo woven winnowing baskets.',
    category: 'Sacred Rituals',
    location_name: 'Ganga Ghats, Patna',
    district: 'Patna',
    state: 'Bihar',
    lat: 25.6120,
    lng: 85.1440,
    cover_image: '/assets/images/Culture/Devotees_offer_prayers_on_the_occasion_of_the_Chhath_Puja_festival.jpg',
    season: 'Kartik Shukla Shashthi (November)',
    community_custodians: 'Ganga Ghat Parvatis & Bamboo Guilds',
    trust_score: 99,
    significance: 'Vedic solar science and ecological reverence unchanged for over 3,000 years.'
  },
  {
    id: 'cult_07',
    title: 'Gond & Baiga Forest Storytelling with Bana Strings',
    tradition_name: 'Pardhan Bardic Oral Epics of Mahua Groves',
    description: 'Mystical musical epics played on the two-stringed Bana instrument, recounting creation myths and sacred relationships with the Narmada valley flora.',
    category: 'Folk Heritage',
    location_name: 'Maikal Hills, Dindori',
    district: 'Dindori',
    state: 'Madhya Pradesh',
    lat: 22.9520,
    lng: 81.0820,
    cover_image: '/assets/images/Culture/Folk_Artist.jpg',
    season: 'Autumn Forest Gatherings',
    community_custodians: 'Pardhan Gond Bards & Elders',
    trust_score: 98,
    significance: 'National Oral Heritage preservation and indigenous tribal mythology.'
  },
  {
    id: 'cult_08',
    title: 'Theyyam Sacred Grove Invocation & Poliyanthram',
    tradition_name: 'Living Deity Embodiment & Fire Walking',
    description: 'Ancestral temple ritual where hereditary performers don massive headdresses and red turmeric body paint to channel protective ancestral spirits.',
    category: 'Sacred Rituals',
    location_name: 'North Malabar Sacred Groves',
    district: 'Kannur',
    state: 'Kerala',
    lat: 11.8745,
    lng: 75.3704,
    cover_image: '/assets/images/Culture/Poliyanthram_podavadukkam.jpg',
    season: 'November to May (Kavu Rituals)',
    community_custodians: 'Vannar & Malayan Hereditary Custodians',
    trust_score: 99,
    significance: 'Over 1,500 years of unbroken sacred grove conservation and spiritual dance.'
  }
];
