import { Experience, Artisan, CulturalExperience } from '../types';
import { SupportedLanguage } from './translations';

export const LOCALIZED_EXPERIENCES: Record<SupportedLanguage, Experience[]> = {
  en: [
    {
      id: 'exp_kolhapur_01',
      artisan_id: 'art_kolhapur_01',
      artisan_name: 'Santosh Kamble',
      artisan_avatar: '/assets/images/Home%20page/Kolhapuri_Chappals_in_roadside_shop_in_Kolhapur3.jpeg',
      trust_score: 98,
      title: 'Heritage Kolhapuri Chappal Crafting Masterclass',
      description: 'Learn ancestral vegetable tanning using myrobalan and babool bark. Sit alongside 4th-generation master cobblers, shape traditional wooden lasts, hand-punch intricate motifs, and braid genuine leather straps.',
      category: 'Leathercraft',
      price_inr: 1850,
      duration_mins: 150,
      max_participants: 8,
      lat: 16.7050,
      lng: 74.2433,
      location_name: 'Shivaji Market, Kolhapur',
      district: 'Kolhapur',
      state: 'Maharashtra',
      cover_image: '/assets/images/Home%20page/Kolhapuri_Chappals_in_roadside_shop_in_Kolhapur3.jpeg',
      odop_tag: 'ODOP-MH-KOLHAPUR-LEATHER',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_chanderi_01',
      artisan_id: 'art_chanderi_01',
      artisan_name: 'Kamla Bai',
      artisan_avatar: '/assets/images/01-Hero/Chanderi_Craft_Village_–_Traditional_Weaving_and_Handicrafts_in_Madhya_Pradesh_01.jpg',
      trust_score: 97,
      title: 'Royal Chanderi Silk Pit-Loom Weaving & Zari Interlacing',
      description: 'Immerse yourself in 700-year-old Bundelkhand royalty. Sit in an earthen pit loom, handle pure mulberry silk and electroplated gold zari, and weave royal peacock motifs.',
      category: 'Handloom',
      price_inr: 2200,
      duration_mins: 180,
      max_participants: 6,
      lat: 24.7120,
      lng: 78.1380,
      location_name: 'Pranpur Craft Village, Chanderi',
      district: 'Ashoknagar',
      state: 'Madhya Pradesh',
      cover_image: '/assets/images/01-Hero/Chanderi_Craft_Village_–_Traditional_Weaving_and_Handicrafts_in_Madhya_Pradesh_01.jpg',
      odop_tag: 'ODOP-MP-CHANDERI-SILK',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_majuli_01',
      artisan_id: 'art_majuli_01',
      artisan_name: 'Hemanta Bora',
      artisan_avatar: '/assets/images/04-Bamboo-Cane/Innovative_Bamboo_Crafts_of_Assam.jpg',
      trust_score: 96,
      title: 'Neo-Vaishnavite Mukha Bamboo Mask Sculpting Masterclass',
      description: 'Learn the 500-year-old art of crafting mythical character masks (Mukha) using bamboo splits, organic Brahmaputra riverbed silt, and natural vegetable pigments.',
      category: 'Bamboo-Cane',
      price_inr: 1950,
      duration_mins: 180,
      max_participants: 8,
      lat: 26.9500,
      lng: 94.2167,
      location_name: 'Natun Samaguri Satra, Majuli Island',
      district: 'Majuli',
      state: 'Assam',
      cover_image: '/assets/images/04-Bamboo-Cane/Innovative_Bamboo_Crafts_of_Assam.jpg',
      odop_tag: 'ODOP-AS-MAJULI-MASKS',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_srinagar_01',
      artisan_id: 'art_srinagar_01',
      artisan_name: 'Ghulam Mohammad Zargar',
      artisan_avatar: '/assets/images/05-Wood-Pottery/Kashmiri_Woodcarving_And_Paper_maché.jpg',
      trust_score: 99,
      title: 'Master Walnut Wood Undercut Relief & Chinar Carving',
      description: 'Master delicate chisel channelling and deep 3D floral undercut carving on seasoned Kashmir walnut wood root blocks in the heart of Old Srinagar.',
      category: 'Woodwork',
      price_inr: 2500,
      duration_mins: 180,
      max_participants: 6,
      lat: 34.0837,
      lng: 74.7973,
      location_name: 'Zadibal Guild, Old Srinagar',
      district: 'Srinagar',
      state: 'Jammu and Kashmir',
      cover_image: '/assets/images/05-Wood-Pottery/Kashmiri_Woodcarving_And_Paper_maché.jpg',
      odop_tag: 'ODOP-JK-SRINAGAR-WALNUT',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_bishnupur_01',
      artisan_id: 'art_bishnupur_01',
      artisan_name: 'Subhas Kumbhakar',
      artisan_avatar: '/assets/images/05-Wood-Pottery/Artisan_decorating_ceramic_plate.jpg',
      trust_score: 96,
      title: 'Living Terracotta Temple Tile & Bankura Horse Modeling',
      description: 'Shape the iconic long-eared Bankura horse in five distinct hollow parts on a potter wheel, burnish with river stones, and fire in traditional wood kilns.',
      category: 'Pottery',
      price_inr: 1450,
      duration_mins: 150,
      max_participants: 8,
      lat: 23.0760,
      lng: 87.3190,
      location_name: 'Panchmura Village, Bankura',
      district: 'Bankura',
      state: 'West Bengal',
      cover_image: '/assets/images/05-Wood-Pottery/Artisan_decorating_ceramic_plate.jpg',
      odop_tag: 'ODOP-WB-BANKURA-HORSE',
      women_friendly: true,
      elderly_friendly: true
    }
  ],

  hi: [
    {
      id: 'exp_kolhapur_01',
      artisan_id: 'art_kolhapur_01',
      artisan_name: 'संतोष कांबले',
      artisan_avatar: '/assets/images/Home%20page/Kolhapuri_Chappals_in_roadside_shop_in_Kolhapur3.jpeg',
      trust_score: 98,
      title: 'पारंपरिक कोल्हापुरी चप्पल हस्तशिल्प मास्टरक्लास',
      description: 'बबूल की छाल और हरड़ से प्राकृतिक चमड़ा पकाना सीखें। चौथी पीढ़ी के मास्टर कारीगरों के साथ बैठकर पारंपरिक लकड़ी के सांचों पर अपने हाथों से असली कोल्हापुरी चप्पल बनाएं।',
      category: 'चमड़ा शिल्प',
      price_inr: 1850,
      duration_mins: 150,
      max_participants: 8,
      lat: 16.7050,
      lng: 74.2433,
      location_name: 'शिवाजी मार्केट, कोल्हापुर',
      district: 'कोल्हापुर',
      state: 'महाराष्ट्र',
      cover_image: '/assets/images/Home%20page/Kolhapuri_Chappals_in_roadside_shop_in_Kolhapur3.jpeg',
      odop_tag: 'ODOP-MH-कोल्हापुरी-चप्पल',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_chanderi_01',
      artisan_id: 'art_chanderi_01',
      artisan_name: 'कमला बाई',
      artisan_avatar: '/assets/images/01-Hero/Chanderi_Craft_Village_–_Traditional_Weaving_and_Handicrafts_in_Madhya_Pradesh_01.jpg',
      trust_score: 97,
      title: 'शाही चंदेरी रेशम गड्ढा-करघा बुनाई और जरी कार्यशाला',
      description: '700 साल पुरानी बुंदेलखंडी बुनाई परंपरा का अनुभव लें। पारंपरिक गड्ढा-करघे पर शुद्ध शहतूत रेशम और सोने की जरी से मोर एवं कमल की बूटी बुनना सीखें।',
      category: 'हथकरघा',
      price_inr: 2200,
      duration_mins: 180,
      max_participants: 6,
      lat: 24.7120,
      lng: 78.1380,
      location_name: 'प्राणपुर क्राफ्ट विलेज, चंदेरी',
      district: 'अशोकनगर',
      state: 'मध्य प्रदेश',
      cover_image: '/assets/images/01-Hero/Chanderi_Craft_Village_–_Traditional_Weaving_and_Handicrafts_in_Madhya_Pradesh_01.jpg',
      odop_tag: 'ODOP-MP-चंदेरी-सिल्क',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_majuli_01',
      artisan_id: 'art_majuli_01',
      artisan_name: 'हेमंत बोरा',
      artisan_avatar: '/assets/images/04-Bamboo-Cane/Innovative_Bamboo_Crafts_of_Assam.jpg',
      trust_score: 96,
      title: 'माजुली नव-वैष्णव मुखौटा और बांस शिल्प मास्टरक्लास',
      description: 'ब्रह्मपुत्र नदी की गाद मिट्टी, गाय के गोबर और बांस की खपच्चियों से 500 साल पुरानी मुखौटा निर्माण कला सीखें।',
      category: 'बांस एवं बेंत शिल्प',
      price_inr: 1950,
      duration_mins: 180,
      max_participants: 8,
      lat: 26.9500,
      lng: 94.2167,
      location_name: 'सामगुरी सत्र, माजुली द्वीप',
      district: 'माजुली',
      state: 'असम',
      cover_image: '/assets/images/04-Bamboo-Cane/Innovative_Bamboo_Crafts_of_Assam.jpg',
      odop_tag: 'ODOP-AS-माजुली-मुखौटा',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_srinagar_01',
      artisan_id: 'art_srinagar_01',
      artisan_name: 'गुलाम मोहम्मद जरगर',
      artisan_avatar: '/assets/images/05-Wood-Pottery/Kashmiri_Woodcarving_And_Paper_maché.jpg',
      trust_score: 99,
      title: 'कश्मीरी अखरोट लकड़ी 3D नक्काशी और चिनार डिज़ाइन मास्टरक्लास',
      description: 'पुराने श्रीनगर के ऐतिहासिक जादीबल में 4 साल पकी अखरोट की लकड़ी पर बारीक छेनी से चिनार के पत्तों की नक्काशी सीखें।',
      category: 'काष्ठ शिल्प',
      price_inr: 2500,
      duration_mins: 180,
      max_participants: 6,
      lat: 34.0837,
      lng: 74.7973,
      location_name: 'जादीबल, पुराना श्रीनगर',
      district: 'श्रीनगर',
      state: 'जम्मू और कश्मीर',
      cover_image: '/assets/images/05-Wood-Pottery/Kashmiri_Woodcarving_And_Paper_maché.jpg',
      odop_tag: 'ODOP-JK-अखरोट-लकड़ी',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_bishnupur_01',
      artisan_id: 'art_bishnupur_01',
      artisan_name: 'सुभाष कुंभकार',
      artisan_avatar: '/assets/images/05-Wood-Pottery/Artisan_decorating_ceramic_plate.jpg',
      trust_score: 96,
      title: 'बांकुड़ा टेराकोटा घोड़ा और मंदिर टाइल मूर्तिकला कार्यशाला',
      description: 'कुम्हार के चाक पर प्रसिद्ध बांकुड़ा घोड़े को पांच खोखले हिस्सों में ढालना और पारंपरिक लकड़ी की भट्टी में पकाना सीखें।',
      category: 'टेराकोटा मिट्टी शिल्प',
      price_inr: 1450,
      duration_mins: 150,
      max_participants: 8,
      lat: 23.0760,
      lng: 87.3190,
      location_name: 'पंचमुरा गांव, बांकुड़ा',
      district: 'बांकुड़ा',
      state: 'पश्चिम बंगाल',
      cover_image: '/assets/images/05-Wood-Pottery/Artisan_decorating_ceramic_plate.jpg',
      odop_tag: 'ODOP-WB-बांकुड़ा-घोड़ा',
      women_friendly: true,
      elderly_friendly: true
    }
  ],

  mr: [
    {
      id: 'exp_kolhapur_01',
      artisan_id: 'art_kolhapur_01',
      artisan_name: 'संतोष कांबळे',
      artisan_avatar: '/assets/images/Home%20page/Kolhapuri_Chappals_in_roadside_shop_in_Kolhapur3.jpeg',
      trust_score: 98,
      title: 'अस्सल कोल्हापुरी चप्पल हस्तकला प्रत्यक्ष कार्यशाळा',
      description: 'बाभळीची साल आणि नैसर्गिक वनस्पती पद्धतीने चामडे प्रक्रिया शिकून स्वतःच्या हाताने अस्सल कोल्हापुरी चप्पल तयार करा.',
      category: 'चामडे हस्तकला',
      price_inr: 1850,
      duration_mins: 150,
      max_participants: 8,
      lat: 16.7050,
      lng: 74.2433,
      location_name: 'शिवाजी मार्केट, कोल्हापूर',
      district: 'कोल्हापूर',
      state: 'महाराष्ट्र',
      cover_image: '/assets/images/Home%20page/Kolhapuri_Chappals_in_roadside_shop_in_Kolhapur3.jpeg',
      odop_tag: 'ODOP-MH-कोल्हापूर-चप्पल',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_chanderi_01',
      artisan_id: 'art_chanderi_01',
      artisan_name: 'कमला बाई',
      artisan_avatar: '/assets/images/01-Hero/Chanderi_Craft_Village_–_Traditional_Weaving_and_Handicrafts_in_Madhya_Pradesh_01.jpg',
      trust_score: 97,
      title: 'शाही चंदेरी रेशमी हातमाग विणकाम कार्यशाळा',
      description: 'पारंपरिक खड्डा हातमागावर बसून अस्सल चंदेरी रेशीम आणि जरी विणकामाचा थेट अनुभव घ्या.',
      category: 'हातमाग',
      price_inr: 2200,
      duration_mins: 180,
      max_participants: 6,
      lat: 24.7120,
      lng: 78.1380,
      location_name: 'प्राणपूर, चंदेरी',
      district: 'अशोकनगर',
      state: 'मध्य प्रदेश',
      cover_image: '/assets/images/01-Hero/Chanderi_Craft_Village_–_Traditional_Weaving_and_Handicrafts_in_Madhya_Pradesh_01.jpg',
      odop_tag: 'ODOP-MP-चंदेरी-रेशीम',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_majuli_01',
      artisan_id: 'art_majuli_01',
      artisan_name: 'हेमंत बोरा',
      artisan_avatar: '/assets/images/04-Bamboo-Cane/Innovative_Bamboo_Crafts_of_Assam.jpg',
      trust_score: 96,
      title: 'माजुली नव-वैष्णव बांबू मुखवटा कार्यशाळा',
      description: 'ब्रह्मपुत्रा नदीकाठच्या मातीतून आणि बांबूच्या कामट्यांमधून पारंपारिक मुखवटा बनवण्याची ५०० वर्षांची कला शिका.',
      category: 'बांबू हस्तकला',
      price_inr: 1950,
      duration_mins: 180,
      max_participants: 8,
      lat: 26.9500,
      lng: 94.2167,
      location_name: 'सामगुरी सत्र, माजुली बेट',
      district: 'माजुली',
      state: 'आसाम',
      cover_image: '/assets/images/04-Bamboo-Cane/Innovative_Bamboo_Crafts_of_Assam.jpg',
      odop_tag: 'ODOP-AS-माजुली-मुखवटे',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_srinagar_01',
      artisan_id: 'art_srinagar_01',
      artisan_name: 'गुलाम मोहम्मद झरगर',
      artisan_avatar: '/assets/images/05-Wood-Pottery/Kashmiri_Woodcarving_And_Paper_maché.jpg',
      trust_score: 99,
      title: 'काश्मिरी अक्रोड लाकूड कोरीव काम कार्यशाळा',
      description: 'श्रीनगरच्या जुन्या शहरात अक्रोडाच्या लाकडावर चिनार पानांचे त्रिमितीय कोरीव काम शिका.',
      category: 'लाकूड कोरीव काम',
      price_inr: 2500,
      duration_mins: 180,
      max_participants: 6,
      lat: 34.0837,
      lng: 74.7973,
      location_name: 'जादीबल, श्रीनगर',
      district: 'श्रीनगर',
      state: 'जम्मू आणि काश्मीर',
      cover_image: '/assets/images/05-Wood-Pottery/Kashmiri_Woodcarving_And_Paper_maché.jpg',
      odop_tag: 'ODOP-JK-अक्रोड-लाकूड',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_bishnupur_01',
      artisan_id: 'art_bishnupur_01',
      artisan_name: 'सुभाष कुंभार',
      artisan_avatar: '/assets/images/05-Wood-Pottery/Artisan_decorating_ceramic_plate.jpg',
      trust_score: 96,
      title: 'बांकुडा टेराकोटा मातीकाम आणि मंदिर शिल्प कार्यशाळा',
      description: 'चाकावर प्रसिद्ध बांकुडा घोडा घडवून लाकडाच्या भट्टीत भाजण्याचे पारंपरिक तंत्र शिका.',
      category: 'टेराकोटा मातीकाम',
      price_inr: 1450,
      duration_mins: 150,
      max_participants: 8,
      lat: 23.0760,
      lng: 87.3190,
      location_name: 'पंचमुरा, बांकुडा',
      district: 'बांकुडा',
      state: 'पश्चिम बंगाल',
      cover_image: '/assets/images/05-Wood-Pottery/Artisan_decorating_ceramic_plate.jpg',
      odop_tag: 'ODOP-WB-बांकुडा-घोडा',
      women_friendly: true,
      elderly_friendly: true
    }
  ],

  ta: [
    {
      id: 'exp_kolhapur_01',
      artisan_id: 'art_kolhapur_01',
      artisan_name: 'சந்தோஷ் காம்ப்ளே',
      artisan_avatar: '/assets/images/Home%20page/Kolhapuri_Chappals_in_roadside_shop_in_Kolhapur3.jpeg',
      trust_score: 98,
      title: 'பாரம்பரிய கோலாப்பூரி செருப்பு கைவினைப் பயிற்சி',
      description: 'பாரம்பரிய முறையில் தோல் பதனிடுதல் மற்றும் கைவினை செருப்பு தயாரிக்கும் பயிற்சி.',
      category: 'தோல் கைவினை',
      price_inr: 1850,
      duration_mins: 150,
      max_participants: 8,
      lat: 16.7050,
      lng: 74.2433,
      location_name: 'சிவாஜி மார்க்கெட், கோலாப்பூர்',
      district: 'கோலாப்பூர்',
      state: 'மகாராஷ்டிரா',
      cover_image: '/assets/images/Home%20page/Kolhapuri_Chappals_in_roadside_shop_in_Kolhapur3.jpeg',
      odop_tag: 'ODOP-MH-LEATHER',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_chanderi_01',
      artisan_id: 'art_chanderi_01',
      artisan_name: 'கமலா பாய்',
      artisan_avatar: '/assets/images/01-Hero/Chanderi_Craft_Village_–_Traditional_Weaving_and_Handicrafts_in_Madhya_Pradesh_01.jpg',
      trust_score: 97,
      title: 'ராஜகம்பீர சந்தேரி பட்டு நெசவுப் பயிற்சி',
      description: 'தூய மல்பெரி பட்டு மற்றும் தங்க ஜரிகை கொண்டு நெசவு செய்யும் நேரடி பயிற்சி.',
      category: 'கைத்தறி',
      price_inr: 2200,
      duration_mins: 180,
      max_participants: 6,
      lat: 24.7120,
      lng: 78.1380,
      location_name: 'பிரான்பூர், சந்தேரி',
      district: 'அசோக்நகர்',
      state: 'மத்தியப் பிரதேசம்',
      cover_image: '/assets/images/01-Hero/Chanderi_Craft_Village_–_Traditional_Weaving_and_Handicrafts_in_Madhya_Pradesh_01.jpg',
      odop_tag: 'ODOP-MP-SILK',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_majuli_01',
      artisan_id: 'art_majuli_01',
      artisan_name: 'ஹேமந்த போரா',
      artisan_avatar: '/assets/images/04-Bamboo-Cane/Innovative_Bamboo_Crafts_of_Assam.jpg',
      trust_score: 96,
      title: 'மஜூலி மூங்கில் முகமூடி கைவினைப் பயிற்சி',
      description: 'பிரம்மபுத்திரா களிமண் மற்றும் மூங்கில் கொண்டு பாரம்பரிய முகமூடி தயாரித்தல்.',
      category: 'மூங்கில் கைவினை',
      price_inr: 1950,
      duration_mins: 180,
      max_participants: 8,
      lat: 26.9500,
      lng: 94.2167,
      location_name: 'மஜூலி தீவு',
      district: 'மஜூலி',
      state: 'அசாம்',
      cover_image: '/assets/images/04-Bamboo-Cane/Innovative_Bamboo_Crafts_of_Assam.jpg',
      odop_tag: 'ODOP-AS-MASKS',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_srinagar_01',
      artisan_id: 'art_srinagar_01',
      artisan_name: 'குலாம் முகமது ஜர்கர்',
      artisan_avatar: '/assets/images/05-Wood-Pottery/Kashmiri_Woodcarving_And_Paper_maché.jpg',
      trust_score: 99,
      title: 'காஷ்மீர் வாதுமை மரச் செதுக்கல் பயிற்சி',
      description: 'பழைய ஸ்ரீநகரில் பாரம்பரிய வாதுமை மரத்தில் பூ வேலைப்பாடுகள் செதுக்கும் கலை.',
      category: 'மரச் செதுக்கல்',
      price_inr: 2500,
      duration_mins: 180,
      max_participants: 6,
      lat: 34.0837,
      lng: 74.7973,
      location_name: 'ஸ்ரீநகர்',
      district: 'ஸ்ரீநகர்',
      state: 'ஜம்மு & காஷ்மீர்',
      cover_image: '/assets/images/05-Wood-Pottery/Kashmiri_Woodcarving_And_Paper_maché.jpg',
      odop_tag: 'ODOP-JK-WALNUT',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_bishnupur_01',
      artisan_id: 'art_bishnupur_01',
      artisan_name: 'சுபாஷ் கும்பகார்',
      artisan_avatar: '/assets/images/05-Wood-Pottery/Artisan_decorating_ceramic_plate.jpg',
      trust_score: 96,
      title: 'பாங்குரா சுடுமண் குதிரை சிற்பக் கலைப் பயிற்சி',
      description: 'பாரம்பரிய சுடுமண் குதிரை மற்றும் கோவில் சிற்பங்கள் செய்யும் கலை.',
      category: 'சுடுமண் கைவினை',
      price_inr: 1450,
      duration_mins: 150,
      max_participants: 8,
      lat: 23.0760,
      lng: 87.3190,
      location_name: 'பாங்குரா',
      district: 'பாங்குரா',
      state: 'மேற்கு வங்கம்',
      cover_image: '/assets/images/05-Wood-Pottery/Artisan_decorating_ceramic_plate.jpg',
      odop_tag: 'ODOP-WB-HORSE',
      women_friendly: true,
      elderly_friendly: true
    }
  ],

  te: [
    {
      id: 'exp_kolhapur_01',
      artisan_id: 'art_kolhapur_01',
      artisan_name: 'సంతోష్ కాంబ్లే',
      artisan_avatar: '/assets/images/Home%20page/Kolhapuri_Chappals_in_roadside_shop_in_Kolhapur3.jpeg',
      trust_score: 98,
      title: 'కొల్హాపూర్ సాంప్రదాయ తోలు చెప్పుల వర్క్‌షాప్',
      description: 'సహజసిద్ధంగా తోలును సిద్ధం చేసి సంప్రదాయ చెప్పులు తయారు చేసే కళను నేర్చుకోండి.',
      category: 'తోలు కళ',
      price_inr: 1850,
      duration_mins: 150,
      max_participants: 8,
      lat: 16.7050,
      lng: 74.2433,
      location_name: 'కొల్హాపూర్',
      district: 'కొల్హాపూర్',
      state: 'మహారాష్ట్ర',
      cover_image: '/assets/images/Home%20page/Kolhapuri_Chappals_in_roadside_shop_in_Kolhapur3.jpeg',
      odop_tag: 'ODOP-MH-LEATHER',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_chanderi_01',
      artisan_id: 'art_chanderi_01',
      artisan_name: 'కమలా బాయి',
      artisan_avatar: '/assets/images/01-Hero/Chanderi_Craft_Village_–_Traditional_Weaving_and_Handicrafts_in_Madhya_Pradesh_01.jpg',
      trust_score: 97,
      title: 'చందేరి పట్టు చేనేత & జరీ నేత కళాశాల',
      description: 'స్వచ్ఛమైన మల్బరీ పట్టు మరియు బంగారు జరీతో మగ్గంపై నేత నేర్చుకోండి.',
      category: 'చేనేత',
      price_inr: 2200,
      duration_mins: 180,
      max_participants: 6,
      lat: 24.7120,
      lng: 78.1380,
      location_name: 'చందేరి',
      district: 'అశోక్‌నగర్',
      state: 'మధ్యప్రదేశ్',
      cover_image: '/assets/images/01-Hero/Chanderi_Craft_Village_–_Traditional_Weaving_and_Handicrafts_in_Madhya_Pradesh_01.jpg',
      odop_tag: 'ODOP-MP-SILK',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_majuli_01',
      artisan_id: 'art_majuli_01',
      artisan_name: 'హేమంత బోరా',
      artisan_avatar: '/assets/images/04-Bamboo-Cane/Innovative_Bamboo_Crafts_of_Assam.jpg',
      trust_score: 96,
      title: 'మజులి వెదురు ముసుగుల సంప్రదాయ వర్క్‌షాప్',
      description: 'బ్రహ్మపుత్ర నది మట్టి మరియు వెదురుతో 500 ఏళ్ల పురాతన ముసుగుల తయారీ.',
      category: 'వెదురు కళ',
      price_inr: 1950,
      duration_mins: 180,
      max_participants: 8,
      lat: 26.9500,
      lng: 94.2167,
      location_name: 'మజులి ద్వీపం',
      district: 'మజులి',
      state: 'అస్సాం',
      cover_image: '/assets/images/04-Bamboo-Cane/Innovative_Bamboo_Crafts_of_Assam.jpg',
      odop_tag: 'ODOP-AS-MASKS',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_srinagar_01',
      artisan_id: 'art_srinagar_01',
      artisan_name: 'గులాం మొహమ్మద్ జర్గర్',
      artisan_avatar: '/assets/images/05-Wood-Pottery/Kashmiri_Woodcarving_And_Paper_maché.jpg',
      trust_score: 99,
      title: 'కాశ్మీర్ అక్రోట్ చెక్క చెక్కడాల వర్క్‌షాప్',
      description: 'పురాతన శ్రీనగర్‌లో అక్రోట్ చెక్కపై సున్నితమైన చిక్కటి చెక్కడాల శిక్షణ.',
      category: 'చెక్క కళ',
      price_inr: 2500,
      duration_mins: 180,
      max_participants: 6,
      lat: 34.0837,
      lng: 74.7973,
      location_name: 'శ్రీనగర్',
      district: 'శ్రీనగర్',
      state: 'జమ్మూ & కాశ్మీర్',
      cover_image: '/assets/images/05-Wood-Pottery/Kashmiri_Woodcarving_And_Paper_maché.jpg',
      odop_tag: 'ODOP-JK-WALNUT',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_bishnupur_01',
      artisan_id: 'art_bishnupur_01',
      artisan_name: 'సుభాష్ కుంభకార్',
      artisan_avatar: '/assets/images/05-Wood-Pottery/Artisan_decorating_ceramic_plate.jpg',
      trust_score: 96,
      title: 'బాంకురా టెర్రకోటా గుర్రం & మట్టి కుండల వర్క్‌షాప్',
      description: 'కుమ్మరి చక్రంపై ప్రసిద్ధ బాంకురా గుర్రం తయారు చేయడం నేర్చుకోండి.',
      category: 'మట్టి కళ',
      price_inr: 1450,
      duration_mins: 150,
      max_participants: 8,
      lat: 23.0760,
      lng: 87.3190,
      location_name: 'బాంకురా',
      district: 'బాంకురా',
      state: 'పశ్చిమ బెంగాల్',
      cover_image: '/assets/images/05-Wood-Pottery/Artisan_decorating_ceramic_plate.jpg',
      odop_tag: 'ODOP-WB-HORSE',
      women_friendly: true,
      elderly_friendly: true
    }
  ],

  bn: [
    {
      id: 'exp_kolhapur_01',
      artisan_id: 'art_kolhapur_01',
      artisan_name: 'সন্তোষ কাম্বলে',
      artisan_avatar: '/assets/images/Home%20page/Kolhapuri_Chappals_in_roadside_shop_in_Kolhapur3.jpeg',
      trust_score: 98,
      title: 'ঐতিহ্যবাহী কোলহাপুরী চটি চামড়া শিল্প কর্মশালা',
      description: 'বাবলা গাছের ছাল দিয়ে প্রাকৃতিক চামড়া প্রক্রিয়াকরণ ও হাতে তৈরি কোলহাপুরী চটি বানানোর প্রশিক্ষণ।',
      category: 'চামড়া শিল্প',
      price_inr: 1850,
      duration_mins: 150,
      max_participants: 8,
      lat: 16.7050,
      lng: 74.2433,
      location_name: 'কোলহাপুর',
      district: 'কোলহাপুর',
      state: 'মহারাষ্ট্র',
      cover_image: '/assets/images/Home%20page/Kolhapuri_Chappals_in_roadside_shop_in_Kolhapur3.jpeg',
      odop_tag: 'ODOP-MH-LEATHER',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_chanderi_01',
      artisan_id: 'art_chanderi_01',
      artisan_name: 'কমলা বাঈ',
      artisan_avatar: '/assets/images/01-Hero/Chanderi_Craft_Village_–_Traditional_Weaving_and_Handicrafts_in_Madhya_Pradesh_01.jpg',
      trust_score: 97,
      title: 'রাজকীয় চান্দেরি রেশম তাঁত ও জরি বয়ন কর্মশালা',
      description: 'ঐতিহ্যবাহী তাঁতে বসে খাঁটি রেশম ও সোনার জরি দিয়ে চান্দেরি শাড়ি বয়ন শিখুন।',
      category: 'তাঁত শিল্প',
      price_inr: 2200,
      duration_mins: 180,
      max_participants: 6,
      lat: 24.7120,
      lng: 78.1380,
      location_name: 'চান্দেরি',
      district: 'অশোকনগর',
      state: 'মধ্যপ্রদেশ',
      cover_image: '/assets/images/01-Hero/Chanderi_Craft_Village_–_Traditional_Weaving_and_Handicrafts_in_Madhya_Pradesh_01.jpg',
      odop_tag: 'ODOP-MP-SILK',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_majuli_01',
      artisan_id: 'art_majuli_01',
      artisan_name: 'হেমন্ত বরা',
      artisan_avatar: '/assets/images/04-Bamboo-Cane/Innovative_Bamboo_Crafts_of_Assam.jpg',
      trust_score: 96,
      title: 'মাজুলী বাঁশের মুখোশ ও বেত শিল্প কর্মশালা',
      description: 'ব্রহ্মপুত্র নদের পলিমাটি ও বাঁশ দিয়ে ৫০০ বছরের পুরনো ঐতিহ্যবাহী মুখোশ তৈরি।',
      category: 'বাঁশ ও বেত শিল্প',
      price_inr: 1950,
      duration_mins: 180,
      max_participants: 8,
      lat: 26.9500,
      lng: 94.2167,
      location_name: 'মাজুলী দ্বীপ',
      district: 'মাজুলী',
      state: 'আসাম',
      cover_image: '/assets/images/04-Bamboo-Cane/Innovative_Bamboo_Crafts_of_Assam.jpg',
      odop_tag: 'ODOP-AS-MASKS',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_srinagar_01',
      artisan_id: 'art_srinagar_01',
      artisan_name: 'গুলাম মোহাম্মদ জরগর',
      artisan_avatar: '/assets/images/05-Wood-Pottery/Kashmiri_Woodcarving_And_Paper_maché.jpg',
      trust_score: 99,
      title: 'কাশ্মীরি আখরোট কাঠের খোদাই ও চিনার নকশা কর্মশালা',
      description: 'পুরানো শ্রীনগরে আখরোট কাঠের উপর সূক্ষ্ম চিনার পাতার খোদাইয়ের সরাসরি প্রশিক্ষণ।',
      category: 'কাঠের খোদাই',
      price_inr: 2500,
      duration_mins: 180,
      max_participants: 6,
      lat: 34.0837,
      lng: 74.7973,
      location_name: 'শ্রীনগর',
      district: 'শ্রীনগর',
      state: 'জম্মু ও কাশ্মীর',
      cover_image: '/assets/images/05-Wood-Pottery/Kashmiri_Woodcarving_And_Paper_maché.jpg',
      odop_tag: 'ODOP-JK-WALNUT',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_bishnupur_01',
      artisan_id: 'art_bishnupur_01',
      artisan_name: 'সুভাষ কুম্ভকার',
      artisan_avatar: '/assets/images/05-Wood-Pottery/Artisan_decorating_ceramic_plate.jpg',
      trust_score: 96,
      title: 'বিষ্ণুপুর বাঁকুড়া পোড়ামাটির ঘোড়া ও মন্দির টেরাকোটা কর্মশালা',
      description: 'কুমোরের চাকে বিশ্বখ্যাত বাঁকুড়ার টেরাকোটা ঘোড়া তৈরি ও কাঠের চুল্লিতে পোড়ানোর পদ্ধতি শিখুন।',
      category: 'পোড়ামাটি শিল্প',
      price_inr: 1450,
      duration_mins: 150,
      max_participants: 8,
      lat: 23.0760,
      lng: 87.3190,
      location_name: 'পাঁচমুড়া, বাঁকুড়া',
      district: 'বাঁকুড়া',
      state: 'পশ্চিমবঙ্গ',
      cover_image: '/assets/images/05-Wood-Pottery/Artisan_decorating_ceramic_plate.jpg',
      odop_tag: 'ODOP-WB-HORSE',
      women_friendly: true,
      elderly_friendly: true
    }
  ]
};

export interface LocalizedSlideItem {
  id: number;
  type: 'image' | 'video';
  src: string;
  craftName: string;
  tagline: string;
  location: string;
  badge: string;
}

export const LOCALIZED_HERO_SLIDES: Record<SupportedLanguage, LocalizedSlideItem[]> = {
  "en": [
    {
      "id": 0,
      "type": "image",
      "src": "/assets/images/Home page/Kolhapuri_Chappals_in_roadside_shop_in_Kolhapur3.jpeg",
      "craftName": "Ancestral Kolhapuri Leathercraft",
      "tagline": "Hand-stitched vegetable-tanned Kolhapuri Chappals from 4th-generation master cobblers.",
      "location": "Kolhapur, Maharashtra",
      "badge": "GI Tagged • 100% Herbal Tanned"
    },
    {
      "id": 1,
      "type": "video",
      "src": "/assets/images/Home page/local artist.mp4",
      "craftName": "Master Artisan at Work",
      "tagline": "Watch hereditary artisans hand-paint intricate heritage motifs and live brushstrokes.",
      "location": "Living Atelier, India",
      "badge": "Master Artisan Video"
    },
    {
      "id": 2,
      "type": "image",
      "src": "/assets/images/Home page/Making_of_bamboo_and_palm_leaf_handicarft_products.jpg",
      "craftName": "Bamboo & Palm Leaf Crafts",
      "tagline": "Indigenous artisans hand-weave intricate bamboo and palm-leaf eco-friendly handicraft products.",
      "location": "Majuli Island, Assam",
      "badge": "UNESCO Heritage Contender"
    },
    {
      "id": 3,
      "type": "video",
      "src": "/assets/images/Home page/Handmade craft stall.mp4",
      "craftName": "Living Craft Ateliers",
      "tagline": "Experience the vibrant energy of authentic heritage stalls and master artisans at work.",
      "location": "Bhavani Mandap Guilds, Maharashtra",
      "badge": "Living Heritage Video"
    },
    {
      "id": 4,
      "type": "image",
      "src": "/assets/images/Home page/Bharud.jpg",
      "craftName": "Bharud — Sacred Folk Tradition",
      "tagline": "A vibrant traditional folk art form of Maharashtra blending music, theatrical expression and spiritual awakening.",
      "location": "Rural Maharashtra",
      "badge": "Living Intangible Heritage"
    },
    {
      "id": 5,
      "type": "video",
      "src": "/assets/images/Home page/Craft shop.mp4",
      "craftName": "Heritage Craft Ateliers & Bazaar",
      "tagline": "Step inside time-honored craft shops where handmade artifacts preserve generations of cultural identity.",
      "location": "Jaipur & Western India",
      "badge": "Artisan Heritage Video"
    },
    {
      "id": 6,
      "type": "video",
      "src": "/assets/images/Home page/Bamboo_basket_making.ogv",
      "craftName": "Ancestral Bamboo Basket Weaving",
      "tagline": "Watch the hypnotic slicing of green bamboo culms and dexterous hand-interlacing of storage baskets.",
      "location": "Western Ghats & Majuli",
      "badge": "Bamboo Heritage Video"
    },
    {
      "id": 7,
      "type": "video",
      "src": "/assets/images/Home page/old leddy crafting.mp4",
      "craftName": "Grandmother Weavers & Spinners",
      "tagline": "Elders of the craft community passing down irreplaceable muscle memory and centuries of spinning wisdom.",
      "location": "Pranpur & Rural Clusters",
      "badge": "Living Legend Video"
    },
    {
      "id": 8,
      "type": "video",
      "src": "/assets/images/Home page/17_Tribes,_One_heartbeat_-_Hornbill_Festival.webm",
      "craftName": "Hornbill Indigenous Cultural Festival",
      "tagline": "17 indigenous tribes celebrating unity through traditional war log drums, folk attire, and sacred dances.",
      "location": "Kisama, Nagaland",
      "badge": "Northeast Cultural Video"
    },
    {
      "id": 9,
      "type": "video",
      "src": "/assets/images/Home page/A_aesthetic_Fire_Pot_Dance.ogv",
      "craftName": "Sacred Fire Pot Devotional Dance",
      "tagline": "Spiritual temple rituals featuring fearless balance, live flame pots, and ancient rhythmic devotion.",
      "location": "South India & Maharashtra",
      "badge": "Sacred Ritual Video"
    },
    {
      "id": 10,
      "type": "video",
      "src": "/assets/images/Home page/Kakada_Bhajan_(3).webm",
      "craftName": "Kakada Bhajan & Warkari Heritage",
      "tagline": "Early dawn temple chants, cymbals, and devotional singing preserved across centuries of bhakti tradition.",
      "location": "Pandharpur, Maharashtra",
      "badge": "Spiritual Heritage Video"
    },
    {
      "id": 11,
      "type": "video",
      "src": "/assets/images/Home page/12245591_3840_2160_30fps.mp4",
      "craftName": "Imperial Handloom Silk & Zari Weaving",
      "tagline": "Micro-level handcrafting of royal silk textiles on ancestral wooden looms with pure metallic zari thread.",
      "location": "Chanderi & Varanasi",
      "badge": "GI Royal Handloom Video"
    },
    {
      "id": 12,
      "type": "video",
      "src": "/assets/images/Home page/148230-793717994.mp4",
      "craftName": "Heritage Wheel Pottery & Terracotta",
      "tagline": "Shaping raw earthen clay on the spinning wheel into sacred vessels and timeless decorative artifacts.",
      "location": "Bishnupur & Kutch",
      "badge": "Master Pottery Video"
    },
    {
      "id": 13,
      "type": "video",
      "src": "/assets/images/Home page/15346256-hd_1920_1080_30fps.mp4",
      "craftName": "Ancestral Metalcraft & Bell Metal Chiseling",
      "tagline": "Master metalsmiths engraving classical folklore and intricate iconography on bronze and copper alloys.",
      "location": "Moradabad & Bastar",
      "badge": "GI Metal Guild Video"
    }
  ],
  "hi": [
    {
      "id": 0,
      "type": "image",
      "src": "/assets/images/Home page/Kolhapuri_Chappals_in_roadside_shop_in_Kolhapur3.jpeg",
      "craftName": "पारंपरिक कोल्हापुरी चर्मशिल्प",
      "tagline": "चौथी पीढ़ी के सिद्ध हस्तशिल्पियों द्वारा बबूल की छाल और हरड़ से तैयार प्राकृतिक कोल्हापुरी चप्पलें।",
      "location": "कोल्हापुर, महाराष्ट्र",
      "badge": "जीआई टैग प्रमाणित"
    },
    {
      "id": 1,
      "type": "video",
      "src": "/assets/images/Home page/local artist.mp4",
      "craftName": "सजीव कार्यशाला में उस्ताद कारीगर",
      "tagline": "पारंपरिक सिद्धहस्त शिल्पकारों को लाइव बारीक धरोहर आकृतियां बनाते देखें।",
      "location": "जीवंत कार्यशाला, भारत",
      "badge": "उस्ताद कारीगर वीडियो"
    },
    {
      "id": 2,
      "type": "image",
      "src": "/assets/images/Home page/Making_of_bamboo_and_palm_leaf_handicarft_products.jpg",
      "craftName": "बांस व ताड़पत्र हस्तशिल्प",
      "tagline": "स्थानीय कारीगर हाथ से बांस और ताड़पत्र से पर्यावरण-अनुकूल बेशकीमती हस्तशिल्प बनाते हैं।",
      "location": "माजुली द्वीप, असम",
      "badge": "यूनेस्को धरोहर दावेदार"
    },
    {
      "id": 3,
      "type": "video",
      "src": "/assets/images/Home page/Handmade craft stall.mp4",
      "craftName": "जीवंत शिल्प हाट व कारीगर",
      "tagline": "पारंपरिक कारीगरों के प्रामाणिक शिल्प स्टॉल और कार्यशालाओं की जीवंत ऊर्जा का अनुभव करें।",
      "location": "भवानी मंडप, महाराष्ट्र",
      "badge": "सजीव धरोहर वीडियो"
    },
    {
      "id": 4,
      "type": "image",
      "src": "/assets/images/Home page/Bharud.jpg",
      "craftName": "भारुड — महाराष्ट्र की पवित्र लोक परंपरा",
      "tagline": "महाराष्ट्र की जीवंत लोक कला जिसमें संगीत, नाट्य और आध्यात्मिक जागृति का अनूठा संगम है।",
      "location": "ग्रामीण महाराष्ट्र",
      "badge": "जीवंत अमूर्त विरासत"
    },
    {
      "id": 5,
      "type": "video",
      "src": "/assets/images/Home page/Craft shop.mp4",
      "craftName": "विरासत शिल्प बाजार और दुकानें",
      "tagline": "समय के पार बसी प्रामाणिक शिल्प दुकानों में हस्तनिर्मित कलाकृतियों की समृद्ध परंपरा देखें।",
      "location": "जयपुर व पश्चिमी भारत",
      "badge": "शिल्प धरोहर वीडियो"
    },
    {
      "id": 6,
      "type": "video",
      "src": "/assets/images/Home page/Bamboo_basket_making.ogv",
      "craftName": "पारंपरिक बांस टोकरी निर्माण",
      "tagline": "हरे बांस की पत्तियों को तराशकर हाथ से मजबूत और सुंदर टोकरी बुनने का जीवंत प्रदर्शन।",
      "location": "पश्चिमी घाट व माजुली",
      "badge": "बांस शिल्प वीडियो"
    },
    {
      "id": 7,
      "type": "video",
      "src": "/assets/images/Home page/old leddy crafting.mp4",
      "craftName": "बुजुर्ग शिल्पकारों की परंपरा",
      "tagline": "पीढ़ियों के अनुभव और चरखे के कौशल को नई पीढ़ी तक पहुंचाती वृद्ध उस्ताद बुनकर।",
      "location": "प्राणपुर व ग्रामीण भारत",
      "badge": "जीवंत किंवदंती वीडियो"
    },
    {
      "id": 8,
      "type": "video",
      "src": "/assets/images/Home page/17_Tribes,_One_heartbeat_-_Hornbill_Festival.webm",
      "craftName": "हॉर्नबिल उत्सव — नागालैंड की जनजातीय संस्कृति",
      "tagline": "17 जनजातियों का पवित्र संगम, पारंपरिक ढोल की थाप और रंगारंग लोक नृत्यों का अद्वितीय दृश्य।",
      "location": "किसामा, नागालैंड",
      "badge": "पूर्वोत्तर धरोहर वीडियो"
    },
    {
      "id": 9,
      "type": "video",
      "src": "/assets/images/Home page/A_aesthetic_Fire_Pot_Dance.ogv",
      "craftName": "अग्नि घट नृत्य — पवित्र मंदिर अनुष्ठान",
      "tagline": "सिर पर प्रज्वलित अग्नि घट रखकर किया जाने वाला प्राचीन भक्ति और शक्ति का विस्मयकारी नृत्य।",
      "location": "दक्षिण भारत व महाराष्ट्र",
      "badge": "पवित्र अनुष्ठान वीडियो"
    },
    {
      "id": 10,
      "type": "video",
      "src": "/assets/images/Home page/Kakada_Bhajan_(3).webm",
      "craftName": "काकड़ आरती व वारकरी भजन",
      "tagline": "भोर के समय मंजीरे और पखावज की धुन पर गाया जाने वाला सदियों पुराना भक्ति रस का अमृत।",
      "location": "पंढरपुर, महाराष्ट्र",
      "badge": "आध्यात्मिक धरोहर वीडियो"
    },
    {
      "id": 11,
      "type": "video",
      "src": "/assets/images/Home page/12245591_3840_2160_30fps.mp4",
      "craftName": "शाही हथकरघा सिल्क व जरी बुनाई",
      "tagline": "लकड़ी के प्राचीन करघों पर शुद्ध जरी के तारों से बुने जाने वाले उत्कृष्ट रेशमी वस्त्र।",
      "location": "चंदेरी व वाराणसी",
      "badge": "शाही हथकरघा वीडियो"
    },
    {
      "id": 12,
      "type": "video",
      "src": "/assets/images/Home page/148230-793717994.mp4",
      "craftName": "कुम्हार का चाक — मिट्टी व टेराकोटा कला",
      "tagline": "घूमते चाक पर गीली मिट्टी को दिव्य आकार देकर पारंपरिक बर्तन व कलाकृतियां गढ़ना।",
      "location": "विष्णुपुर व कच्छ",
      "badge": "मिट्टी कला वीडियो"
    },
    {
      "id": 13,
      "type": "video",
      "src": "/assets/images/Home page/15346256-hd_1920_1080_30fps.mp4",
      "craftName": "कांस्य व पीतल धातु शिल्प",
      "tagline": "तांबे और कांस्य की धातुओं पर हथौड़ी और छेनी से बारीक पौराणिक नक्काशी उकेरते उस्ताद धातुशिल्पी।",
      "location": "मुरादाबाद व बस्तर",
      "badge": "धातु शिल्प वीडियो"
    }
  ],
  "mr": [
    {
      "id": 0,
      "type": "image",
      "src": "/assets/images/Home page/Kolhapuri_Chappals_in_roadside_shop_in_Kolhapur3.jpeg",
      "craftName": "अभिजात कोल्हापुरी चर्मकला",
      "tagline": "चौथ्या पिढीतील कसबी कारागिरांनी बाभळीच्या सालीच्या नैसर्गिक टॅनिंगने हाताने शिवलेली चप्पल.",
      "location": "कोल्हापूर, महाराष्ट्र",
      "badge": "जीआई मानांकन"
    },
    {
      "id": 1,
      "type": "video",
      "src": "/assets/images/Home page/local artist.mp4",
      "craftName": "कार्यरत ज्येष्ठ हस्तकलाकार",
      "tagline": "पारंपरिक कारागिरांना जिवंत कलेचे नक्षीकाम आणि कुंचल्याचे फटकारे मारताना प्रत्यक्ष पहा.",
      "location": "प्रत्यक्ष कार्यशाळा, भारत",
      "badge": "मास्टर आर्टिसन व्हिडिओ"
    },
    {
      "id": 2,
      "type": "image",
      "src": "/assets/images/Home page/Making_of_bamboo_and_palm_leaf_handicarft_products.jpg",
      "craftName": "बांबू व ताडपत्र हस्तकला",
      "tagline": "स्थानिक कारागीर हाताने बांबू व ताडपत्राच्या पर्यावरणपूरक अमूल्य हस्तकलावस्तू घडवतात.",
      "location": "माजुली बेट, आसाम",
      "badge": "युनेस्को वारसा दावेदार"
    },
    {
      "id": 3,
      "type": "video",
      "src": "/assets/images/Home page/Handmade craft stall.mp4",
      "craftName": "पारंपरिक कारागीर स्टॉल्स",
      "tagline": "भवानी मंडपातील कारागिरांचा थेट उत्साह आणि अस्सल हस्तकलेची ऊर्जा अनुभवा.",
      "location": "भवानी मंडप, कोल्हापूर",
      "badge": "वारसा व्हिडिओ"
    },
    {
      "id": 4,
      "type": "image",
      "src": "/assets/images/Home page/Bharud.jpg",
      "craftName": "भारुड — महाराष्ट्राची लोककला",
      "tagline": "महाराष्ट्राची ही जिवंत लोककला संगीत, नाट्य आणि समाज प्रबोधनाचा एक अनोखा आविष्कार आहे.",
      "location": "ग्रामीण महाराष्ट्र",
      "badge": "जिवंत अमूर्त वारसा"
    },
    {
      "id": 5,
      "type": "video",
      "src": "/assets/images/Home page/Craft shop.mp4",
      "craftName": "वारसा हस्तकला दालन",
      "tagline": "पिढ्यानपिढ्या चालत आलेल्या हस्तकलेच्या दालनात अस्सल भारतीय संस्कृतीची ओळख अनुभवा.",
      "location": "जयपूर आणि पश्चिम भारत",
      "badge": "वारसा दालन व्हिडिओ"
    },
    {
      "id": 6,
      "type": "video",
      "src": "/assets/images/Home page/Bamboo_basket_making.ogv",
      "craftName": "पारंपरिक बांबू विणकाम कला",
      "tagline": "बांबूच्या काड्या कुशलतेने कापून हाताने सुबक टोपल्या विणण्याची पारंपरिक पद्धत प्रत्यक्ष पहा.",
      "location": "पश्चिम घाट आणि माजुली",
      "badge": "बांबू कला व्हिडिओ"
    },
    {
      "id": 7,
      "type": "video",
      "src": "/assets/images/Home page/old leddy crafting.mp4",
      "craftName": "ज्येष्ठ कारागिरांचा वारसा",
      "tagline": "वर्षानुवर्षे चरख्यावर सूत कातणाऱ्या आजीबाईंच्या हातातील जादुई कौशल्य प्रत्यक्ष पहा.",
      "location": "प्राणपूर आणि ग्रामीण भाग",
      "badge": "जिवंत वारसा व्हिडिओ"
    },
    {
      "id": 8,
      "type": "video",
      "src": "/assets/images/Home page/17_Tribes,_One_heartbeat_-_Hornbill_Festival.webm",
      "craftName": "हॉर्नबिल महोत्सव — नागालँडची संस्कृती",
      "tagline": "१७ आदिवासी जमातींचे एकत्र येणे, पारंपरिक वाद्ये आणि लोकनृत्याचा अद्वितीय संगम.",
      "location": "किसामा, नागालँड",
      "badge": "ईशान्य वारसा व्हिडिओ"
    },
    {
      "id": 9,
      "type": "video",
      "src": "/assets/images/Home page/A_aesthetic_Fire_Pot_Dance.ogv",
      "craftName": "अग्नि घट नृत्य — मंदिरातील धार्मिक विधी",
      "tagline": "डोक्यावर धगधगता अग्निघट घेऊन भक्तीभावाने सादर होणारे थरारक आणि पवित्र लोकनृत्य.",
      "location": "महाराष्ट्र व दक्षिण भारत",
      "badge": "धार्मिक विधी व्हिडिओ"
    },
    {
      "id": 10,
      "type": "video",
      "src": "/assets/images/Home page/Kakada_Bhajan_(3).webm",
      "craftName": "काकड आरती आणि वारकरी भजन",
      "tagline": "पहाटेच्या मंगल समयी टाळ-मृदुंगाच्या गजरात गुंजणारा वारकरी संप्रदायाचा अमूल्य भक्ती वारसा.",
      "location": "पंढरपूर, महाराष्ट्र",
      "badge": "अमूर्त वारसा व्हिडिओ"
    },
    {
      "id": 11,
      "type": "video",
      "src": "/assets/images/Home page/12245591_3840_2160_30fps.mp4",
      "craftName": "शाही हातमाग रेशीम आणि जरीकाम",
      "tagline": "लाकडी हातमागांवर अस्सल जरीच्या धाग्यांनी अलवार विणले जाणारे राजेशाही रेशमी वस्त्र.",
      "location": "चंदेरी आणि वाराणसी",
      "badge": "शाही हातमाग व्हिडिओ"
    },
    {
      "id": 12,
      "type": "video",
      "src": "/assets/images/Home page/148230-793717994.mp4",
      "craftName": "कुंभाराचे चाक — जिवंत मातीकाम",
      "tagline": "फिरत्या चाकावर ओल्या मातीला हाताच्या स्पर्शाने सुंदर आकार देण्याची पुरातन कला.",
      "location": "विष्णुपूर आणि कच्छ",
      "badge": "मातीकला व्हिडिओ"
    },
    {
      "id": 13,
      "type": "video",
      "src": "/assets/images/Home page/15346256-hd_1920_1080_30fps.mp4",
      "craftName": "अभिजात धातूकाम आणि नक्षीकाम",
      "tagline": "कांस्य आणि पितळेच्या भांड्यांवर छिन्नी-हातोड्याने बारीक नक्षी कोरण्याची पिढीजात कला.",
      "location": "मुरादाबाद आणि बस्तर",
      "badge": "धातूकाम व्हिडिओ"
    }
  ],
  "ta": [
    {
      "id": 0,
      "type": "image",
      "src": "/assets/images/Home page/Kolhapuri_Chappals_in_roadside_shop_in_Kolhapur3.jpeg",
      "craftName": "பழங்கால கோலாப்பூரி தோல் கைவினை",
      "tagline": "4வது தலைமுறை கைவினைஞர்களின் இயற்கை தோல் பதனிடுதல் முறையில் தைக்கப்பட்ட கோலாப்பூரி செருப்புகள்.",
      "location": "கோலாப்பூர், மகாராஷ்டிரா",
      "badge": "GI சான்றிதழ் பெற்றது"
    },
    {
      "id": 1,
      "type": "video",
      "src": "/assets/images/Home page/local artist.mp4",
      "craftName": "கைவினைஞர் நேரடி படைப்பு பணி",
      "tagline": "பாரம்பரிய கைவினைஞர்கள் நுணுக்கமான கலை நயங்களை நேரடியாக உருவாக்குவதை காணுங்கள்.",
      "location": "நேரடி பணிமனை, இந்தியா",
      "badge": "கைவினைஞர் நேரடி வீடியோ"
    },
    {
      "id": 2,
      "type": "image",
      "src": "/assets/images/Home page/Making_of_bamboo_and_palm_leaf_handicarft_products.jpg",
      "craftName": "மூங்கில் & பனை ஓலை கைவினை",
      "tagline": "உள்ளூர் கைவினைஞர்கள் பாரம்பரிய முறையில் மூங்கில் மற்றும் பனை ஓலையில் இயற்கை கைவினைப்பொருட்கள் செய்கிறார்கள்.",
      "location": "மாஜுலி தீவு, அசாம்",
      "badge": "யுனெஸ்கோ பாரம்பரியம்"
    },
    {
      "id": 3,
      "type": "video",
      "src": "/assets/images/Home page/Handmade craft stall.mp4",
      "craftName": "பாரம்பரிய கைவினை அங்காடி",
      "tagline": "பாரம்பரிய கைவினைஞர்களின் நேரடி விற்பனை ஸ்டால்கள் மற்றும் வாழும் கலைக்கூடங்களை அனுபவியுங்கள்.",
      "location": "பவானி மண்டபம், மகாராஷ்டிரா",
      "badge": "பாரம்பரிய கைவினை வீடியோ"
    },
    {
      "id": 4,
      "type": "image",
      "src": "/assets/images/Home page/Bharud.jpg",
      "craftName": "பாரத் — ஆன்மீக நாட்டுப்புற கலை",
      "tagline": "மகாராஷ்டிராவின் இசை, நாடக நடிப்பு மற்றும் பக்தியை இணைக்கும் உயிரோட்டமான நாட்டுப்புற கலை.",
      "location": "கிராமப்புற மகாராஷ்டிரா",
      "badge": "உயிரோட்டமான பாரம்பரியம்"
    },
    {
      "id": 5,
      "type": "video",
      "src": "/assets/images/Home page/Craft shop.mp4",
      "craftName": "பாரம்பரிய கைவினை கடைவீதி",
      "tagline": "தலைமுறைகளாக தொடரும் கைவினைப் பொருட்களின் உண்மையான கடைகள் மற்றும் கலை நயத்தை உணருங்கள்.",
      "location": "ஜெய்ப்பூர், இந்தியா",
      "badge": "கைவினை மரபு வீடியோ"
    },
    {
      "id": 6,
      "type": "video",
      "src": "/assets/images/Home page/Bamboo_basket_making.ogv",
      "craftName": "பாரம்பரிய மூங்கில் கூடை நெசவு",
      "tagline": "பச்சை மூங்கிலை அறுத்து கைகளால் உறுதியான மற்றும் அழகான கூடைகள் முடையும் காட்சியை பாருங்கள்.",
      "location": "மேற்கு தொடர்ச்சி மலை",
      "badge": "மூங்கில் கலை வீடியோ"
    },
    {
      "id": 7,
      "type": "video",
      "src": "/assets/images/Home page/old leddy crafting.mp4",
      "craftName": "முதியோர் கைவினைப் பாரம்பரியம்",
      "tagline": "நூற்றாண்டுகளின் ஞானத்தை அடுத்த தலைமுறைக்கு வழங்கும் முதிய கைவினைஞர்களின் சுழலும் சக்கரம்.",
      "location": "கிராமப்புற இந்தியா",
      "badge": "வாழும் மரபு வீடியோ"
    },
    {
      "id": 8,
      "type": "video",
      "src": "/assets/images/Home page/17_Tribes,_One_heartbeat_-_Hornbill_Festival.webm",
      "craftName": "ஹார்ன்பில் பழங்குடி திருவிழா",
      "tagline": "17 பழங்குடி இனங்களின் பாரம்பரிய நடனங்கள், இசைக் கருவிகள் மற்றும் உடைகளின் கண்கவர் திருவிழா.",
      "location": "நாகாலாந்து",
      "badge": "வடகிழக்கு பண்பாட்டு வீடியோ"
    },
    {
      "id": 9,
      "type": "video",
      "src": "/assets/images/Home page/A_aesthetic_Fire_Pot_Dance.ogv",
      "craftName": "அக்னி சட்டி நடனம் — ஆன்மீக சடங்கு",
      "tagline": "தலையில் எரியும் தீச்சட்டியுடன் பக்தி பரவசத்துடன் ஆடப்படும் பண்டைய கோவில் சடங்கு நடனம்.",
      "location": "தென்னிந்தியா",
      "badge": "புனித சடங்கு வீடியோ"
    },
    {
      "id": 10,
      "type": "video",
      "src": "/assets/images/Home page/Kakada_Bhajan_(3).webm",
      "craftName": "காக்கட பஜனை — பக்தி பாரம்பரியம்",
      "tagline": "அதிகாலை வேளையில் தாளங்கள் முழங்க பாடப்படும் பல நூற்றாண்டுகள் பழமையான பக்தி கீர்த்தனைகள்.",
      "location": "பண்டரிபுரம்",
      "badge": "பக்தி மரபு வீடியோ"
    },
    {
      "id": 11,
      "type": "video",
      "src": "/assets/images/Home page/12245591_3840_2160_30fps.mp4",
      "craftName": "பாரம்பரிய பட்டு & ஜரிகை நெசவு",
      "tagline": "பாரம்பரிய மரத்தறி நெசவில் தூய ஜரிகை நூல்களால் நுணுக்கமாக நெய்யப்படும் அரச பட்டு ஆடைகள்.",
      "location": "வாரணாசி & காஞ்சிபுரம்",
      "badge": "பட்டு நெசவு வீடியோ"
    },
    {
      "id": 12,
      "type": "video",
      "src": "/assets/images/Home page/148230-793717994.mp4",
      "craftName": "பாரம்பரிய மண்பாண்ட சக்கர கலை",
      "tagline": "சுழலும் சக்கரத்தில் ஈர மண்ணை கொண்டு கலைநயமிக்க பானைகள் மற்றும் சிலைகள் செய்யும் அற்புத கலை.",
      "location": "பிஷ்ணுபூர் & கட்ச்",
      "badge": "மண்பாண்ட கலை வீடியோ"
    },
    {
      "id": 13,
      "type": "video",
      "src": "/assets/images/Home page/15346256-hd_1920_1080_30fps.mp4",
      "craftName": "பாரம்பரிய உலோக சிற்ப வேலைப்பாடு",
      "tagline": "வெண்கலம் மற்றும் பித்தளை உலோகங்களில் உளி கொண்டு நுணுக்கமான தெய்வ உருவங்களை செதுக்கும் கலை.",
      "location": "மொராதாபாத் & பஸ்தர்",
      "badge": "உலோக கைவினை வீடியோ"
    }
  ],
  "te": [
    {
      "id": 0,
      "type": "image",
      "src": "/assets/images/Home page/Kolhapuri_Chappals_in_roadside_shop_in_Kolhapur3.jpeg",
      "craftName": "వారసత్వ కోల్హాపూరి తోలు కళ",
      "tagline": "4వ తరం కళాకారుల ప్రకృతి సిద్ధమైన పద్ధతిలో చేతితో కుట్టిన కోల్హాపూరి చెప్పులు.",
      "location": "కోల్హాపూర్, మహారాష్ట్ర",
      "badge": "GI ట్యాగ్ సర్టిఫైడ్"
    },
    {
      "id": 1,
      "type": "video",
      "src": "/assets/images/Home page/local artist.mp4",
      "craftName": "పనిలో నిమగ్నమైన మాస్టర్ కళాకారుడు",
      "tagline": "వంశపారంపర్య కళాకారులు అద్భుతమైన సాంప్రదాయ నమూనాలను గీస్తుండగా ప్రత్యక్షంగా వీక్షించండి.",
      "location": "కళా శాల, భారతదేశం",
      "badge": "మాస్టర్ కళాకారుడు వీడియో"
    },
    {
      "id": 2,
      "type": "image",
      "src": "/assets/images/Home page/Making_of_bamboo_and_palm_leaf_handicarft_products.jpg",
      "craftName": "వెదురు & తాటాకు పర్యావరణ హస్తకళ",
      "tagline": "స్థానిక కళాకారులు చేతితో వెదురు మరియు తాటాకుతో ప్రకృతిసిద్ధమైన అద్భుత హస్తకళలు రూపొందిస్తారు.",
      "location": "మజులి ద్వీపం, అస్సాం",
      "badge": "యునెస్కో వారసత్వ అభ్యర్థి"
    },
    {
      "id": 3,
      "type": "video",
      "src": "/assets/images/Home page/Handmade craft stall.mp4",
      "craftName": "సజీవ హస్తకళా కేంద్రాలు",
      "tagline": "సాంప్రదాయ కళాకారుల స్టాళ్లు మరియు ప్రామాణికమైన హస్తకళల ప్రత్యక్ష అనుభూతిని పొందండి.",
      "location": "భవాని మండపం, మహారాష్ట్ర",
      "badge": "సజీవ వారసత్వ వీడియో"
    },
    {
      "id": 4,
      "type": "image",
      "src": "/assets/images/Home page/Bharud.jpg",
      "craftName": "భారుద్ — పవిత్ర జానపద కళారూపం",
      "tagline": "మహారాష్ట్ర యొక్క జీవంతమైన జానపద కళ సంగీతం, నాటకం మరియు భక్తి సందేశాల మేళవింపు.",
      "location": "గ్రామీణ మహారాష్ట్ర",
      "badge": "జీవంతమైన అమూర్త వారసత్వం"
    },
    {
      "id": 5,
      "type": "video",
      "src": "/assets/images/Home page/Craft shop.mp4",
      "craftName": "వారసత్వ హస్తకళా కేంద్రాలు",
      "tagline": "తరతరాల సాంస్కృతిక విశిష్టతను చాటే చేతితో చేసిన కళాఖండాల దుకాణాలను సందర్శించండి.",
      "location": "జైపూర్, భారతదేశం",
      "badge": "హస్తకళా వారసత్వ వీడియో"
    },
    {
      "id": 6,
      "type": "video",
      "src": "/assets/images/Home page/Bamboo_basket_making.ogv",
      "craftName": "సాంప్రదాయ వెదురు బుట్టల అల్లిక",
      "tagline": "పచ్చి వెదురును చీల్చి అద్భుతమైన నైపుణ్యంతో ధాన్యపు బుట్టలను అల్లే ప్రత్యక్ష దృశ్యం.",
      "location": "పశ్చిమ కనుమలు & మజులి",
      "badge": "వెదురు కళ వీడియో"
    },
    {
      "id": 7,
      "type": "video",
      "src": "/assets/images/Home page/old leddy crafting.mp4",
      "craftName": "వయోవృద్ధ కళాకారుల నేర్పు",
      "tagline": "తరతరాల అనుభవంతో రాట్నంపై దారాలు తీస్తూ జ్ఞానాన్ని అందించే వృద్ధ నేత కళాకారిణులు.",
      "location": "గ్రామీణ ప్రాంతాలు",
      "badge": "సజీవ లెజెండ్ వీడియో"
    },
    {
      "id": 8,
      "type": "video",
      "src": "/assets/images/Home page/17_Tribes,_One_heartbeat_-_Hornbill_Festival.webm",
      "craftName": "హార్న్‌బిల్ గిరిజన ఉత్సవం",
      "tagline": "17 స్థానిక తెగల సమ్మేళనం, సాంప్రదాయ వాయిద్యాలు మరియు రంగురంగుల నృత్యాల అద్భుత ప్రదర్శన.",
      "location": "నాగాలాండ్",
      "badge": "ఈశాన్య సంస్కృతి వీడియో"
    },
    {
      "id": 9,
      "type": "video",
      "src": "/assets/images/Home page/A_aesthetic_Fire_Pot_Dance.ogv",
      "craftName": "అగ్ని కుండ నృత్యం — పవిత్ర ఆలయ ఆచారం",
      "tagline": "తల పై అగ్ని కుండాలు ధరించి భక్తి శ్రద్ధలతో ప్రదర్శించే పురాతన ఆలయ నృత్య విన్యాసం.",
      "location": "దక్షిణ భారతదేశం",
      "badge": "పవిత్ర ఆచార వీడియో"
    },
    {
      "id": 10,
      "type": "video",
      "src": "/assets/images/Home page/Kakada_Bhajan_(3).webm",
      "craftName": "కాకడ భజన & వార్కరీ భక్తి గానం",
      "tagline": "వేకువజామున తాళాలు, మృదంగ నాదాలతో ఆలపించే శతాబ్దాల పురాతన పవిత్ర భక్తి సంకీర్తన.",
      "location": "పండరీపురం",
      "badge": "ఆధ్యాత్మిక వారసత్వ వీడియో"
    },
    {
      "id": 11,
      "type": "video",
      "src": "/assets/images/Home page/12245591_3840_2160_30fps.mp4",
      "craftName": "రాజవంశ చేనేత పట్టు & జరీ నేత",
      "tagline": "పురాతన చెక్క మగ్గాలపై స్వచ్ఛమైన జరీ దారాలతో రూపొందించే అద్భుతమైన పట్టు వస్త్రాలు.",
      "location": "చందేరి & వారణాసి",
      "badge": "చేనేత వారసత్వ వీడియో"
    },
    {
      "id": 12,
      "type": "video",
      "src": "/assets/images/Home page/148230-793717994.mp4",
      "craftName": "కుమ్మరి చక్రం — మట్టి కళాఖండాలు",
      "tagline": "గిర్రున తిరిగే చక్రంపై తడి మట్టిని అద్భుత ఆకారాలుగా తీర్చిదిద్దే పురాతన కుమ్మరి కళ.",
      "location": "కచ్ & బిష్ణుపూర్",
      "badge": "కుమ్మరి కళ వీడియో"
    },
    {
      "id": 13,
      "type": "video",
      "src": "/assets/images/Home page/15346256-hd_1920_1080_30fps.mp4",
      "craftName": "పురాతన లోహ కళ & కాంస్య చెక్కడాలు",
      "tagline": "కాంస్యం మరియు రాగి పాత్రలపై ఉలితో పౌరాణిక బొమ్మలను చెక్కే వంశపారంపర్య లోహ కళాకారులు.",
      "location": "మొరాదాబాద్ & బస్తర్",
      "badge": "లోహ కళా వీడియో"
    }
  ],
  "bn": [
    {
      "id": 0,
      "type": "image",
      "src": "/assets/images/Home page/Kolhapuri_Chappals_in_roadside_shop_in_Kolhapur3.jpeg",
      "craftName": "ঐতিহ্যবাহী কোলহাপুরী চামড়াশিল্প",
      "tagline": "চতুর্থ প্রজন্মের অভিজ্ঞ কারিগরদের বাবলা ছাল ও হরিতকী দিয়ে সম্পূর্ণ ভেষজ পদ্ধতিতে তৈরি কোলহাপুরী চটি।",
      "location": "কোলহাপুর, মহারাষ্ট্র",
      "badge": "জিআই ট্যাগ প্রাপ্ত • ১০০% ভেষজ ট্যানিং"
    },
    {
      "id": 1,
      "type": "video",
      "src": "/assets/images/Home page/local artist.mp4",
      "craftName": "কর্মরত প্রধান কারিগর",
      "tagline": "বংশপরম্পরা কারিগরদের সরাসরি ঐতিহ্যবাহী নকশা ও তুলির ছোঁয়ায় শিল্পকর্ম তৈরি দেখুন।",
      "location": "সরাসরি কর্মশালা, ভারত",
      "badge": "মাস্টার আর্টিসান ভিডিও"
    },
    {
      "id": 2,
      "type": "image",
      "src": "/assets/images/Home page/Making_of_bamboo_and_palm_leaf_handicarft_products.jpg",
      "craftName": "বাঁশ ও তালপাতার পরিবেশবান্ধব শিল্প",
      "tagline": "স্থানীয় কারিগররা পরম যত্নে বাঁশ ও তালপাতা দিয়ে অপূর্ব হস্তশিল্প সামগ্রী তৈরি করেন।",
      "location": "মাজুলী দ্বীপ, আসাম",
      "badge": "ইউনেস্কো ঐতিহ্য দাবিদার"
    },
    {
      "id": 3,
      "type": "video",
      "src": "/assets/images/Home page/Handmade craft stall.mp4",
      "craftName": "সরাসরি হস্তশিল্প হাট",
      "tagline": "ঐতিহ্যবাহী কারিগরদের খাঁটি স্টল ও কাজের প্রাণবন্ত পরিবেশ উপভোগ করুন।",
      "location": "ভবানী মণ্ডপ, মহারাষ্ট্র",
      "badge": "জীবন্ত ঐতিহ্য ভিডিও"
    },
    {
      "id": 4,
      "type": "image",
      "src": "/assets/images/Home page/Bharud.jpg",
      "craftName": "ভারুড — লোক নাট্য ও সঙ্গীত",
      "tagline": "মহারাষ্ট্রের এই জীবন্ত লোকশিল্পে সঙ্গীত, অভিনয় ও আধ্যাত্মিক চেতনার অপূর্ব মিশ্রণ।",
      "location": "গ্রামীণ মহারাষ্ট্র",
      "badge": "জীবন্ত অমূর্ত ঐতিহ্য"
    },
    {
      "id": 5,
      "type": "video",
      "src": "/assets/images/Home page/Craft shop.mp4",
      "craftName": "ঐতিহ্যবাহী হস্তশিল্পের হাট",
      "tagline": "বংশপরম্পরায় সংরক্ষিত হাতে তৈরি শিল্পপণ্যের খাঁটি ভারতীয় বাজারের অভিজ্ঞতা নিন।",
      "location": "জয়পুর ও পশ্চিম ভারত",
      "badge": "হস্তশিল্প ঐতিহ্য ভিডিও"
    },
    {
      "id": 6,
      "type": "video",
      "src": "/assets/images/Home page/Bamboo_basket_making.ogv",
      "craftName": "বাঁশের ঐতিহ্যবাহী খাঁটি বয়ন",
      "tagline": "বাঁশের কাঠি নিখুঁতভাবে চিরে হাতে মজবুত ঝুড়ি বোনার অসাধারণ দৃশ্য প্রত্যক্ষ করুন।",
      "location": "পশ্চিমঘাট ও মাজুলী",
      "badge": "বাঁশ বয়ন ভিডিও"
    },
    {
      "id": 7,
      "type": "video",
      "src": "/assets/images/Home page/old leddy crafting.mp4",
      "craftName": "প্রবীণ কারিগরদের চিরন্তন সাধনা",
      "tagline": "চরকায় সুতো কেটে প্রাচীন ঐতিহ্যকে বাঁচিয়ে রাখা গ্রামীণ প্রবীণ শিল্পীদের স্নেহস্পর্শ।",
      "location": "প্রাণপুর ও গ্রামীণ ভারত",
      "badge": "জীবন্ত ঐতিহ্য ভিডিও"
    },
    {
      "id": 8,
      "type": "video",
      "src": "/assets/images/Home page/17_Tribes,_One_heartbeat_-_Hornbill_Festival.webm",
      "craftName": "হর্নবিল উৎসব — নাগাল্যান্ডের আদিবাসী ঐতিহ্য",
      "tagline": "১৭টি আদিবাসী উপজাতির মিলনমেলা, ঐতিহ্যবাহী যুদ্ধবাদ্য ও বর্ণাঢ্য লোকনৃত্যের মহোৎসব।",
      "location": "কিসামা, নাগাল্যান্ড",
      "badge": "উত্তর-পূর্ব ঐতিহ্য ভিডিও"
    },
    {
      "id": 9,
      "type": "video",
      "src": "/assets/images/Home page/A_aesthetic_Fire_Pot_Dance.ogv",
      "craftName": "অগ্নি পাত্র নৃত্য — আধ্যাত্মিক আচার",
      "tagline": "মাথায় জ্বলন্ত মাটির অগ্নিকুণ্ড নিয়ে প্রাচীন মন্দিরের ভক্তি ও শক্তির অপূর্ব আত্মনিবেদন।",
      "location": "দক্ষিণ ভারত ও মহারাষ্ট্র",
      "badge": "পবিত্র আচার ভিডিও"
    },
    {
      "id": 10,
      "type": "video",
      "src": "/assets/images/Home page/Kakada_Bhajan_(3).webm",
      "craftName": "কাকড়া ভজন — ওয়ারকারী ভক্তিগীতি",
      "tagline": "ভোরের আলো ফোটার সময় কাঁসর ও পাখোয়াজের সুরে নিবেদিত শতাব্দী প্রাচীন ভক্তিগীতি।",
      "location": "পন্ধরপুর, মহারাষ্ট্র",
      "badge": "আধ্যাত্মিক ঐতিহ্য ভিডিও"
    },
    {
      "id": 11,
      "type": "video",
      "src": "/assets/images/Home page/12245591_3840_2160_30fps.mp4",
      "craftName": "রাজকীয় হস্তচালিত রেশম ও জরি বয়ন",
      "tagline": "কাঠের তাঁতে খাঁটি জরি সুতো দিয়ে সূক্ষ্ম কারুকার্যে বোনা রাজকীয় সিল্ক বস্ত্রের ঐতিহ্য।",
      "location": "চন্দেরী ও বারাণসী",
      "badge": "হস্তচালিত তাঁত ভিডিও"
    },
    {
      "id": 12,
      "type": "video",
      "src": "/assets/images/Home page/148230-793717994.mp4",
      "craftName": "কুমোরের চাকে জীবন্ত পোড়ামাটি শিল্প",
      "tagline": "ঘূর্ণায়মান চাকে কাঁচা মাটিকে নিপুণ স্পর্শে অপরূপ দেবপাত্র ও মৃৎশিল্পে রূপ দেওয়ার দৃশ্য।",
      "location": "বিষ্ণুপুর ও কচ্ছ",
      "badge": "মৃৎশিল্প ভিডিও"
    },
    {
      "id": 13,
      "type": "video",
      "src": "/assets/images/Home page/15346256-hd_1920_1080_30fps.mp4",
      "craftName": "ঐতিহ্যবাহী কাঁসা ও পেতল ধাতুশিল্প",
      "tagline": "তামা ও ব্রোঞ্জের পাতে ছেনি-হাতুড়ি দিয়ে পৌরাণিক নকশা খোদাই করার অনুপম ধাতব শিল্প।",
      "location": "মোরাদাবাদ ও বস্তার",
      "badge": "ধাতুশিল্প ভিডিও"
    }
  ]
};

export const LOCALIZED_HOMEPAGE_UI: Record<SupportedLanguage, {
  discoverHeading: string;
  verifiedArtisansBadge: string;
  giTagBadge: string;
  directIncomeBadge: string;
  searchPlaceholder: string;
  allCraftsCategory: string;
  workshopsHeading: string;
  workshopsSubtitle: string;
  viewAtelierBtn: string;
  bookBtn: string;
  trustScoreLabel: string;
  heritageMapHeading: string;
  heritageMapSubtitle: string;
  activeAteliersLabel: string;
}> = {
  en: {
    discoverHeading: "Discover India's",
    verifiedArtisansBadge: "100% Verified Hereditary Artisans",
    giTagBadge: "GI Tag Protected Crafts",
    directIncomeBadge: "96% Direct-to-Artisan Payouts",
    searchPlaceholder: "Search by craft, artisan name, village or district...",
    allCraftsCategory: "All Crafts",
    workshopsHeading: "Master Artisan Workshops",
    workshopsSubtitle: "Handcrafted living lineages, direct atelier sessions & GI-certified masterclasses",
    viewAtelierBtn: "View Atelier & Book →",
    bookBtn: "Book Workshop",
    trustScoreLabel: "Trust Score",
    heritageMapHeading: "Living Heritage Craft Map",
    heritageMapSubtitle: "Locate authentic hereditary artisan clusters across India with Survey of India administrative accuracy",
    activeAteliersLabel: "Verified Craft Ateliers Active"
  },
  hi: {
    discoverHeading: "अनुभव करें भारत का",
    verifiedArtisansBadge: "100% सत्यापित वंशानुगत कारीगर",
    giTagBadge: "जीआई टैग संरक्षित हस्तशिल्प",
    directIncomeBadge: "96% सीधा कारीगर भुगतान",
    searchPlaceholder: "शिल्प, कारीगर का नाम, गांव या जिला खोजें...",
    allCraftsCategory: "सभी हस्तशिल्प",
    workshopsHeading: "उस्ताद कारीगर कार्यशालाएं",
    workshopsSubtitle: "हस्तनिर्मित जीवंत धरोहर, प्रत्यक्ष कार्यशाला सत्र और जीआई प्रमाणित मास्टरक्लास",
    viewAtelierBtn: "कार्यशाला देखें व बुक करें →",
    bookBtn: "वर्कशॉप बुक करें",
    trustScoreLabel: "सत्यापन स्कोर",
    heritageMapHeading: "सजीव धरोहर शिल्प मानचित्र",
    heritageMapSubtitle: "सर्वे ऑफ इंडिया प्रशासनिक सटीकता के साथ भारत भर के प्रामाणिक कारीगर समूहों को खोजें",
    activeAteliersLabel: "सत्यापित शिल्प कार्यशालाएं सक्रिय"
  },
  mr: {
    discoverHeading: "अनुभवा भारताची",
    verifiedArtisansBadge: "१००% सत्यापित पिढीजात कारागीर",
    giTagBadge: "जीआय मानांकन संरक्षित कला",
    directIncomeBadge: "९६% थेट कारागिरांना उत्पन्न",
    searchPlaceholder: "हस्तकला, कारागिराचे नाव, गाव किंवा जिल्हा शोधा...",
    allCraftsCategory: "सर्व हस्तकला",
    workshopsHeading: "मास्टर कारागीर कार्यशाळा",
    workshopsSubtitle: "हस्तनिर्मित जिवंत परंपरा, प्रत्यक्ष कार्यशाळा आणि जीआय प्रमाणित मास्टरक्लास",
    viewAtelierBtn: "कार्यशाळा पहा व नोंदणी करा →",
    bookBtn: "कार्यशाळा बुक करा",
    trustScoreLabel: "सत्यापन स्कोअर",
    heritageMapHeading: "वारसा हस्तकला नकाशा",
    heritageMapSubtitle: "सर्व्हे ऑफ इंडियाच्या प्रशासकीय अचूकतेसह भारतातील अस्सल कारागीर क्लस्टर्स शोधा",
    activeAteliersLabel: "सत्यापित कार्यशाळा सक्रिय"
  },
  ta: {
    discoverHeading: "இந்தியாவின் அனுபவம்",
    verifiedArtisansBadge: "100% சரிபார்க்கப்பட்ட கைவினைஞர்கள்",
    giTagBadge: "புவிசார் குறியீடு பாதுகாக்கப்பட்ட கலை",
    directIncomeBadge: "96% நேரடி கலைஞர் வருவாய்",
    searchPlaceholder: "கைவினை, கலைஞர் பெயர், கிராமம் அல்லது மாவட்டத்தை தேடுங்கள்...",
    allCraftsCategory: "அனைத்து கைவினைகளும்",
    workshopsHeading: "முதன்மை கலைஞர் பட்டறைகள்",
    workshopsSubtitle: "பாரம்பரிய நேரடி பட்டறை அமர்வுகள் மற்றும் சான்றளிக்கப்பட்ட வகுப்புகள்",
    viewAtelierBtn: "பட்டறையை காண்க & முன்பதிவு செய்க →",
    bookBtn: "முன்பதிவு செய்க",
    trustScoreLabel: "நம்பகத்தன்மை மதிப்பீடு",
    heritageMapHeading: "பாரம்பரிய கைவினை வரைபடம்",
    heritageMapSubtitle: "இந்திய அளவிலான அதிகாரப்பூர்வ நிர்வாக துல்லியத்துடன் கலைஞர் மையங்களை கண்டறியவும்",
    activeAteliersLabel: "சரிபார்க்கப்பட்ட பட்டறைகள் இயங்குகின்றன"
  },
  te: {
    discoverHeading: "భారతదేశ అద్భుతమైన",
    verifiedArtisansBadge: "100% ధృవీకరించబడిన వంశపారంపర్య కళాకారులు",
    giTagBadge: "జిఐ ట్యాగ్ రక్షిత హస్తకళలు",
    directIncomeBadge: "96% కళాకారులకు నేరుగా చెల్లింపు",
    searchPlaceholder: "కళ, కళాకారుడి పేరు, గ్రామం లేదా జిల్లాను శోధించండి...",
    allCraftsCategory: "అన్ని హస్తకళలు",
    workshopsHeading: "మాస్టర్ ఆర్టిసన్ వర్క్‌షాప్‌లు",
    workshopsSubtitle: "హస్తకళల ప్రత్యక్ష వర్క్‌షాప్ సెషన్‌లు మరియు జిఐ సర్టిఫైడ్ మాస్టర్‌క్లాస్‌లు",
    viewAtelierBtn: "వర్క్‌షాప్‌ను వీక్షించి బుక్ చేయండి →",
    bookBtn: "బుక్ చేయండి",
    trustScoreLabel: "నమ్మక స్కోరు",
    heritageMapHeading: "సజీవ వారసత్వ హస్తకళా పటం",
    heritageMapSubtitle: "సర్వే ఆఫ్ ఇండియా ఖచ్చితత్వంతో భారతదేశం అంతటా ప్రామాణికమైన కళాకారుల క్లస్టర్‌లను గుర్తించండి",
    activeAteliersLabel: "ధృవీకరించబడిన వర్క్‌షాప్‌లు యాక్టివ్‌గా ఉన్నాయి"
  },
  bn: {
    discoverHeading: "আবিষ্কার করুন ভারতের",
    verifiedArtisansBadge: "১০০% যাচাইকৃত বংশপরম্পরা কারিগর",
    giTagBadge: "জিআই ট্যাগ সুরক্ষিত হস্তশিল্প",
    directIncomeBadge: "৯৬% সরাসরি কারিগরের আয়",
    searchPlaceholder: "শিল্প, কারিগরের নাম, গ্রাম বা জেলা খুঁজুন...",
    allCraftsCategory: "সকল শিল্পকলা",
    workshopsHeading: "উস্তাদ কারিগর কর্মশালা",
    workshopsSubtitle: "হস্তনির্মিত জীবন্ত ঐতিহ্য, সরাসরি কর্মশালা ও জিআই প্রত্যয়িত মাস্টারক্লাস",
    viewAtelierBtn: "কর্মশালা দেখুন ও বুক করুন →",
    bookBtn: "বুক করুন",
    trustScoreLabel: "যাচাইকরণ স্কোর",
    heritageMapHeading: "ঐতিহ্যবাহী হস্তশিল্প মানচিত্র",
    heritageMapSubtitle: "সার্ভে অফ ইন্ডিয়ার প্রশাসনিক নির্ভুলতার সাথে সমগ্র ভারতের খাঁটি কারিগর দল খুঁজুন",
    activeAteliersLabel: "সক্রিয় যাচাইকৃত কর্মশালা"
  }
};



export const CULTURAL_EXPERIENCES: CulturalExperience[] = [
  {
    id: 'cult_01',
    title: 'Traditional Marma & Indigenous Bone-Setting Lineage',
    tradition_name: 'Marma Chikitsa & Herbal Poultices',
    description: 'Centuries-old hereditary orthopedic healing and joint alignment practiced through botanical oils, bamboo splints, and generational touch techniques.',
    category: 'Community Medicine',
    location_name: 'Puttur & Malabar Belt',
    district: 'Chittoor',
    state: 'Andhra Pradesh',
    lat: 13.4418,
    lng: 79.5539,
    cover_image: '/assets/images/Culture/Traditional_Bone_Setting.jpg',
    season: 'Year-round traditional consultations',
    community_custodians: 'Vaidya Kshatriya & Marma Guilds',
    trust_score: 99,
    significance: 'Recognized under Ministry of AYUSH traditional indigenous medicine repositories.'
  },
  {
    id: 'cult_02',
    title: 'Bodo-Kachari Indigenous Loom Songs & Spring Customs',
    tradition_name: 'Bagurumba Dance & Dokhona Silk Rites',
    description: 'Ancestral butterfly-movement spring rituals accompanied by Kham drums, Sifung flutes, and hand-spun floral Dokhona ceremonial weaving.',
    category: 'Tribal Customs',
    location_name: 'Kokrajhar Bodoland',
    district: 'Kokrajhar',
    state: 'Assam',
    lat: 26.4014,
    lng: 90.2716,
    cover_image: '/assets/images/Culture/Bodo-Kachari_2.jpg',
    season: 'Bwisagu Spring Festival (April)',
    community_custodians: 'Bodo Women Weaving & Cultural Guild',
    trust_score: 97,
    significance: 'UNESCO Intangible Folk Heritage Documentation.'
  },
  {
    id: 'cult_03',
    title: 'Dhunuchi Naach & Kumartuli Clay Deity Invocation',
    tradition_name: 'Sacred Dhunuchi Aarti with Dhak Rhythm',
    description: 'Ecstatic clay-censer devotional dance with burning coconut husk and camphor, celebrating the living artisan deity sculpted from holy Ganges clay.',
    category: 'Sacred Rituals',
    location_name: 'Kumartuli Ghats, Kolkata',
    district: 'Kolkata',
    state: 'West Bengal',
    lat: 22.5986,
    lng: 88.3639,
    cover_image: '/assets/images/Culture/Dancing_mood_of_Durga_Puja.jpg',
    season: 'Sharadotsav (September – October)',
    community_custodians: 'Kumartuli Sculptors Guild & Dhakis',
    trust_score: 98,
    significance: 'UNESCO Representative List of the Intangible Cultural Heritage of Humanity.'
  },
  {
    id: 'cult_04',
    title: 'Kokan Shimga Palakhi Nrutya (Village Deities Palanquin Dance)',
    tradition_name: 'Shimagotsav Ancestral Palanquin Swaying',
    description: 'Spectacular village gathering where hereditary bearers dance through narrow betel-nut groves carrying sacred wooden palanquins of gram-daivatas.',
    category: 'Seasonal Festival',
    location_name: 'Konkan Coastal Villages',
    district: 'Ratnagiri',
    state: 'Maharashtra',
    lat: 16.9902,
    lng: 73.3120,
    cover_image: '/assets/images/Culture/Palakhinrutya_-_Dance_of_Palanquin_of_Village_Dities_-_Shimagotsav_in_Kokan_-_Maharashtra.jpg',
    season: 'Holi / Shimga (March)',
    community_custodians: 'Kokan Gramstha & Tarang Custodians',
    trust_score: 96,
    significance: '400-year-old coastal Konkan agrarian community cohesion ritual.'
  },
  {
    id: 'cult_05',
    title: 'Bhil & Bhilala Bhagoria Haat Festival of Colors',
    tradition_name: 'Tribal Harvest Courtship & Dhol Assemblies',
    description: 'Vibrant tribal carnival of giant dhol drums, brass ornaments, gulal celebrations, and community bonding across the Vindhyan hills.',
    category: 'Seasonal Festival',
    location_name: 'Jhabua Tribal Belt',
    district: 'Jhabua',
    state: 'Madhya Pradesh',
    lat: 22.7699,
    lng: 74.5936,
    cover_image: '/assets/images/Culture/The_Bhagoria_festival.jpg',
    season: 'Week preceding Holi (March)',
    community_custodians: 'Bhil & Bhilala Tribal Elders',
    trust_score: 97,
    significance: 'Ancient indigenous harvest Thanksgiving and agrarian matchmaking fair.'
  },
  {
    id: 'cult_06',
    title: 'Chhath Mahaparv — Vedic Riverbank Solar Worship',
    tradition_name: 'Riverbed Arghya with Handmade Bamboo Soop',
    description: 'Austerity festival honoring Surya and Chhathi Maiya on the banks of holy rivers, using 100% organic offerings and bamboo woven winnowing baskets.',
    category: 'Sacred Rituals',
    location_name: 'Ganga Ghats, Patna',
    district: 'Patna',
    state: 'Bihar',
    lat: 25.6120,
    lng: 85.1440,
    cover_image: '/assets/images/Culture/Devotees_offer_prayers_on_the_occasion_of_the_Chhath_Puja_festival.jpg',
    season: 'Kartik Shukla Shashthi (November)',
    community_custodians: 'Ganga Ghat Parvatis & Bamboo Guilds',
    trust_score: 99,
    significance: 'Vedic solar science and ecological reverence unchanged for over 3,000 years.'
  },
  {
    id: 'cult_07',
    title: 'Gond & Baiga Forest Storytelling with Bana Strings',
    tradition_name: 'Pardhan Bardic Oral Epics of Mahua Groves',
    description: 'Mystical musical epics played on the two-stringed Bana instrument, recounting creation myths and sacred relationships with the Narmada valley flora.',
    category: 'Folk Heritage',
    location_name: 'Maikal Hills, Dindori',
    district: 'Dindori',
    state: 'Madhya Pradesh',
    lat: 22.9520,
    lng: 81.0820,
    cover_image: '/assets/images/Culture/Folk_Artist.jpg',
    season: 'Autumn Forest Gatherings',
    community_custodians: 'Pardhan Gond Bards & Elders',
    trust_score: 98,
    significance: 'National Oral Heritage preservation and indigenous tribal mythology.'
  },
  {
    id: 'cult_08',
    title: 'Theyyam Sacred Grove Invocation & Poliyanthram',
    tradition_name: 'Living Deity Embodiment & Fire Walking',
    description: 'Ancestral temple ritual where hereditary performers don massive headdresses and red turmeric body paint to channel protective ancestral spirits.',
    category: 'Sacred Rituals',
    location_name: 'North Malabar Sacred Groves',
    district: 'Kannur',
    state: 'Kerala',
    lat: 11.8745,
    lng: 75.3704,
    cover_image: '/assets/images/Culture/Poliyanthram_podavadukkam.jpg',
    season: 'November to May (Kavu Rituals)',
    community_custodians: 'Vannar & Malayan Hereditary Custodians',
    trust_score: 99,
    significance: 'Over 1,500 years of unbroken sacred grove conservation and spiritual dance.'
  }
];
