import { Experience, Artisan, CulturalExperience } from '../types';
import { SupportedLanguage } from './translations';

export const LOCALIZED_EXPERIENCES: Record<SupportedLanguage, Experience[]> = {
  en: [
    {
      id: 'exp_kolhapur_01',
      artisan_id: 'art_kolhapur_01',
      artisan_name: 'Santosh Kamble',
      artisan_avatar: '/assets/images/Home%20page/Kolhapuri_Chappals_in_roadside_shop_in_Kolhapur3.jpeg',
      trust_score: 98,
      title: 'Heritage Kolhapuri Chappal Crafting Masterclass',
      description: 'Learn ancestral vegetable tanning using myrobalan and babool bark. Sit alongside 4th-generation master cobblers, shape traditional wooden lasts, hand-punch intricate motifs, and braid genuine leather straps.',
      category: 'Leathercraft',
      price_inr: 1850,
      duration_mins: 150,
      max_participants: 8,
      lat: 16.7050,
      lng: 74.2433,
      location_name: 'Shivaji Market, Kolhapur',
      district: 'Kolhapur',
      state: 'Maharashtra',
      cover_image: '/assets/images/Home%20page/Kolhapuri_Chappals_in_roadside_shop_in_Kolhapur3.jpeg',
      odop_tag: 'ODOP-MH-KOLHAPUR-LEATHER',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_chanderi_01',
      artisan_id: 'art_chanderi_01',
      artisan_name: 'Kamla Bai',
      artisan_avatar: '/assets/images/01-Hero/Chanderi_Craft_Village_â€“_Traditional_Weaving_and_Handicrafts_in_Madhya_Pradesh_01.jpg',
      trust_score: 97,
      title: 'Royal Chanderi Silk Pit-Loom Weaving & Zari Interlacing',
      description: 'Immerse yourself in 700-year-old Bundelkhand royalty. Sit in an earthen pit loom, handle pure mulberry silk and electroplated gold zari, and weave royal peacock motifs.',
      category: 'Handloom',
      price_inr: 2200,
      duration_mins: 180,
      max_participants: 6,
      lat: 24.7120,
      lng: 78.1380,
      location_name: 'Pranpur Craft Village, Chanderi',
      district: 'Ashoknagar',
      state: 'Madhya Pradesh',
      cover_image: '/assets/images/01-Hero/Chanderi_Craft_Village_â€“_Traditional_Weaving_and_Handicrafts_in_Madhya_Pradesh_01.jpg',
      odop_tag: 'ODOP-MP-CHANDERI-SILK',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_majuli_01',
      artisan_id: 'art_majuli_01',
      artisan_name: 'Hemanta Bora',
      artisan_avatar: '/assets/images/04-Bamboo-Cane/Innovative_Bamboo_Crafts_of_Assam.jpg',
      trust_score: 96,
      title: 'Neo-Vaishnavite Mukha Bamboo Mask Sculpting Masterclass',
      description: 'Learn the 500-year-old art of crafting mythical character masks (Mukha) using bamboo splits, organic Brahmaputra riverbed silt, and natural vegetable pigments.',
      category: 'Bamboo-Cane',
      price_inr: 1950,
      duration_mins: 180,
      max_participants: 8,
      lat: 26.9500,
      lng: 94.2167,
      location_name: 'Natun Samaguri Satra, Majuli Island',
      district: 'Majuli',
      state: 'Assam',
      cover_image: '/assets/images/04-Bamboo-Cane/Innovative_Bamboo_Crafts_of_Assam.jpg',
      odop_tag: 'ODOP-AS-MAJULI-MASKS',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_srinagar_01',
      artisan_id: 'art_srinagar_01',
      artisan_name: 'Ghulam Mohammad Zargar',
      artisan_avatar: '/assets/images/05-Wood-Pottery/Kashmiri_Woodcarving_And_Paper_machÃ©.jpg',
      trust_score: 99,
      title: 'Master Walnut Wood Undercut Relief & Chinar Carving',
      description: 'Master delicate chisel channelling and deep 3D floral undercut carving on seasoned Kashmir walnut wood root blocks in the heart of Old Srinagar.',
      category: 'Woodwork',
      price_inr: 2500,
      duration_mins: 180,
      max_participants: 6,
      lat: 34.0837,
      lng: 74.7973,
      location_name: 'Zadibal Guild, Old Srinagar',
      district: 'Srinagar',
      state: 'Jammu and Kashmir',
      cover_image: '/assets/images/05-Wood-Pottery/Kashmiri_Woodcarving_And_Paper_machÃ©.jpg',
      odop_tag: 'ODOP-JK-SRINAGAR-WALNUT',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_bishnupur_01',
      artisan_id: 'art_bishnupur_01',
      artisan_name: 'Subhas Kumbhakar',
      artisan_avatar: '/assets/images/05-Wood-Pottery/Artisan_decorating_ceramic_plate.jpg',
      trust_score: 96,
      title: 'Living Terracotta Temple Tile & Bankura Horse Modeling',
      description: 'Shape the iconic long-eared Bankura horse in five distinct hollow parts on a potter wheel, burnish with river stones, and fire in traditional wood kilns.',
      category: 'Pottery',
      price_inr: 1450,
      duration_mins: 150,
      max_participants: 8,
      lat: 23.0760,
      lng: 87.3190,
      location_name: 'Panchmura Village, Bankura',
      district: 'Bankura',
      state: 'West Bengal',
      cover_image: '/assets/images/05-Wood-Pottery/Artisan_decorating_ceramic_plate.jpg',
      odop_tag: 'ODOP-WB-BANKURA-HORSE',
      women_friendly: true,
      elderly_friendly: true
    }
  ],

  hi: [
    {
      id: 'exp_kolhapur_01',
      artisan_id: 'art_kolhapur_01',
      artisan_name: 'à¤¸à¤‚à¤¤à¥‹à¤· à¤•à¤¾à¤‚à¤¬à¤²à¥‡',
      artisan_avatar: '/assets/images/Home%20page/Kolhapuri_Chappals_in_roadside_shop_in_Kolhapur3.jpeg',
      trust_score: 98,
      title: 'à¤ªà¤¾à¤°à¤‚à¤ªà¤°à¤¿à¤• à¤•à¥‹à¤²à¥à¤¹à¤¾à¤ªà¥à¤°à¥€ à¤šà¤ªà¥à¤ªà¤² à¤¹à¤¸à¥à¤¤à¤¶à¤¿à¤²à¥à¤ª à¤®à¤¾à¤¸à¥à¤Ÿà¤°à¤•à¥à¤²à¤¾à¤¸',
      description: 'à¤¬à¤¬à¥‚à¤² à¤•à¥€ à¤›à¤¾à¤² à¤”à¤° à¤¹à¤°à¤¡à¤¼ à¤¸à¥‡ à¤ªà¥à¤°à¤¾à¤•à¥ƒà¤¤à¤¿à¤• à¤šà¤®à¤¡à¤¼à¤¾ à¤ªà¤•à¤¾à¤¨à¤¾ à¤¸à¥€à¤–à¥‡à¤‚à¥¤ à¤šà¥Œà¤¥à¥€ à¤ªà¥€à¤¢à¤¼à¥€ à¤•à¥‡ à¤®à¤¾à¤¸à¥à¤Ÿà¤° à¤•à¤¾à¤°à¥€à¤—à¤°à¥‹à¤‚ à¤•à¥‡ à¤¸à¤¾à¤¥ à¤¬à¥ˆà¤ à¤•à¤° à¤ªà¤¾à¤°à¤‚à¤ªà¤°à¤¿à¤• à¤²à¤•à¤¡à¤¼à¥€ à¤•à¥‡ à¤¸à¤¾à¤‚à¤šà¥‹à¤‚ à¤ªà¤° à¤…à¤ªà¤¨à¥‡ à¤¹à¤¾à¤¥à¥‹à¤‚ à¤¸à¥‡ à¤…à¤¸à¤²à¥€ à¤•à¥‹à¤²à¥à¤¹à¤¾à¤ªà¥à¤°à¥€ à¤šà¤ªà¥à¤ªà¤² à¤¬à¤¨à¤¾à¤à¤‚à¥¤',
      category: 'à¤šà¤®à¤¡à¤¼à¤¾ à¤¶à¤¿à¤²à¥à¤ª',
      price_inr: 1850,
      duration_mins: 150,
      max_participants: 8,
      lat: 16.7050,
      lng: 74.2433,
      location_name: 'à¤¶à¤¿à¤µà¤¾à¤œà¥€ à¤®à¤¾à¤°à¥à¤•à¥‡à¤Ÿ, à¤•à¥‹à¤²à¥à¤¹à¤¾à¤ªà¥à¤°',
      district: 'à¤•à¥‹à¤²à¥à¤¹à¤¾à¤ªà¥à¤°',
      state: 'à¤®à¤¹à¤¾à¤°à¤¾à¤·à¥à¤Ÿà¥à¤°',
      cover_image: '/assets/images/Home%20page/Kolhapuri_Chappals_in_roadside_shop_in_Kolhapur3.jpeg',
      odop_tag: 'ODOP-MH-à¤•à¥‹à¤²à¥à¤¹à¤¾à¤ªà¥à¤°à¥€-à¤šà¤ªà¥à¤ªà¤²',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_chanderi_01',
      artisan_id: 'art_chanderi_01',
      artisan_name: 'à¤•à¤®à¤²à¤¾ à¤¬à¤¾à¤ˆ',
      artisan_avatar: '/assets/images/01-Hero/Chanderi_Craft_Village_â€“_Traditional_Weaving_and_Handicrafts_in_Madhya_Pradesh_01.jpg',
      trust_score: 97,
      title: 'à¤¶à¤¾à¤¹à¥€ à¤šà¤‚à¤¦à¥‡à¤°à¥€ à¤°à¥‡à¤¶à¤® à¤—à¤¡à¥à¤¢à¤¾-à¤•à¤°à¤˜à¤¾ à¤¬à¥à¤¨à¤¾à¤ˆ à¤”à¤° à¤œà¤°à¥€ à¤•à¤¾à¤°à¥à¤¯à¤¶à¤¾à¤²à¤¾',
      description: '700 à¤¸à¤¾à¤² à¤ªà¥à¤°à¤¾à¤¨à¥€ à¤¬à¥à¤‚à¤¦à¥‡à¤²à¤–à¤‚à¤¡à¥€ à¤¬à¥à¤¨à¤¾à¤ˆ à¤ªà¤°à¤‚à¤ªà¤°à¤¾ à¤•à¤¾ à¤…à¤¨à¥à¤­à¤µ à¤²à¥‡à¤‚à¥¤ à¤ªà¤¾à¤°à¤‚à¤ªà¤°à¤¿à¤• à¤—à¤¡à¥à¤¢à¤¾-à¤•à¤°à¤˜à¥‡ à¤ªà¤° à¤¶à¥à¤¦à¥à¤§ à¤¶à¤¹à¤¤à¥‚à¤¤ à¤°à¥‡à¤¶à¤® à¤”à¤° à¤¸à¥‹à¤¨à¥‡ à¤•à¥€ à¤œà¤°à¥€ à¤¸à¥‡ à¤®à¥‹à¤° à¤à¤µà¤‚ à¤•à¤®à¤² à¤•à¥€ à¤¬à¥‚à¤Ÿà¥€ à¤¬à¥à¤¨à¤¨à¤¾ à¤¸à¥€à¤–à¥‡à¤‚à¥¤',
      category: 'à¤¹à¤¥à¤•à¤°à¤˜à¤¾',
      price_inr: 2200,
      duration_mins: 180,
      max_participants: 6,
      lat: 24.7120,
      lng: 78.1380,
      location_name: 'à¤ªà¥à¤°à¤¾à¤£à¤ªà¥à¤° à¤•à¥à¤°à¤¾à¤«à¥à¤Ÿ à¤µà¤¿à¤²à¥‡à¤œ, à¤šà¤‚à¤¦à¥‡à¤°à¥€',
      district: 'à¤…à¤¶à¥‹à¤•à¤¨à¤—à¤°',
      state: 'à¤®à¤§à¥à¤¯ à¤ªà¥à¤°à¤¦à¥‡à¤¶',
      cover_image: '/assets/images/01-Hero/Chanderi_Craft_Village_â€“_Traditional_Weaving_and_Handicrafts_in_Madhya_Pradesh_01.jpg',
      odop_tag: 'ODOP-MP-à¤šà¤‚à¤¦à¥‡à¤°à¥€-à¤¸à¤¿à¤²à¥à¤•',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_majuli_01',
      artisan_id: 'art_majuli_01',
      artisan_name: 'à¤¹à¥‡à¤®à¤‚à¤¤ à¤¬à¥‹à¤°à¤¾',
      artisan_avatar: '/assets/images/04-Bamboo-Cane/Innovative_Bamboo_Crafts_of_Assam.jpg',
      trust_score: 96,
      title: 'à¤®à¤¾à¤œà¥à¤²à¥€ à¤¨à¤µ-à¤µà¥ˆà¤·à¥à¤£à¤µ à¤®à¥à¤–à¥Œà¤Ÿà¤¾ à¤”à¤° à¤¬à¤¾à¤‚à¤¸ à¤¶à¤¿à¤²à¥à¤ª à¤®à¤¾à¤¸à¥à¤Ÿà¤°à¤•à¥à¤²à¤¾à¤¸',
      description: 'à¤¬à¥à¤°à¤¹à¥à¤®à¤ªà¥à¤¤à¥à¤° à¤¨à¤¦à¥€ à¤•à¥€ à¤—à¤¾à¤¦ à¤®à¤¿à¤Ÿà¥à¤Ÿà¥€, à¤—à¤¾à¤¯ à¤•à¥‡ à¤—à¥‹à¤¬à¤° à¤”à¤° à¤¬à¤¾à¤‚à¤¸ à¤•à¥€ à¤–à¤ªà¤šà¥à¤šà¤¿à¤¯à¥‹à¤‚ à¤¸à¥‡ 500 à¤¸à¤¾à¤² à¤ªà¥à¤°à¤¾à¤¨à¥€ à¤®à¥à¤–à¥Œà¤Ÿà¤¾ à¤¨à¤¿à¤°à¥à¤®à¤¾à¤£ à¤•à¤²à¤¾ à¤¸à¥€à¤–à¥‡à¤‚à¥¤',
      category: 'à¤¬à¤¾à¤‚à¤¸ à¤à¤µà¤‚ à¤¬à¥‡à¤‚à¤¤ à¤¶à¤¿à¤²à¥à¤ª',
      price_inr: 1950,
      duration_mins: 180,
      max_participants: 8,
      lat: 26.9500,
      lng: 94.2167,
      location_name: 'à¤¸à¤¾à¤®à¤—à¥à¤°à¥€ à¤¸à¤¤à¥à¤°, à¤®à¤¾à¤œà¥à¤²à¥€ à¤¦à¥à¤µà¥€à¤ª',
      district: 'à¤®à¤¾à¤œà¥à¤²à¥€',
      state: 'à¤…à¤¸à¤®',
      cover_image: '/assets/images/04-Bamboo-Cane/Innovative_Bamboo_Crafts_of_Assam.jpg',
      odop_tag: 'ODOP-AS-à¤®à¤¾à¤œà¥à¤²à¥€-à¤®à¥à¤–à¥Œà¤Ÿà¤¾',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_srinagar_01',
      artisan_id: 'art_srinagar_01',
      artisan_name: 'à¤—à¥à¤²à¤¾à¤® à¤®à¥‹à¤¹à¤®à¥à¤®à¤¦ à¤œà¤°à¤—à¤°',
      artisan_avatar: '/assets/images/05-Wood-Pottery/Kashmiri_Woodcarving_And_Paper_machÃ©.jpg',
      trust_score: 99,
      title: 'à¤•à¤¶à¥à¤®à¥€à¤°à¥€ à¤…à¤–à¤°à¥‹à¤Ÿ à¤²à¤•à¤¡à¤¼à¥€ 3D à¤¨à¤•à¥à¤•à¤¾à¤¶à¥€ à¤”à¤° à¤šà¤¿à¤¨à¤¾à¤° à¤¡à¤¿à¤œà¤¼à¤¾à¤‡à¤¨ à¤®à¤¾à¤¸à¥à¤Ÿà¤°à¤•à¥à¤²à¤¾à¤¸',
      description: 'à¤ªà¥à¤°à¤¾à¤¨à¥‡ à¤¶à¥à¤°à¥€à¤¨à¤—à¤° à¤•à¥‡ à¤à¤¤à¤¿à¤¹à¤¾à¤¸à¤¿à¤• à¤œà¤¾à¤¦à¥€à¤¬à¤² à¤®à¥‡à¤‚ 4 à¤¸à¤¾à¤² à¤ªà¤•à¥€ à¤…à¤–à¤°à¥‹à¤Ÿ à¤•à¥€ à¤²à¤•à¤¡à¤¼à¥€ à¤ªà¤° à¤¬à¤¾à¤°à¥€à¤• à¤›à¥‡à¤¨à¥€ à¤¸à¥‡ à¤šà¤¿à¤¨à¤¾à¤° à¤•à¥‡ à¤ªà¤¤à¥à¤¤à¥‹à¤‚ à¤•à¥€ à¤¨à¤•à¥à¤•à¤¾à¤¶à¥€ à¤¸à¥€à¤–à¥‡à¤‚à¥¤',
      category: 'à¤•à¤¾à¤·à¥à¤  à¤¶à¤¿à¤²à¥à¤ª',
      price_inr: 2500,
      duration_mins: 180,
      max_participants: 6,
      lat: 34.0837,
      lng: 74.7973,
      location_name: 'à¤œà¤¾à¤¦à¥€à¤¬à¤², à¤ªà¥à¤°à¤¾à¤¨à¤¾ à¤¶à¥à¤°à¥€à¤¨à¤—à¤°',
      district: 'à¤¶à¥à¤°à¥€à¤¨à¤—à¤°',
      state: 'à¤œà¤®à¥à¤®à¥‚ à¤”à¤° à¤•à¤¶à¥à¤®à¥€à¤°',
      cover_image: '/assets/images/05-Wood-Pottery/Kashmiri_Woodcarving_And_Paper_machÃ©.jpg',
      odop_tag: 'ODOP-JK-à¤…à¤–à¤°à¥‹à¤Ÿ-à¤²à¤•à¤¡à¤¼à¥€',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_bishnupur_01',
      artisan_id: 'art_bishnupur_01',
      artisan_name: 'à¤¸à¥à¤­à¤¾à¤· à¤•à¥à¤‚à¤­à¤•à¤¾à¤°',
      artisan_avatar: '/assets/images/05-Wood-Pottery/Artisan_decorating_ceramic_plate.jpg',
      trust_score: 96,
      title: 'à¤¬à¤¾à¤‚à¤•à¥à¤¡à¤¼à¤¾ à¤Ÿà¥‡à¤°à¤¾à¤•à¥‹à¤Ÿà¤¾ à¤˜à¥‹à¤¡à¤¼à¤¾ à¤”à¤° à¤®à¤‚à¤¦à¤¿à¤° à¤Ÿà¤¾à¤‡à¤² à¤®à¥‚à¤°à¥à¤¤à¤¿à¤•à¤²à¤¾ à¤•à¤¾à¤°à¥à¤¯à¤¶à¤¾à¤²à¤¾',
      description: 'à¤•à¥à¤®à¥à¤¹à¤¾à¤° à¤•à¥‡ à¤šà¤¾à¤• à¤ªà¤° à¤ªà¥à¤°à¤¸à¤¿à¤¦à¥à¤§ à¤¬à¤¾à¤‚à¤•à¥à¤¡à¤¼à¤¾ à¤˜à¥‹à¤¡à¤¼à¥‡ à¤•à¥‹ à¤ªà¤¾à¤‚à¤š à¤–à¥‹à¤–à¤²à¥‡ à¤¹à¤¿à¤¸à¥à¤¸à¥‹à¤‚ à¤®à¥‡à¤‚ à¤¢à¤¾à¤²à¤¨à¤¾ à¤”à¤° à¤ªà¤¾à¤°à¤‚à¤ªà¤°à¤¿à¤• à¤²à¤•à¤¡à¤¼à¥€ à¤•à¥€ à¤­à¤Ÿà¥à¤Ÿà¥€ à¤®à¥‡à¤‚ à¤ªà¤•à¤¾à¤¨à¤¾ à¤¸à¥€à¤–à¥‡à¤‚à¥¤',
      category: 'à¤Ÿà¥‡à¤°à¤¾à¤•à¥‹à¤Ÿà¤¾ à¤®à¤¿à¤Ÿà¥à¤Ÿà¥€ à¤¶à¤¿à¤²à¥à¤ª',
      price_inr: 1450,
      duration_mins: 150,
      max_participants: 8,
      lat: 23.0760,
      lng: 87.3190,
      location_name: 'à¤ªà¤‚à¤šà¤®à¥à¤°à¤¾ à¤—à¤¾à¤‚à¤µ, à¤¬à¤¾à¤‚à¤•à¥à¤¡à¤¼à¤¾',
      district: 'à¤¬à¤¾à¤‚à¤•à¥à¤¡à¤¼à¤¾',
      state: 'à¤ªà¤¶à¥à¤šà¤¿à¤® à¤¬à¤‚à¤—à¤¾à¤²',
      cover_image: '/assets/images/05-Wood-Pottery/Artisan_decorating_ceramic_plate.jpg',
      odop_tag: 'ODOP-WB-à¤¬à¤¾à¤‚à¤•à¥à¤¡à¤¼à¤¾-à¤˜à¥‹à¤¡à¤¼à¤¾',
      women_friendly: true,
      elderly_friendly: true
    }
  ],

  mr: [
    {
      id: 'exp_kolhapur_01',
      artisan_id: 'art_kolhapur_01',
      artisan_name: 'à¤¸à¤‚à¤¤à¥‹à¤· à¤•à¤¾à¤‚à¤¬à¤³à¥‡',
      artisan_avatar: '/assets/images/Home%20page/Kolhapuri_Chappals_in_roadside_shop_in_Kolhapur3.jpeg',
      trust_score: 98,
      title: 'à¤…à¤¸à¥à¤¸à¤² à¤•à¥‹à¤²à¥à¤¹à¤¾à¤ªà¥à¤°à¥€ à¤šà¤ªà¥à¤ªà¤² à¤¹à¤¸à¥à¤¤à¤•à¤²à¤¾ à¤ªà¥à¤°à¤¤à¥à¤¯à¤•à¥à¤· à¤•à¤¾à¤°à¥à¤¯à¤¶à¤¾à¤³à¤¾',
      description: 'à¤¬à¤¾à¤­à¤³à¥€à¤šà¥€ à¤¸à¤¾à¤² à¤†à¤£à¤¿ à¤¨à¥ˆà¤¸à¤°à¥à¤—à¤¿à¤• à¤µà¤¨à¤¸à¥à¤ªà¤¤à¥€ à¤ªà¤¦à¥à¤§à¤¤à¥€à¤¨à¥‡ à¤šà¤¾à¤®à¤¡à¥‡ à¤ªà¥à¤°à¤•à¥à¤°à¤¿à¤¯à¤¾ à¤¶à¤¿à¤•à¥‚à¤¨ à¤¸à¥à¤µà¤¤à¤ƒà¤šà¥à¤¯à¤¾ à¤¹à¤¾à¤¤à¤¾à¤¨à¥‡ à¤…à¤¸à¥à¤¸à¤² à¤•à¥‹à¤²à¥à¤¹à¤¾à¤ªà¥à¤°à¥€ à¤šà¤ªà¥à¤ªà¤² à¤¤à¤¯à¤¾à¤° à¤•à¤°à¤¾.',
      category: 'à¤šà¤¾à¤®à¤¡à¥‡ à¤¹à¤¸à¥à¤¤à¤•à¤²à¤¾',
      price_inr: 1850,
      duration_mins: 150,
      max_participants: 8,
      lat: 16.7050,
      lng: 74.2433,
      location_name: 'à¤¶à¤¿à¤µà¤¾à¤œà¥€ à¤®à¤¾à¤°à¥à¤•à¥‡à¤Ÿ, à¤•à¥‹à¤²à¥à¤¹à¤¾à¤ªà¥‚à¤°',
      district: 'à¤•à¥‹à¤²à¥à¤¹à¤¾à¤ªà¥‚à¤°',
      state: 'à¤®à¤¹à¤¾à¤°à¤¾à¤·à¥à¤Ÿà¥à¤°',
      cover_image: '/assets/images/Home%20page/Kolhapuri_Chappals_in_roadside_shop_in_Kolhapur3.jpeg',
      odop_tag: 'ODOP-MH-à¤•à¥‹à¤²à¥à¤¹à¤¾à¤ªà¥‚à¤°-à¤šà¤ªà¥à¤ªà¤²',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_chanderi_01',
      artisan_id: 'art_chanderi_01',
      artisan_name: 'à¤•à¤®à¤²à¤¾ à¤¬à¤¾à¤ˆ',
      artisan_avatar: '/assets/images/01-Hero/Chanderi_Craft_Village_â€“_Traditional_Weaving_and_Handicrafts_in_Madhya_Pradesh_01.jpg',
      trust_score: 97,
      title: 'à¤¶à¤¾à¤¹à¥€ à¤šà¤‚à¤¦à¥‡à¤°à¥€ à¤°à¥‡à¤¶à¤®à¥€ à¤¹à¤¾à¤¤à¤®à¤¾à¤— à¤µà¤¿à¤£à¤•à¤¾à¤® à¤•à¤¾à¤°à¥à¤¯à¤¶à¤¾à¤³à¤¾',
      description: 'à¤ªà¤¾à¤°à¤‚à¤ªà¤°à¤¿à¤• à¤–à¤¡à¥à¤¡à¤¾ à¤¹à¤¾à¤¤à¤®à¤¾à¤—à¤¾à¤µà¤° à¤¬à¤¸à¥‚à¤¨ à¤…à¤¸à¥à¤¸à¤² à¤šà¤‚à¤¦à¥‡à¤°à¥€ à¤°à¥‡à¤¶à¥€à¤® à¤†à¤£à¤¿ à¤œà¤°à¥€ à¤µà¤¿à¤£à¤•à¤¾à¤®à¤¾à¤šà¤¾ à¤¥à¥‡à¤Ÿ à¤…à¤¨à¥à¤­à¤µ à¤˜à¥à¤¯à¤¾.',
      category: 'à¤¹à¤¾à¤¤à¤®à¤¾à¤—',
      price_inr: 2200,
      duration_mins: 180,
      max_participants: 6,
      lat: 24.7120,
      lng: 78.1380,
      location_name: 'à¤ªà¥à¤°à¤¾à¤£à¤ªà¥‚à¤°, à¤šà¤‚à¤¦à¥‡à¤°à¥€',
      district: 'à¤…à¤¶à¥‹à¤•à¤¨à¤—à¤°',
      state: 'à¤®à¤§à¥à¤¯ à¤ªà¥à¤°à¤¦à¥‡à¤¶',
      cover_image: '/assets/images/01-Hero/Chanderi_Craft_Village_â€“_Traditional_Weaving_and_Handicrafts_in_Madhya_Pradesh_01.jpg',
      odop_tag: 'ODOP-MP-à¤šà¤‚à¤¦à¥‡à¤°à¥€-à¤°à¥‡à¤¶à¥€à¤®',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_majuli_01',
      artisan_id: 'art_majuli_01',
      artisan_name: 'à¤¹à¥‡à¤®à¤‚à¤¤ à¤¬à¥‹à¤°à¤¾',
      artisan_avatar: '/assets/images/04-Bamboo-Cane/Innovative_Bamboo_Crafts_of_Assam.jpg',
      trust_score: 96,
      title: 'à¤®à¤¾à¤œà¥à¤²à¥€ à¤¨à¤µ-à¤µà¥ˆà¤·à¥à¤£à¤µ à¤¬à¤¾à¤‚à¤¬à¥‚ à¤®à¥à¤–à¤µà¤Ÿà¤¾ à¤•à¤¾à¤°à¥à¤¯à¤¶à¤¾à¤³à¤¾',
      description: 'à¤¬à¥à¤°à¤¹à¥à¤®à¤ªà¥à¤¤à¥à¤°à¤¾ à¤¨à¤¦à¥€à¤•à¤¾à¤ à¤šà¥à¤¯à¤¾ à¤®à¤¾à¤¤à¥€à¤¤à¥‚à¤¨ à¤†à¤£à¤¿ à¤¬à¤¾à¤‚à¤¬à¥‚à¤šà¥à¤¯à¤¾ à¤•à¤¾à¤®à¤Ÿà¥à¤¯à¤¾à¤‚à¤®à¤§à¥‚à¤¨ à¤ªà¤¾à¤°à¤‚à¤ªà¤¾à¤°à¤¿à¤• à¤®à¥à¤–à¤µà¤Ÿà¤¾ à¤¬à¤¨à¤µà¤£à¥à¤¯à¤¾à¤šà¥€ à¥«à¥¦à¥¦ à¤µà¤°à¥à¤·à¤¾à¤‚à¤šà¥€ à¤•à¤²à¤¾ à¤¶à¤¿à¤•à¤¾.',
      category: 'à¤¬à¤¾à¤‚à¤¬à¥‚ à¤¹à¤¸à¥à¤¤à¤•à¤²à¤¾',
      price_inr: 1950,
      duration_mins: 180,
      max_participants: 8,
      lat: 26.9500,
      lng: 94.2167,
      location_name: 'à¤¸à¤¾à¤®à¤—à¥à¤°à¥€ à¤¸à¤¤à¥à¤°, à¤®à¤¾à¤œà¥à¤²à¥€ à¤¬à¥‡à¤Ÿ',
      district: 'à¤®à¤¾à¤œà¥à¤²à¥€',
      state: 'à¤†à¤¸à¤¾à¤®',
      cover_image: '/assets/images/04-Bamboo-Cane/Innovative_Bamboo_Crafts_of_Assam.jpg',
      odop_tag: 'ODOP-AS-à¤®à¤¾à¤œà¥à¤²à¥€-à¤®à¥à¤–à¤µà¤Ÿà¥‡',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_srinagar_01',
      artisan_id: 'art_srinagar_01',
      artisan_name: 'à¤—à¥à¤²à¤¾à¤® à¤®à¥‹à¤¹à¤®à¥à¤®à¤¦ à¤à¤°à¤—à¤°',
      artisan_avatar: '/assets/images/05-Wood-Pottery/Kashmiri_Woodcarving_And_Paper_machÃ©.jpg',
      trust_score: 99,
      title: 'à¤•à¤¾à¤¶à¥à¤®à¤¿à¤°à¥€ à¤…à¤•à¥à¤°à¥‹à¤¡ à¤²à¤¾à¤•à¥‚à¤¡ à¤•à¥‹à¤°à¥€à¤µ à¤•à¤¾à¤® à¤•à¤¾à¤°à¥à¤¯à¤¶à¤¾à¤³à¤¾',
      description: 'à¤¶à¥à¤°à¥€à¤¨à¤—à¤°à¤šà¥à¤¯à¤¾ à¤œà¥à¤¨à¥à¤¯à¤¾ à¤¶à¤¹à¤°à¤¾à¤¤ à¤…à¤•à¥à¤°à¥‹à¤¡à¤¾à¤šà¥à¤¯à¤¾ à¤²à¤¾à¤•à¤¡à¤¾à¤µà¤° à¤šà¤¿à¤¨à¤¾à¤° à¤ªà¤¾à¤¨à¤¾à¤‚à¤šà¥‡ à¤¤à¥à¤°à¤¿à¤®à¤¿à¤¤à¥€à¤¯ à¤•à¥‹à¤°à¥€à¤µ à¤•à¤¾à¤® à¤¶à¤¿à¤•à¤¾.',
      category: 'à¤²à¤¾à¤•à¥‚à¤¡ à¤•à¥‹à¤°à¥€à¤µ à¤•à¤¾à¤®',
      price_inr: 2500,
      duration_mins: 180,
      max_participants: 6,
      lat: 34.0837,
      lng: 74.7973,
      location_name: 'à¤œà¤¾à¤¦à¥€à¤¬à¤², à¤¶à¥à¤°à¥€à¤¨à¤—à¤°',
      district: 'à¤¶à¥à¤°à¥€à¤¨à¤—à¤°',
      state: 'à¤œà¤®à¥à¤®à¥‚ à¤†à¤£à¤¿ à¤•à¤¾à¤¶à¥à¤®à¥€à¤°',
      cover_image: '/assets/images/05-Wood-Pottery/Kashmiri_Woodcarving_And_Paper_machÃ©.jpg',
      odop_tag: 'ODOP-JK-à¤…à¤•à¥à¤°à¥‹à¤¡-à¤²à¤¾à¤•à¥‚à¤¡',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_bishnupur_01',
      artisan_id: 'art_bishnupur_01',
      artisan_name: 'à¤¸à¥à¤­à¤¾à¤· à¤•à¥à¤‚à¤­à¤¾à¤°',
      artisan_avatar: '/assets/images/05-Wood-Pottery/Artisan_decorating_ceramic_plate.jpg',
      trust_score: 96,
      title: 'à¤¬à¤¾à¤‚à¤•à¥à¤¡à¤¾ à¤Ÿà¥‡à¤°à¤¾à¤•à¥‹à¤Ÿà¤¾ à¤®à¤¾à¤¤à¥€à¤•à¤¾à¤® à¤†à¤£à¤¿ à¤®à¤‚à¤¦à¤¿à¤° à¤¶à¤¿à¤²à¥à¤ª à¤•à¤¾à¤°à¥à¤¯à¤¶à¤¾à¤³à¤¾',
      description: 'à¤šà¤¾à¤•à¤¾à¤µà¤° à¤ªà¥à¤°à¤¸à¤¿à¤¦à¥à¤§ à¤¬à¤¾à¤‚à¤•à¥à¤¡à¤¾ à¤˜à¥‹à¤¡à¤¾ à¤˜à¤¡à¤µà¥‚à¤¨ à¤²à¤¾à¤•à¤¡à¤¾à¤šà¥à¤¯à¤¾ à¤­à¤Ÿà¥à¤Ÿà¥€à¤¤ à¤­à¤¾à¤œà¤£à¥à¤¯à¤¾à¤šà¥‡ à¤ªà¤¾à¤°à¤‚à¤ªà¤°à¤¿à¤• à¤¤à¤‚à¤¤à¥à¤° à¤¶à¤¿à¤•à¤¾.',
      category: 'à¤Ÿà¥‡à¤°à¤¾à¤•à¥‹à¤Ÿà¤¾ à¤®à¤¾à¤¤à¥€à¤•à¤¾à¤®',
      price_inr: 1450,
      duration_mins: 150,
      max_participants: 8,
      lat: 23.0760,
      lng: 87.3190,
      location_name: 'à¤ªà¤‚à¤šà¤®à¥à¤°à¤¾, à¤¬à¤¾à¤‚à¤•à¥à¤¡à¤¾',
      district: 'à¤¬à¤¾à¤‚à¤•à¥à¤¡à¤¾',
      state: 'à¤ªà¤¶à¥à¤šà¤¿à¤® à¤¬à¤‚à¤—à¤¾à¤²',
      cover_image: '/assets/images/05-Wood-Pottery/Artisan_decorating_ceramic_plate.jpg',
      odop_tag: 'ODOP-WB-à¤¬à¤¾à¤‚à¤•à¥à¤¡à¤¾-à¤˜à¥‹à¤¡à¤¾',
      women_friendly: true,
      elderly_friendly: true
    }
  ],

  ta: [
    {
      id: 'exp_kolhapur_01',
      artisan_id: 'art_kolhapur_01',
      artisan_name: 'à®šà®¨à¯à®¤à¯‹à®·à¯ à®•à®¾à®®à¯à®ªà¯à®³à¯‡',
      artisan_avatar: '/assets/images/Home%20page/Kolhapuri_Chappals_in_roadside_shop_in_Kolhapur3.jpeg',
      trust_score: 98,
      title: 'à®ªà®¾à®°à®®à¯à®ªà®°à®¿à®¯ à®•à¯‹à®²à®¾à®ªà¯à®ªà¯‚à®°à®¿ à®šà¯†à®°à¯à®ªà¯à®ªà¯ à®•à¯ˆà®µà®¿à®©à¯ˆà®ªà¯ à®ªà®¯à®¿à®±à¯à®šà®¿',
      description: 'à®ªà®¾à®°à®®à¯à®ªà®°à®¿à®¯ à®®à¯à®±à¯ˆà®¯à®¿à®²à¯ à®¤à¯‹à®²à¯ à®ªà®¤à®©à®¿à®Ÿà¯à®¤à®²à¯ à®®à®±à¯à®±à¯à®®à¯ à®•à¯ˆà®µà®¿à®©à¯ˆ à®šà¯†à®°à¯à®ªà¯à®ªà¯ à®¤à®¯à®¾à®°à®¿à®•à¯à®•à¯à®®à¯ à®ªà®¯à®¿à®±à¯à®šà®¿.',
      category: 'à®¤à¯‹à®²à¯ à®•à¯ˆà®µà®¿à®©à¯ˆ',
      price_inr: 1850,
      duration_mins: 150,
      max_participants: 8,
      lat: 16.7050,
      lng: 74.2433,
      location_name: 'à®šà®¿à®µà®¾à®œà®¿ à®®à®¾à®°à¯à®•à¯à®•à¯†à®Ÿà¯, à®•à¯‹à®²à®¾à®ªà¯à®ªà¯‚à®°à¯',
      district: 'à®•à¯‹à®²à®¾à®ªà¯à®ªà¯‚à®°à¯',
      state: 'à®®à®•à®¾à®°à®¾à®·à¯à®Ÿà®¿à®°à®¾',
      cover_image: '/assets/images/Home%20page/Kolhapuri_Chappals_in_roadside_shop_in_Kolhapur3.jpeg',
      odop_tag: 'ODOP-MH-LEATHER',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_chanderi_01',
      artisan_id: 'art_chanderi_01',
      artisan_name: 'à®•à®®à®²à®¾ à®ªà®¾à®¯à¯',
      artisan_avatar: '/assets/images/01-Hero/Chanderi_Craft_Village_â€“_Traditional_Weaving_and_Handicrafts_in_Madhya_Pradesh_01.jpg',
      trust_score: 97,
      title: 'à®°à®¾à®œà®•à®®à¯à®ªà¯€à®° à®šà®¨à¯à®¤à¯‡à®°à®¿ à®ªà®Ÿà¯à®Ÿà¯ à®¨à¯†à®šà®µà¯à®ªà¯ à®ªà®¯à®¿à®±à¯à®šà®¿',
      description: 'à®¤à¯‚à®¯ à®®à®²à¯à®ªà¯†à®°à®¿ à®ªà®Ÿà¯à®Ÿà¯ à®®à®±à¯à®±à¯à®®à¯ à®¤à®™à¯à®• à®œà®°à®¿à®•à¯ˆ à®•à¯Šà®£à¯à®Ÿà¯ à®¨à¯†à®šà®µà¯ à®šà¯†à®¯à¯à®¯à¯à®®à¯ à®¨à¯‡à®°à®Ÿà®¿ à®ªà®¯à®¿à®±à¯à®šà®¿.',
      category: 'à®•à¯ˆà®¤à¯à®¤à®±à®¿',
      price_inr: 2200,
      duration_mins: 180,
      max_participants: 6,
      lat: 24.7120,
      lng: 78.1380,
      location_name: 'à®ªà®¿à®°à®¾à®©à¯à®ªà¯‚à®°à¯, à®šà®¨à¯à®¤à¯‡à®°à®¿',
      district: 'à®…à®šà¯‹à®•à¯à®¨à®•à®°à¯',
      state: 'à®®à®¤à¯à®¤à®¿à®¯à®ªà¯ à®ªà®¿à®°à®¤à¯‡à®šà®®à¯',
      cover_image: '/assets/images/01-Hero/Chanderi_Craft_Village_â€“_Traditional_Weaving_and_Handicrafts_in_Madhya_Pradesh_01.jpg',
      odop_tag: 'ODOP-MP-SILK',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_majuli_01',
      artisan_id: 'art_majuli_01',
      artisan_name: 'à®¹à¯‡à®®à®¨à¯à®¤ à®ªà¯‹à®°à®¾',
      artisan_avatar: '/assets/images/04-Bamboo-Cane/Innovative_Bamboo_Crafts_of_Assam.jpg',
      trust_score: 96,
      title: 'à®®à®œà¯‚à®²à®¿ à®®à¯‚à®™à¯à®•à®¿à®²à¯ à®®à¯à®•à®®à¯‚à®Ÿà®¿ à®•à¯ˆà®µà®¿à®©à¯ˆà®ªà¯ à®ªà®¯à®¿à®±à¯à®šà®¿',
      description: 'à®ªà®¿à®°à®®à¯à®®à®ªà¯à®¤à¯à®¤à®¿à®°à®¾ à®•à®³à®¿à®®à®£à¯ à®®à®±à¯à®±à¯à®®à¯ à®®à¯‚à®™à¯à®•à®¿à®²à¯ à®•à¯Šà®£à¯à®Ÿà¯ à®ªà®¾à®°à®®à¯à®ªà®°à®¿à®¯ à®®à¯à®•à®®à¯‚à®Ÿà®¿ à®¤à®¯à®¾à®°à®¿à®¤à¯à®¤à®²à¯.',
      category: 'à®®à¯‚à®™à¯à®•à®¿à®²à¯ à®•à¯ˆà®µà®¿à®©à¯ˆ',
      price_inr: 1950,
      duration_mins: 180,
      max_participants: 8,
      lat: 26.9500,
      lng: 94.2167,
      location_name: 'à®®à®œà¯‚à®²à®¿ à®¤à¯€à®µà¯',
      district: 'à®®à®œà¯‚à®²à®¿',
      state: 'à®…à®šà®¾à®®à¯',
      cover_image: '/assets/images/04-Bamboo-Cane/Innovative_Bamboo_Crafts_of_Assam.jpg',
      odop_tag: 'ODOP-AS-MASKS',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_srinagar_01',
      artisan_id: 'art_srinagar_01',
      artisan_name: 'à®•à¯à®²à®¾à®®à¯ à®®à¯à®•à®®à®¤à¯ à®œà®°à¯à®•à®°à¯',
      artisan_avatar: '/assets/images/05-Wood-Pottery/Kashmiri_Woodcarving_And_Paper_machÃ©.jpg',
      trust_score: 99,
      title: 'à®•à®¾à®·à¯à®®à¯€à®°à¯ à®µà®¾à®¤à¯à®®à¯ˆ à®®à®°à®šà¯ à®šà¯†à®¤à¯à®•à¯à®•à®²à¯ à®ªà®¯à®¿à®±à¯à®šà®¿',
      description: 'à®ªà®´à¯ˆà®¯ à®¸à¯à®°à¯€à®¨à®•à®°à®¿à®²à¯ à®ªà®¾à®°à®®à¯à®ªà®°à®¿à®¯ à®µà®¾à®¤à¯à®®à¯ˆ à®®à®°à®¤à¯à®¤à®¿à®²à¯ à®ªà¯‚ à®µà¯‡à®²à¯ˆà®ªà¯à®ªà®¾à®Ÿà¯à®•à®³à¯ à®šà¯†à®¤à¯à®•à¯à®•à¯à®®à¯ à®•à®²à¯ˆ.',
      category: 'à®®à®°à®šà¯ à®šà¯†à®¤à¯à®•à¯à®•à®²à¯',
      price_inr: 2500,
      duration_mins: 180,
      max_participants: 6,
      lat: 34.0837,
      lng: 74.7973,
      location_name: 'à®¸à¯à®°à¯€à®¨à®•à®°à¯',
      district: 'à®¸à¯à®°à¯€à®¨à®•à®°à¯',
      state: 'à®œà®®à¯à®®à¯ & à®•à®¾à®·à¯à®®à¯€à®°à¯',
      cover_image: '/assets/images/05-Wood-Pottery/Kashmiri_Woodcarving_And_Paper_machÃ©.jpg',
      odop_tag: 'ODOP-JK-WALNUT',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_bishnupur_01',
      artisan_id: 'art_bishnupur_01',
      artisan_name: 'à®šà¯à®ªà®¾à®·à¯ à®•à¯à®®à¯à®ªà®•à®¾à®°à¯',
      artisan_avatar: '/assets/images/05-Wood-Pottery/Artisan_decorating_ceramic_plate.jpg',
      trust_score: 96,
      title: 'à®ªà®¾à®™à¯à®•à¯à®°à®¾ à®šà¯à®Ÿà¯à®®à®£à¯ à®•à¯à®¤à®¿à®°à¯ˆ à®šà®¿à®±à¯à®ªà®•à¯ à®•à®²à¯ˆà®ªà¯ à®ªà®¯à®¿à®±à¯à®šà®¿',
      description: 'à®ªà®¾à®°à®®à¯à®ªà®°à®¿à®¯ à®šà¯à®Ÿà¯à®®à®£à¯ à®•à¯à®¤à®¿à®°à¯ˆ à®®à®±à¯à®±à¯à®®à¯ à®•à¯‹à®µà®¿à®²à¯ à®šà®¿à®±à¯à®ªà®™à¯à®•à®³à¯ à®šà¯†à®¯à¯à®¯à¯à®®à¯ à®•à®²à¯ˆ.',
      category: 'à®šà¯à®Ÿà¯à®®à®£à¯ à®•à¯ˆà®µà®¿à®©à¯ˆ',
      price_inr: 1450,
      duration_mins: 150,
      max_participants: 8,
      lat: 23.0760,
      lng: 87.3190,
      location_name: 'à®ªà®¾à®™à¯à®•à¯à®°à®¾',
      district: 'à®ªà®¾à®™à¯à®•à¯à®°à®¾',
      state: 'à®®à¯‡à®±à¯à®•à¯ à®µà®™à¯à®•à®®à¯',
      cover_image: '/assets/images/05-Wood-Pottery/Artisan_decorating_ceramic_plate.jpg',
      odop_tag: 'ODOP-WB-HORSE',
      women_friendly: true,
      elderly_friendly: true
    }
  ],

  te: [
    {
      id: 'exp_kolhapur_01',
      artisan_id: 'art_kolhapur_01',
      artisan_name: 'à°¸à°‚à°¤à±‹à°·à± à°•à°¾à°‚à°¬à±à°²à±‡',
      artisan_avatar: '/assets/images/Home%20page/Kolhapuri_Chappals_in_roadside_shop_in_Kolhapur3.jpeg',
      trust_score: 98,
      title: 'à°•à±Šà°²à±à°¹à°¾à°ªà±‚à°°à± à°¸à°¾à°‚à°ªà±à°°à°¦à°¾à°¯ à°¤à±‹à°²à± à°šà±†à°ªà±à°ªà±à°² à°µà°°à±à°•à±â€Œà°·à°¾à°ªà±',
      description: 'à°¸à°¹à°œà°¸à°¿à°¦à±à°§à°‚à°—à°¾ à°¤à±‹à°²à±à°¨à± à°¸à°¿à°¦à±à°§à°‚ à°šà±‡à°¸à°¿ à°¸à°‚à°ªà±à°°à°¦à°¾à°¯ à°šà±†à°ªà±à°ªà±à°²à± à°¤à°¯à°¾à°°à± à°šà±‡à°¸à±‡ à°•à°³à°¨à± à°¨à±‡à°°à±à°šà±à°•à±‹à°‚à°¡à°¿.',
      category: 'à°¤à±‹à°²à± à°•à°³',
      price_inr: 1850,
      duration_mins: 150,
      max_participants: 8,
      lat: 16.7050,
      lng: 74.2433,
      location_name: 'à°•à±Šà°²à±à°¹à°¾à°ªà±‚à°°à±',
      district: 'à°•à±Šà°²à±à°¹à°¾à°ªà±‚à°°à±',
      state: 'à°®à°¹à°¾à°°à°¾à°·à±à°Ÿà±à°°',
      cover_image: '/assets/images/Home%20page/Kolhapuri_Chappals_in_roadside_shop_in_Kolhapur3.jpeg',
      odop_tag: 'ODOP-MH-LEATHER',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_chanderi_01',
      artisan_id: 'art_chanderi_01',
      artisan_name: 'à°•à°®à°²à°¾ à°¬à°¾à°¯à°¿',
      artisan_avatar: '/assets/images/01-Hero/Chanderi_Craft_Village_â€“_Traditional_Weaving_and_Handicrafts_in_Madhya_Pradesh_01.jpg',
      trust_score: 97,
      title: 'à°šà°‚à°¦à±‡à°°à°¿ à°ªà°Ÿà±à°Ÿà± à°šà±‡à°¨à±‡à°¤ & à°œà°°à±€ à°¨à±‡à°¤ à°•à°³à°¾à°¶à°¾à°²',
      description: 'à°¸à±à°µà°šà±à°›à°®à±ˆà°¨ à°®à°²à±à°¬à°°à±€ à°ªà°Ÿà±à°Ÿà± à°®à°°à°¿à°¯à± à°¬à°‚à°—à°¾à°°à± à°œà°°à±€à°¤à±‹ à°®à°—à±à°—à°‚à°ªà±ˆ à°¨à±‡à°¤ à°¨à±‡à°°à±à°šà±à°•à±‹à°‚à°¡à°¿.',
      category: 'à°šà±‡à°¨à±‡à°¤',
      price_inr: 2200,
      duration_mins: 180,
      max_participants: 6,
      lat: 24.7120,
      lng: 78.1380,
      location_name: 'à°šà°‚à°¦à±‡à°°à°¿',
      district: 'à°…à°¶à±‹à°•à±â€Œà°¨à°—à°°à±',
      state: 'à°®à°§à±à°¯à°ªà±à°°à°¦à±‡à°¶à±',
      cover_image: '/assets/images/01-Hero/Chanderi_Craft_Village_â€“_Traditional_Weaving_and_Handicrafts_in_Madhya_Pradesh_01.jpg',
      odop_tag: 'ODOP-MP-SILK',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_majuli_01',
      artisan_id: 'art_majuli_01',
      artisan_name: 'à°¹à±‡à°®à°‚à°¤ à°¬à±‹à°°à°¾',
      artisan_avatar: '/assets/images/04-Bamboo-Cane/Innovative_Bamboo_Crafts_of_Assam.jpg',
      trust_score: 96,
      title: 'à°®à°œà±à°²à°¿ à°µà±†à°¦à±à°°à± à°®à±à°¸à±à°—à±à°² à°¸à°‚à°ªà±à°°à°¦à°¾à°¯ à°µà°°à±à°•à±â€Œà°·à°¾à°ªà±',
      description: 'à°¬à±à°°à°¹à±à°®à°ªà±à°¤à±à°° à°¨à°¦à°¿ à°®à°Ÿà±à°Ÿà°¿ à°®à°°à°¿à°¯à± à°µà±†à°¦à±à°°à±à°¤à±‹ 500 à°à°³à±à°² à°ªà±à°°à°¾à°¤à°¨ à°®à±à°¸à±à°—à±à°² à°¤à°¯à°¾à°°à±€.',
      category: 'à°µà±†à°¦à±à°°à± à°•à°³',
      price_inr: 1950,
      duration_mins: 180,
      max_participants: 8,
      lat: 26.9500,
      lng: 94.2167,
      location_name: 'à°®à°œà±à°²à°¿ à°¦à±à°µà±€à°ªà°‚',
      district: 'à°®à°œà±à°²à°¿',
      state: 'à°…à°¸à±à°¸à°¾à°‚',
      cover_image: '/assets/images/04-Bamboo-Cane/Innovative_Bamboo_Crafts_of_Assam.jpg',
      odop_tag: 'ODOP-AS-MASKS',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_srinagar_01',
      artisan_id: 'art_srinagar_01',
      artisan_name: 'à°—à±à°²à°¾à°‚ à°®à±Šà°¹à°®à±à°®à°¦à± à°œà°°à±à°—à°°à±',
      artisan_avatar: '/assets/images/05-Wood-Pottery/Kashmiri_Woodcarving_And_Paper_machÃ©.jpg',
      trust_score: 99,
      title: 'à°•à°¾à°¶à±à°®à±€à°°à± à°…à°•à±à°°à±‹à°Ÿà± à°šà±†à°•à±à°• à°šà±†à°•à±à°•à°¡à°¾à°² à°µà°°à±à°•à±â€Œà°·à°¾à°ªà±',
      description: 'à°ªà±à°°à°¾à°¤à°¨ à°¶à±à°°à±€à°¨à°—à°°à±â€Œà°²à±‹ à°…à°•à±à°°à±‹à°Ÿà± à°šà±†à°•à±à°•à°ªà±ˆ à°¸à±à°¨à±à°¨à°¿à°¤à°®à±ˆà°¨ à°šà°¿à°•à±à°•à°Ÿà°¿ à°šà±†à°•à±à°•à°¡à°¾à°² à°¶à°¿à°•à±à°·à°£.',
      category: 'à°šà±†à°•à±à°• à°•à°³',
      price_inr: 2500,
      duration_mins: 180,
      max_participants: 6,
      lat: 34.0837,
      lng: 74.7973,
      location_name: 'à°¶à±à°°à±€à°¨à°—à°°à±',
      district: 'à°¶à±à°°à±€à°¨à°—à°°à±',
      state: 'à°œà°®à±à°®à±‚ & à°•à°¾à°¶à±à°®à±€à°°à±',
      cover_image: '/assets/images/05-Wood-Pottery/Kashmiri_Woodcarving_And_Paper_machÃ©.jpg',
      odop_tag: 'ODOP-JK-WALNUT',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_bishnupur_01',
      artisan_id: 'art_bishnupur_01',
      artisan_name: 'à°¸à±à°­à°¾à°·à± à°•à±à°‚à°­à°•à°¾à°°à±',
      artisan_avatar: '/assets/images/05-Wood-Pottery/Artisan_decorating_ceramic_plate.jpg',
      trust_score: 96,
      title: 'à°¬à°¾à°‚à°•à±à°°à°¾ à°Ÿà±†à°°à±à°°à°•à±‹à°Ÿà°¾ à°—à±à°°à±à°°à°‚ & à°®à°Ÿà±à°Ÿà°¿ à°•à±à°‚à°¡à°² à°µà°°à±à°•à±â€Œà°·à°¾à°ªà±',
      description: 'à°•à±à°®à±à°®à°°à°¿ à°šà°•à±à°°à°‚à°ªà±ˆ à°ªà±à°°à°¸à°¿à°¦à±à°§ à°¬à°¾à°‚à°•à±à°°à°¾ à°—à±à°°à±à°°à°‚ à°¤à°¯à°¾à°°à± à°šà±‡à°¯à°¡à°‚ à°¨à±‡à°°à±à°šà±à°•à±‹à°‚à°¡à°¿.',
      category: 'à°®à°Ÿà±à°Ÿà°¿ à°•à°³',
      price_inr: 1450,
      duration_mins: 150,
      max_participants: 8,
      lat: 23.0760,
      lng: 87.3190,
      location_name: 'à°¬à°¾à°‚à°•à±à°°à°¾',
      district: 'à°¬à°¾à°‚à°•à±à°°à°¾',
      state: 'à°ªà°¶à±à°šà°¿à°® à°¬à±†à°‚à°—à°¾à°²à±',
      cover_image: '/assets/images/05-Wood-Pottery/Artisan_decorating_ceramic_plate.jpg',
      odop_tag: 'ODOP-WB-HORSE',
      women_friendly: true,
      elderly_friendly: true
    }
  ],

  bn: [
    {
      id: 'exp_kolhapur_01',
      artisan_id: 'art_kolhapur_01',
      artisan_name: 'à¦¸à¦¨à§à¦¤à§‹à¦· à¦•à¦¾à¦®à§à¦¬à¦²à§‡',
      artisan_avatar: '/assets/images/Home%20page/Kolhapuri_Chappals_in_roadside_shop_in_Kolhapur3.jpeg',
      trust_score: 98,
      title: 'à¦à¦¤à¦¿à¦¹à§à¦¯à¦¬à¦¾à¦¹à§€ à¦•à§‹à¦²à¦¹à¦¾à¦ªà§à¦°à§€ à¦šà¦Ÿà¦¿ à¦šà¦¾à¦®à¦¡à¦¼à¦¾ à¦¶à¦¿à¦²à§à¦ª à¦•à¦°à§à¦®à¦¶à¦¾à¦²à¦¾',
      description: 'à¦¬à¦¾à¦¬à¦²à¦¾ à¦—à¦¾à¦›à§‡à¦° à¦›à¦¾à¦² à¦¦à¦¿à¦¯à¦¼à§‡ à¦ªà§à¦°à¦¾à¦•à§ƒà¦¤à¦¿à¦• à¦šà¦¾à¦®à¦¡à¦¼à¦¾ à¦ªà§à¦°à¦•à§à¦°à¦¿à¦¯à¦¼à¦¾à¦•à¦°à¦£ à¦“ à¦¹à¦¾à¦¤à§‡ à¦¤à§ˆà¦°à¦¿ à¦•à§‹à¦²à¦¹à¦¾à¦ªà§à¦°à§€ à¦šà¦Ÿà¦¿ à¦¬à¦¾à¦¨à¦¾à¦¨à§‹à¦° à¦ªà§à¦°à¦¶à¦¿à¦•à§à¦·à¦£à¥¤',
      category: 'à¦šà¦¾à¦®à¦¡à¦¼à¦¾ à¦¶à¦¿à¦²à§à¦ª',
      price_inr: 1850,
      duration_mins: 150,
      max_participants: 8,
      lat: 16.7050,
      lng: 74.2433,
      location_name: 'à¦•à§‹à¦²à¦¹à¦¾à¦ªà§à¦°',
      district: 'à¦•à§‹à¦²à¦¹à¦¾à¦ªà§à¦°',
      state: 'à¦®à¦¹à¦¾à¦°à¦¾à¦·à§à¦Ÿà§à¦°',
      cover_image: '/assets/images/Home%20page/Kolhapuri_Chappals_in_roadside_shop_in_Kolhapur3.jpeg',
      odop_tag: 'ODOP-MH-LEATHER',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_chanderi_01',
      artisan_id: 'art_chanderi_01',
      artisan_name: 'à¦•à¦®à¦²à¦¾ à¦¬à¦¾à¦ˆ',
      artisan_avatar: '/assets/images/01-Hero/Chanderi_Craft_Village_â€“_Traditional_Weaving_and_Handicrafts_in_Madhya_Pradesh_01.jpg',
      trust_score: 97,
      title: 'à¦°à¦¾à¦œà¦•à§€à¦¯à¦¼ à¦šà¦¾à¦¨à§à¦¦à§‡à¦°à¦¿ à¦°à§‡à¦¶à¦® à¦¤à¦¾à¦à¦¤ à¦“ à¦œà¦°à¦¿ à¦¬à¦¯à¦¼à¦¨ à¦•à¦°à§à¦®à¦¶à¦¾à¦²à¦¾',
      description: 'à¦à¦¤à¦¿à¦¹à§à¦¯à¦¬à¦¾à¦¹à§€ à¦¤à¦¾à¦à¦¤à§‡ à¦¬à¦¸à§‡ à¦–à¦¾à¦à¦Ÿà¦¿ à¦°à§‡à¦¶à¦® à¦“ à¦¸à§‹à¦¨à¦¾à¦° à¦œà¦°à¦¿ à¦¦à¦¿à¦¯à¦¼à§‡ à¦šà¦¾à¦¨à§à¦¦à§‡à¦°à¦¿ à¦¶à¦¾à¦¡à¦¼à¦¿ à¦¬à¦¯à¦¼à¦¨ à¦¶à¦¿à¦–à§à¦¨à¥¤',
      category: 'à¦¤à¦¾à¦à¦¤ à¦¶à¦¿à¦²à§à¦ª',
      price_inr: 2200,
      duration_mins: 180,
      max_participants: 6,
      lat: 24.7120,
      lng: 78.1380,
      location_name: 'à¦šà¦¾à¦¨à§à¦¦à§‡à¦°à¦¿',
      district: 'à¦…à¦¶à§‹à¦•à¦¨à¦—à¦°',
      state: 'à¦®à¦§à§à¦¯à¦ªà§à¦°à¦¦à§‡à¦¶',
      cover_image: '/assets/images/01-Hero/Chanderi_Craft_Village_â€“_Traditional_Weaving_and_Handicrafts_in_Madhya_Pradesh_01.jpg',
      odop_tag: 'ODOP-MP-SILK',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_majuli_01',
      artisan_id: 'art_majuli_01',
      artisan_name: 'à¦¹à§‡à¦®à¦¨à§à¦¤ à¦¬à¦°à¦¾',
      artisan_avatar: '/assets/images/04-Bamboo-Cane/Innovative_Bamboo_Crafts_of_Assam.jpg',
      trust_score: 96,
      title: 'à¦®à¦¾à¦œà§à¦²à§€ à¦¬à¦¾à¦à¦¶à§‡à¦° à¦®à§à¦–à§‹à¦¶ à¦“ à¦¬à§‡à¦¤ à¦¶à¦¿à¦²à§à¦ª à¦•à¦°à§à¦®à¦¶à¦¾à¦²à¦¾',
      description: 'à¦¬à§à¦°à¦¹à§à¦®à¦ªà§à¦¤à§à¦° à¦¨à¦¦à§‡à¦° à¦ªà¦²à¦¿à¦®à¦¾à¦Ÿà¦¿ à¦“ à¦¬à¦¾à¦à¦¶ à¦¦à¦¿à¦¯à¦¼à§‡ à§«à§¦à§¦ à¦¬à¦›à¦°à§‡à¦° à¦ªà§à¦°à¦¨à§‹ à¦à¦¤à¦¿à¦¹à§à¦¯à¦¬à¦¾à¦¹à§€ à¦®à§à¦–à§‹à¦¶ à¦¤à§ˆà¦°à¦¿à¥¤',
      category: 'à¦¬à¦¾à¦à¦¶ à¦“ à¦¬à§‡à¦¤ à¦¶à¦¿à¦²à§à¦ª',
      price_inr: 1950,
      duration_mins: 180,
      max_participants: 8,
      lat: 26.9500,
      lng: 94.2167,
      location_name: 'à¦®à¦¾à¦œà§à¦²à§€ à¦¦à§à¦¬à§€à¦ª',
      district: 'à¦®à¦¾à¦œà§à¦²à§€',
      state: 'à¦†à¦¸à¦¾à¦®',
      cover_image: '/assets/images/04-Bamboo-Cane/Innovative_Bamboo_Crafts_of_Assam.jpg',
      odop_tag: 'ODOP-AS-MASKS',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_srinagar_01',
      artisan_id: 'art_srinagar_01',
      artisan_name: 'à¦—à§à¦²à¦¾à¦® à¦®à§‹à¦¹à¦¾à¦®à§à¦®à¦¦ à¦œà¦°à¦—à¦°',
      artisan_avatar: '/assets/images/05-Wood-Pottery/Kashmiri_Woodcarving_And_Paper_machÃ©.jpg',
      trust_score: 99,
      title: 'à¦•à¦¾à¦¶à§à¦®à§€à¦°à¦¿ à¦†à¦–à¦°à§‹à¦Ÿ à¦•à¦¾à¦ à§‡à¦° à¦–à§‹à¦¦à¦¾à¦‡ à¦“ à¦šà¦¿à¦¨à¦¾à¦° à¦¨à¦•à¦¶à¦¾ à¦•à¦°à§à¦®à¦¶à¦¾à¦²à¦¾',
      description: 'à¦ªà§à¦°à¦¾à¦¨à§‹ à¦¶à§à¦°à§€à¦¨à¦—à¦°à§‡ à¦†à¦–à¦°à§‹à¦Ÿ à¦•à¦¾à¦ à§‡à¦° à¦‰à¦ªà¦° à¦¸à§‚à¦•à§à¦·à§à¦® à¦šà¦¿à¦¨à¦¾à¦° à¦ªà¦¾à¦¤à¦¾à¦° à¦–à§‹à¦¦à¦¾à¦‡à¦¯à¦¼à§‡à¦° à¦¸à¦°à¦¾à¦¸à¦°à¦¿ à¦ªà§à¦°à¦¶à¦¿à¦•à§à¦·à¦£à¥¤',
      category: 'à¦•à¦¾à¦ à§‡à¦° à¦–à§‹à¦¦à¦¾à¦‡',
      price_inr: 2500,
      duration_mins: 180,
      max_participants: 6,
      lat: 34.0837,
      lng: 74.7973,
      location_name: 'à¦¶à§à¦°à§€à¦¨à¦—à¦°',
      district: 'à¦¶à§à¦°à§€à¦¨à¦—à¦°',
      state: 'à¦œà¦®à§à¦®à§ à¦“ à¦•à¦¾à¦¶à§à¦®à§€à¦°',
      cover_image: '/assets/images/05-Wood-Pottery/Kashmiri_Woodcarving_And_Paper_machÃ©.jpg',
      odop_tag: 'ODOP-JK-WALNUT',
      women_friendly: true,
      elderly_friendly: true
    },
    {
      id: 'exp_bishnupur_01',
      artisan_id: 'art_bishnupur_01',
      artisan_name: 'à¦¸à§à¦­à¦¾à¦· à¦•à§à¦®à§à¦­à¦•à¦¾à¦°',
      artisan_avatar: '/assets/images/05-Wood-Pottery/Artisan_decorating_ceramic_plate.jpg',
      trust_score: 96,
      title: 'à¦¬à¦¿à¦·à§à¦£à§à¦ªà§à¦° à¦¬à¦¾à¦à¦•à§à¦¡à¦¼à¦¾ à¦ªà§‹à¦¡à¦¼à¦¾à¦®à¦¾à¦Ÿà¦¿à¦° à¦˜à§‹à¦¡à¦¼à¦¾ à¦“ à¦®à¦¨à§à¦¦à¦¿à¦° à¦Ÿà§‡à¦°à¦¾à¦•à§‹à¦Ÿà¦¾ à¦•à¦°à§à¦®à¦¶à¦¾à¦²à¦¾',
      description: 'à¦•à§à¦®à§‹à¦°à§‡à¦° à¦šà¦¾à¦•à§‡ à¦¬à¦¿à¦¶à§à¦¬à¦–à§à¦¯à¦¾à¦¤ à¦¬à¦¾à¦à¦•à§à¦¡à¦¼à¦¾à¦° à¦Ÿà§‡à¦°à¦¾à¦•à§‹à¦Ÿà¦¾ à¦˜à§‹à¦¡à¦¼à¦¾ à¦¤à§ˆà¦°à¦¿ à¦“ à¦•à¦¾à¦ à§‡à¦° à¦šà§à¦²à§à¦²à¦¿à¦¤à§‡ à¦ªà§‹à¦¡à¦¼à¦¾à¦¨à§‹à¦° à¦ªà¦¦à§à¦§à¦¤à¦¿ à¦¶à¦¿à¦–à§à¦¨à¥¤',
      category: 'à¦ªà§‹à¦¡à¦¼à¦¾à¦®à¦¾à¦Ÿà¦¿ à¦¶à¦¿à¦²à§à¦ª',
      price_inr: 1450,
      duration_mins: 150,
      max_participants: 8,
      lat: 23.0760,
      lng: 87.3190,
      location_name: 'à¦ªà¦¾à¦à¦šà¦®à§à¦¡à¦¼à¦¾, à¦¬à¦¾à¦à¦•à§à¦¡à¦¼à¦¾',
      district: 'à¦¬à¦¾à¦à¦•à§à¦¡à¦¼à¦¾',
      state: 'à¦ªà¦¶à§à¦šà¦¿à¦®à¦¬à¦™à§à¦—',
      cover_image: '/assets/images/05-Wood-Pottery/Artisan_decorating_ceramic_plate.jpg',
      odop_tag: 'ODOP-WB-HORSE',
      women_friendly: true,
      elderly_friendly: true
    }
  ]
};

export interface LocalizedSlideItem {
  id: number;
  type: 'image' | 'video';
  src: string;
  craftName: string;
  tagline: string;
  location: string;
  badge: string;
}

export const LOCALIZED_HERO_SLIDES: Record<SupportedLanguage, LocalizedSlideItem[]> = {
  en: [
    {
      id: 0,
      type: 'image',
      src: '/assets/images/Home page/Kolhapuri_Chappals_in_roadside_shop_in_Kolhapur3.jpeg',
      craftName: "Ancestral Kolhapuri Leathercraft",
      tagline: "Hand-stitched vegetable-tanned Kolhapuri Chappals from 4th-generation master cobblers.",
      location: "Kolhapur, Maharashtra",
      badge: "GI Tagged â€¢ 100% Herbal Tanned"
    },
    {
      id: 1,
      type: 'video',
      src: '/assets/images/Home page/local artist.mp4',
      craftName: "Master Artisan at Work",
      tagline: "Watch hereditary artisans hand-paint intricate heritage motifs and live brushstrokes.",
      location: "Living Atelier, India",
      badge: "Master Artisan Video"
    },
    {
      id: 2,
      type: 'image',
      src: '/assets/images/Home page/Making_of_bamboo_and_palm_leaf_handicarft_products.jpg',
      craftName: "Bamboo & Palm Leaf Craft",
      tagline: "Indigenous artisans hand-weave intricate bamboo and palm-leaf handicraft products.",
      location: "Majuli Island, Assam",
      badge: "UNESCO Heritage Contender"
    },
    {
      id: 3,
      type: 'video',
      src: '/assets/images/Home page/Handmade craft stall.mp4',
      craftName: "Living Craft Ateliers",
      tagline: "Experience the vibrant energy of authentic heritage stalls and master artisans at work.",
      location: "Bhavani Mandap Guilds, Maharashtra",
      badge: "Living Heritage Video"
    },
    {
      id: 4,
      type: 'image',
      src: '/assets/images/Home page/Bharud.jpg',
      craftName: "Bharud â€” Sacred Folk Performance",
      tagline: "A vibrant traditional folk art form of Maharashtra blending music, dance and devotion.",
      location: "Rural Maharashtra",
      badge: "Living Intangible Heritage"
    }
  ],
  hi: [
    {
      id: 0,
      type: 'image',
      src: '/assets/images/Home page/Kolhapuri_Chappals_in_roadside_shop_in_Kolhapur3.jpeg',
      craftName: "à¤ªà¤¾à¤°à¤‚à¤ªà¤°à¤¿à¤• à¤•à¥‹à¤²à¥à¤¹à¤¾à¤ªà¥à¤°à¥€ à¤šà¤°à¥à¤®à¤¶à¤¿à¤²à¥à¤ª",
      tagline: "à¤šà¥Œà¤¥à¥€ à¤ªà¥€à¤¢à¤¼à¥€ à¤•à¥‡ à¤¸à¤¿à¤¦à¥à¤§ à¤¹à¤¸à¥à¤¤à¤¶à¤¿à¤²à¥à¤ªà¤¿à¤¯à¥‹à¤‚ à¤¦à¥à¤µà¤¾à¤°à¤¾ à¤¬à¤¬à¥‚à¤² à¤•à¥€ à¤›à¤¾à¤² à¤”à¤° à¤¹à¤°à¤¡à¤¼ à¤¸à¥‡ à¤¤à¥ˆà¤¯à¤¾à¤° à¤ªà¥à¤°à¤¾à¤•à¥ƒà¤¤à¤¿à¤• à¤•à¥‹à¤²à¥à¤¹à¤¾à¤ªà¥à¤°à¥€ à¤šà¤ªà¥à¤ªà¤²à¥‡à¤‚à¥¤",
      location: "à¤•à¥‹à¤²à¥à¤¹à¤¾à¤ªà¥à¤°, à¤®à¤¹à¤¾à¤°à¤¾à¤·à¥à¤Ÿà¥à¤°",
      badge: "à¤œà¥€à¤†à¤ˆ à¤Ÿà¥ˆà¤— à¤ªà¥à¤°à¤®à¤¾à¤£à¤¿à¤¤"
    },
    {
      id: 1,
      type: 'video',
      src: '/assets/images/Home page/local artist.mp4',
      craftName: "à¤¸à¤œà¥€à¤µ à¤•à¤¾à¤°à¥à¤¯à¤¶à¤¾à¤²à¤¾ à¤®à¥‡à¤‚ à¤‰à¤¸à¥à¤¤à¤¾à¤¦ à¤•à¤¾à¤°à¥€à¤—à¤°",
      tagline: "à¤ªà¤¾à¤°à¤‚à¤ªà¤°à¤¿à¤• à¤¸à¤¿à¤¦à¥à¤§à¤¹à¤¸à¥à¤¤ à¤¶à¤¿à¤²à¥à¤ªà¤•à¤¾à¤°à¥‹à¤‚ à¤•à¥‹ à¤²à¤¾à¤‡à¤µ à¤¬à¤¾à¤°à¥€à¤• à¤§à¤°à¥‹à¤¹à¤° à¤†à¤•à¥ƒà¤¤à¤¿à¤¯à¤¾à¤‚ à¤¬à¤¨à¤¾à¤¤à¥‡ à¤¦à¥‡à¤–à¥‡à¤‚à¥¤",
      location: "à¤œà¥€à¤µà¤‚à¤¤ à¤•à¤¾à¤°à¥à¤¯à¤¶à¤¾à¤²à¤¾, à¤­à¤¾à¤°à¤¤",
      badge: "à¤‰à¤¸à¥à¤¤à¤¾à¤¦ à¤•à¤¾à¤°à¥€à¤—à¤° à¤µà¥€à¤¡à¤¿à¤¯à¥‹"
    },
    {
      id: 2,
      type: 'image',
      src: '/assets/images/Home page/Making_of_bamboo_and_palm_leaf_handicarft_products.jpg',
      craftName: "à¤¬à¤¾à¤‚à¤¸ à¤µ à¤¤à¤¾à¤¡à¤¼à¤ªà¤¤à¥à¤° à¤¹à¤¸à¥à¤¤à¤¶à¤¿à¤²à¥à¤ª",
      tagline: "à¤¸à¥à¤¥à¤¾à¤¨à¥€à¤¯ à¤•à¤¾à¤°à¥€à¤—à¤° à¤¹à¤¾à¤¥ à¤¸à¥‡ à¤¬à¤¾à¤‚à¤¸ à¤”à¤° à¤¤à¤¾à¤¡à¤¼à¤ªà¤¤à¥à¤° à¤¸à¥‡ à¤¬à¥‡à¤¶à¤•à¥€à¤®à¤¤à¥€ à¤¹à¤¸à¥à¤¤à¤¶à¤¿à¤²à¥à¤ª à¤µà¤¸à¥à¤¤à¥à¤à¤‚ à¤¬à¤¨à¤¾à¤¤à¥‡ à¤¹à¥ˆà¤‚à¥¤",
      location: "à¤®à¤¾à¤œà¥à¤²à¥€ à¤¦à¥à¤µà¥€à¤ª, à¤…à¤¸à¤®",
      badge: "à¤¯à¥‚à¤¨à¥‡à¤¸à¥à¤•à¥‹ à¤§à¤°à¥‹à¤¹à¤° à¤¦à¤¾à¤µà¥‡à¤¦à¤¾à¤°"
    },
    {
      id: 3,
      type: 'video',
      src: '/assets/images/Home page/Handmade craft stall.mp4',
      craftName: "à¤œà¥€à¤µà¤‚à¤¤ à¤¶à¤¿à¤²à¥à¤ª à¤¹à¤¾à¤Ÿ à¤µ à¤•à¤¾à¤°à¥€à¤—à¤°",
      tagline: "à¤ªà¤¾à¤°à¤‚à¤ªà¤°à¤¿à¤• à¤•à¤¾à¤°à¥€à¤—à¤°à¥‹à¤‚ à¤•à¥‡ à¤ªà¥à¤°à¤¾à¤®à¤¾à¤£à¤¿à¤• à¤¶à¤¿à¤²à¥à¤ª à¤¸à¥à¤Ÿà¥‰à¤² à¤”à¤° à¤•à¤¾à¤°à¥à¤¯à¤¶à¤¾à¤²à¤¾à¤“à¤‚ à¤•à¥€ à¤œà¥€à¤µà¤‚à¤¤ à¤Šà¤°à¥à¤œà¤¾ à¤•à¤¾ à¤…à¤¨à¥à¤­à¤µ à¤•à¤°à¥‡à¤‚à¥¤",
      location: "à¤­à¤µà¤¾à¤¨à¥€ à¤®à¤‚à¤¡à¤ª, à¤®à¤¹à¤¾à¤°à¤¾à¤·à¥à¤Ÿà¥à¤°",
      badge: "à¤¸à¤œà¥€à¤µ à¤§à¤°à¥‹à¤¹à¤° à¤µà¥€à¤¡à¤¿à¤¯à¥‹"
    },
    {
      id: 4,
      type: 'image',
      src: '/assets/images/Home page/Bharud.jpg',
      craftName: "à¤­à¤¾à¤°à¥à¤¡ â€” à¤®à¤¹à¤¾à¤°à¤¾à¤·à¥à¤Ÿà¥à¤° à¤•à¤¾ à¤²à¥‹à¤• à¤¨à¤¾à¤Ÿà¥à¤¯",
      tagline: "à¤®à¤¹à¤¾à¤°à¤¾à¤·à¥à¤Ÿà¥à¤° à¤•à¥€ à¤œà¥€à¤µà¤‚à¤¤ à¤²à¥‹à¤• à¤•à¤²à¤¾ à¤œà¤¿à¤¸à¤®à¥‡à¤‚ à¤¸à¤‚à¤—à¥€à¤¤, à¤¨à¥ƒà¤¤à¥à¤¯ à¤”à¤° à¤­à¤•à¥à¤¤à¤¿ à¤•à¤¾ à¤…à¤¨à¥‹à¤–à¤¾ à¤¸à¤‚à¤—à¤® à¤¹à¥ˆà¥¤",
      location: "à¤—à¥à¤°à¤¾à¤®à¥€à¤£ à¤®à¤¹à¤¾à¤°à¤¾à¤·à¥à¤Ÿà¥à¤°",
      badge: "à¤œà¥€à¤µà¤‚à¤¤ à¤…à¤®à¥‚à¤°à¥à¤¤ à¤µà¤¿à¤°à¤¾à¤¸à¤¤"
    }
  ],
  mr: [
    {
      id: 0,
      type: 'image',
      src: '/assets/images/Home page/Kolhapuri_Chappals_in_roadside_shop_in_Kolhapur3.jpeg',
      craftName: "à¤…à¤­à¤¿à¤œà¤¾à¤¤ à¤•à¥‹à¤²à¥à¤¹à¤¾à¤ªà¥à¤°à¥€ à¤šà¤°à¥à¤®à¤•à¤²à¤¾",
      tagline: "à¤šà¥Œà¤¥à¥à¤¯à¤¾ à¤ªà¤¿à¤¢à¥€à¤¤à¥€à¤² à¤•à¤¸à¤¬à¥€ à¤•à¤¾à¤°à¤¾à¤—à¤¿à¤°à¤¾à¤‚à¤¨à¥€ à¤¬à¤¾à¤­à¤³à¥€à¤šà¥à¤¯à¤¾ à¤¸à¤¾à¤²à¥€à¤šà¥à¤¯à¤¾ à¤¨à¥ˆà¤¸à¤°à¥à¤—à¤¿à¤• à¤Ÿà¥…à¤¨à¤¿à¤‚à¤—à¤¨à¥‡ à¤¹à¤¾à¤¤à¤¾à¤¨à¥‡ à¤¶à¤¿à¤µà¤²à¥‡à¤²à¥€ à¤šà¤ªà¥à¤ªà¤².",
      location: "à¤•à¥‹à¤²à¥à¤¹à¤¾à¤ªà¥‚à¤°, à¤®à¤¹à¤¾à¤°à¤¾à¤·à¥à¤Ÿà¥à¤°",
      badge: "à¤œà¥€à¤†à¤¯ à¤®à¤¾à¤¨à¤¾à¤‚à¤•à¤¨"
    },
    {
      id: 1,
      type: 'video',
      src: '/assets/images/Home page/local artist.mp4',
      craftName: "à¤•à¤¾à¤°à¥à¤¯à¤°à¤¤ à¤œà¥à¤¯à¥‡à¤·à¥à¤  à¤¹à¤¸à¥à¤¤à¤•à¤²à¤¾à¤•à¤¾à¤°",
      tagline: "à¤ªà¤¾à¤°à¤‚à¤ªà¤°à¤¿à¤• à¤•à¤¾à¤°à¤¾à¤—à¤¿à¤°à¤¾à¤‚à¤¨à¤¾ à¤œà¤¿à¤µà¤‚à¤¤ à¤•à¤²à¥‡à¤šà¥‡ à¤¨à¤•à¥à¤·à¥€à¤•à¤¾à¤® à¤†à¤£à¤¿ à¤•à¥à¤‚à¤šà¤²à¥à¤¯à¤¾à¤šà¥‡ à¤«à¤Ÿà¤•à¤¾à¤°à¥‡ à¤®à¤¾à¤°à¤¤à¤¾à¤¨à¤¾ à¤ªà¥à¤°à¤¤à¥à¤¯à¤•à¥à¤· à¤ªà¤¹à¤¾.",
      location: "à¤ªà¥à¤°à¤¤à¥à¤¯à¤•à¥à¤· à¤•à¤¾à¤°à¥à¤¯à¤¶à¤¾à¤³à¤¾, à¤­à¤¾à¤°à¤¤",
      badge: "à¤®à¤¾à¤¸à¥à¤Ÿà¤° à¤†à¤°à¥à¤Ÿà¤¿à¤¸à¤¨ à¤µà¥à¤¹à¤¿à¤¡à¤¿à¤“"
    },
    {
      id: 2,
      type: 'image',
      src: '/assets/images/Home page/Making_of_bamboo_and_palm_leaf_handicarft_products.jpg',
      craftName: "à¤¬à¤¾à¤‚à¤¬à¥‚ à¤µ à¤¤à¤¾à¤¡à¤ªà¤¤à¥à¤° à¤¹à¤¸à¥à¤¤à¤•à¤²à¤¾",
      tagline: "à¤¸à¥à¤¥à¤¾à¤¨à¤¿à¤• à¤•à¤¾à¤°à¤¾à¤—à¥€à¤° à¤¹à¤¾à¤¤à¤¾à¤¨à¥‡ à¤¬à¤¾à¤‚à¤¬à¥‚ à¤µ à¤¤à¤¾à¤¡à¤ªà¤¤à¥à¤°à¤¾à¤šà¥à¤¯à¤¾ à¤…à¤®à¥‚à¤²à¥à¤¯ à¤¹à¤¸à¥à¤¤à¤•à¤²à¤¾à¤µà¤¸à¥à¤¤à¥‚ à¤˜à¤¡à¤µà¤¤à¤¾à¤¤.",
      location: "à¤®à¤¾à¤œà¥à¤²à¥€ à¤¬à¥‡à¤Ÿ, à¤†à¤¸à¤¾à¤®",
      badge: "à¤¯à¥à¤¨à¥‡à¤¸à¥à¤•à¥‹ à¤µà¤¾à¤°à¤¸à¤¾ à¤¦à¤¾à¤µà¥‡à¤¦à¤¾à¤°"
    },
    {
      id: 3,
      type: 'video',
      src: '/assets/images/Home page/Handmade craft stall.mp4',
      craftName: "à¤ªà¤¾à¤°à¤‚à¤ªà¤°à¤¿à¤• à¤•à¤¾à¤°à¤¾à¤—à¥€à¤° à¤¸à¥à¤Ÿà¥‰à¤²à¥à¤¸",
      tagline: "à¤­à¤µà¤¾à¤¨à¥€ à¤®à¤‚à¤¡à¤ªà¤¾à¤¤à¥€à¤² à¤•à¤¾à¤°à¤¾à¤—à¤¿à¤°à¤¾à¤‚à¤šà¤¾ à¤¥à¥‡à¤Ÿ à¤‰à¤¤à¥à¤¸à¤¾à¤¹ à¤†à¤£à¤¿ à¤…à¤¸à¥à¤¸à¤² à¤¹à¤¸à¥à¤¤à¤•à¤²à¥‡à¤šà¥€ à¤Šà¤°à¥à¤œà¤¾ à¤…à¤¨à¥à¤­à¤µà¤¾.",
      location: "à¤­à¤µà¤¾à¤¨à¥€ à¤®à¤‚à¤¡à¤ª, à¤•à¥‹à¤²à¥à¤¹à¤¾à¤ªà¥‚à¤°",
      badge: "à¤µà¤¾à¤°à¤¸à¤¾ à¤µà¥à¤¹à¤¿à¤¡à¤¿à¤“"
    },
    {
      id: 4,
      type: 'image',
      src: '/assets/images/Home page/Bharud.jpg',
      craftName: "à¤­à¤¾à¤°à¥à¤¡ â€” à¤®à¤¹à¤¾à¤°à¤¾à¤·à¥à¤Ÿà¥à¤°à¤¾à¤šà¥€ à¤²à¥‹à¤•à¤•à¤²à¤¾",
      tagline: "à¤®à¤¹à¤¾à¤°à¤¾à¤·à¥à¤Ÿà¥à¤°à¤¾à¤šà¥€ à¤¹à¥€ à¤œà¤¿à¤µà¤‚à¤¤ à¤²à¥‹à¤•à¤•à¤²à¤¾ à¤¸à¤‚à¤—à¥€à¤¤, à¤¨à¥ƒà¤¤à¥à¤¯ à¤†à¤£à¤¿ à¤­à¤•à¥à¤¤à¥€à¤šà¤¾ à¤…à¤¨à¥‹à¤–à¤¾ à¤¸à¤‚à¤—à¤® à¤†à¤¹à¥‡.",
      location: "à¤—à¥à¤°à¤¾à¤®à¥€à¤£ à¤®à¤¹à¤¾à¤°à¤¾à¤·à¥à¤Ÿà¥à¤°",
      badge: "à¤œà¤¿à¤µà¤‚à¤¤ à¤…à¤®à¥‚à¤°à¥à¤¤ à¤µà¤¾à¤°à¤¸à¤¾"
    }
  ],
  ta: [
    {
      id: 0,
      type: 'image',
      src: '/assets/images/Home page/Kolhapuri_Chappals_in_roadside_shop_in_Kolhapur3.jpeg',
      craftName: "à®•à¯‹à®²à®¾à®ªà¯à®ªà¯‚à®°à®¿ à®¤à¯‹à®²à¯ à®•à¯ˆà®µà®¿à®©à¯ˆ",
      tagline: "4à®µà®¤à¯ à®¤à®²à¯ˆà®®à¯à®±à¯ˆ à®•à¯ˆà®µà®¿à®©à¯ˆà®žà®°à¯à®•à®³à®¿à®©à¯ à®‡à®¯à®±à¯à®•à¯ˆ à®¤à¯‹à®²à¯ à®ªà®¤à®©à®¿à®Ÿà¯à®¤à®²à¯ à®®à¯à®±à¯ˆà®¯à®¿à®²à¯ à®¤à¯ˆà®•à¯à®•à®ªà¯à®ªà®Ÿà¯à®Ÿ à®šà¯†à®°à¯à®ªà¯à®ªà¯à®•à®³à¯.",
      location: "à®•à¯‹à®²à®¾à®ªà¯à®ªà¯‚à®°à¯, à®®à®•à®¾à®°à®¾à®·à¯à®Ÿà®¿à®°à®¾",
      badge: "GI à®šà®¾à®©à¯à®±à®³à®¿à®•à¯à®•à®ªà¯à®ªà®Ÿà¯à®Ÿà®¤à¯"
    },
    {
      id: 1,
      type: 'video',
      src: '/assets/images/Home page/local artist.mp4',
      craftName: "à®•à¯ˆà®µà®¿à®©à¯ˆà®žà®°à¯ à®¨à¯‡à®°à®Ÿà®¿ à®ªà®£à®¿",
      tagline: "à®ªà®¾à®°à®®à¯à®ªà®°à®¿à®¯ à®•à¯ˆà®µà®¿à®©à¯ˆà®žà®°à¯à®•à®³à¯ à®¨à¯‡à®°à®Ÿà®¿à®¯à®¾à®• à®•à®²à¯ˆ à®ªà®Ÿà¯ˆà®ªà¯à®ªà¯à®•à®³à¯ à®‰à®°à¯à®µà®¾à®•à¯à®•à¯à®µà®¤à¯ˆ à®•à®¾à®£à¯à®™à¯à®•à®³à¯.",
      location: "à®¨à¯‡à®°à®Ÿà®¿ à®ªà®£à®¿à®®à®©à¯ˆ, à®‡à®¨à¯à®¤à®¿à®¯à®¾",
      badge: "à®•à¯ˆà®µà®¿à®©à¯ˆà®žà®°à¯ à®•à®¾à®£à¯Šà®³à®¿"
    },
    {
      id: 2,
      type: 'image',
      src: '/assets/images/Home page/Making_of_bamboo_and_palm_leaf_handicarft_products.jpg',
      craftName: "à®®à¯‚à®™à¯à®•à®¿à®²à¯ & à®ªà®©à¯ˆ à®‡à®²à¯ˆ à®•à¯ˆà®µà®¿à®©à¯ˆ",
      tagline: "à®‰à®³à¯à®³à¯‚à®°à¯ à®•à¯ˆà®µà®¿à®©à¯ˆà®žà®°à¯à®•à®³à¯ à®•à¯ˆà®•à®³à®¾à®²à¯ à®®à¯‚à®™à¯à®•à®¿à®²à¯ à®®à®±à¯à®±à¯à®®à¯ à®ªà®©à¯ˆ à®‡à®²à¯ˆà®¯à®¿à®²à¯ à®•à¯ˆà®µà®¿à®©à¯ˆà®ªà¯à®ªà¯Šà®°à¯à®Ÿà¯à®•à®³à¯ à®šà¯†à®¯à¯à®•à®¿à®±à®¾à®°à¯à®•à®³à¯.",
      location: "à®®à®¾à®œà¯à®²à®¿ à®¤à¯€à®µà¯, à®…à®šà®¾à®®à¯",
      badge: "à®¯à¯à®©à¯†à®¸à¯à®•à¯‹ à®ªà®¾à®°à®®à¯à®ªà®°à®¿à®¯à®®à¯"
    },
    {
      id: 3,
      type: 'video',
      src: '/assets/images/Home page/Handmade craft stall.mp4',
      craftName: "à®ªà®¾à®°à®®à¯à®ªà®°à®¿à®¯ à®•à¯ˆà®µà®¿à®©à¯ˆ à®•à®£à¯à®•à®¾à®Ÿà¯à®šà®¿",
      tagline: "à®ªà®¾à®°à®®à¯à®ªà®°à®¿à®¯ à®•à¯ˆà®µà®¿à®©à¯ˆà®žà®°à¯à®•à®³à®¿à®©à¯ à®‰à®£à¯à®®à¯ˆà®¯à®¾à®© à®¸à¯à®Ÿà®¾à®²à¯à®•à®³à¯ à®®à®±à¯à®±à¯à®®à¯ à®ªà®£à®¿à®®à®©à¯ˆà®•à®³à¯ˆ à®…à®©à¯à®ªà®µà®¿à®¯à¯à®™à¯à®•à®³à¯.",
      location: "à®ªà®µà®¾à®©à®¿ à®®à®£à¯à®Ÿà®ªà®®à¯, à®®à®•à®¾à®°à®¾à®·à¯à®Ÿà®¿à®°à®¾",
      badge: "à®ªà®¾à®°à®®à¯à®ªà®°à®¿à®¯ à®•à¯ˆà®µà®¿à®©à¯ˆ à®•à®¾à®£à¯Šà®³à®¿"
    },
    {
      id: 4,
      type: 'image',
      src: '/assets/images/Home page/Bharud.jpg',
      craftName: "à®ªà®¾à®°à®Ÿà¯ â€” à®¨à®¾à®Ÿà¯à®Ÿà¯à®ªà¯à®ªà¯à®± à®•à®²à¯ˆ",
      tagline: "à®®à®•à®¾à®°à®¾à®·à¯à®Ÿà®¿à®°à®¾à®µà®¿à®©à¯ à®‡à®šà¯ˆ, à®¨à®Ÿà®©à®®à¯ à®®à®±à¯à®±à¯à®®à¯ à®ªà®•à¯à®¤à®¿à®¯à¯ˆ à®‡à®£à¯ˆà®•à¯à®•à¯à®®à¯ à®‰à®¯à®¿à®°à¯‹à®Ÿà¯à®Ÿà®®à®¾à®© à®¨à®¾à®Ÿà¯à®Ÿà¯à®ªà¯à®ªà¯à®± à®•à®²à¯ˆ.",
      location: "à®•à®¿à®°à®¾à®®à®ªà¯à®ªà¯à®± à®®à®•à®¾à®°à®¾à®·à¯à®Ÿà®¿à®°à®¾",
      badge: "à®‰à®¯à®¿à®°à¯‹à®Ÿà¯à®Ÿà®®à®¾à®© à®ªà®¾à®°à®®à¯à®ªà®°à®¿à®¯à®®à¯"
    }
  ],
  te: [
    {
      id: 0,
      type: 'image',
      src: '/assets/images/Home page/Kolhapuri_Chappals_in_roadside_shop_in_Kolhapur3.jpeg',
      craftName: "à°•à±‹à°²à±à°¹à°¾à°ªà±‚à°°à°¿ à°¤à±‹à°²à± à°•à°³",
      tagline: "4à°µ à°¤à°°à°‚ à°•à°³à°¾à°•à°¾à°°à±à°² à°ªà±à°°à°•à±ƒà°¤à°¿ à°¸à°¿à°¦à±à°§à°®à±ˆà°¨ à°ªà°¦à±à°§à°¤à°¿à°²à±‹ à°šà±‡à°¤à°¿à°¤à±‹ à°•à±à°Ÿà±à°Ÿà°¿à°¨ à°•à±‹à°²à±à°¹à°¾à°ªà±‚à°°à°¿ à°šà±†à°ªà±à°ªà±à°²à±.",
      location: "à°•à±‹à°²à±à°¹à°¾à°ªà±‚à°°à±, à°®à°¹à°¾à°°à°¾à°·à±à°Ÿà±à°°",
      badge: "GI à°Ÿà±à°¯à°¾à°—à± à°§à±ƒà°µà±€à°•à°°à°¿à°‚à°šà°¬à°¡à°¿à°‚à°¦à°¿"
    },
    {
      id: 1,
      type: 'video',
      src: '/assets/images/Home page/local artist.mp4',
      craftName: "à°•à°³à°¾à°•à°¾à°°à±à°¡à± à°ªà°¨à°¿à°²à±‹",
      tagline: "à°µà°‚à°¶à°ªà°¾à°°à°‚à°ªà°°à±à°¯ à°•à°³à°¾à°•à°¾à°°à±à°²à± à°¸à°¾à°‚à°ªà±à°°à°¦à°¾à°¯ à°¨à°®à±‚à°¨à°¾à°²à± à°šà±‡à°¤à°¿à°¤à±‹ à°µà±‡à°¸à±à°¤à±à°‚à°¡à°—à°¾ à°šà±‚à°¡à°‚à°¡à°¿.",
      location: "à°¨à±‡à°°à±à°—à°¾ à°•à°³à°¾ à°¶à°¾à°², à°­à°¾à°°à°¤à°¦à±‡à°¶à°‚",
      badge: "à°•à°³à°¾à°•à°¾à°°à±à°¡à± à°µà±€à°¡à°¿à°¯à±‹"
    },
    {
      id: 2,
      type: 'image',
      src: '/assets/images/Home page/Making_of_bamboo_and_palm_leaf_handicarft_products.jpg',
      craftName: "à°µà±†à°¦à±à°°à± & à°¤à°¾à°Ÿà°¾à°•à± à°¹à°¸à±à°¤à°•à°³",
      tagline: "à°¸à±à°¥à°¾à°¨à°¿à°• à°•à°³à°¾à°•à°¾à°°à±à°²à± à°šà±‡à°¤à°¿à°¤à±‹ à°µà±†à°¦à±à°°à± à°®à°°à°¿à°¯à± à°¤à°¾à°Ÿà°¾à°•à±à°¤à±‹ à°…à°®à±‚à°²à±à°¯à°®à±ˆà°¨ à°¹à°¸à±à°¤à°•à°³ à°µà°¸à±à°¤à±à°µà±à°²à± à°¤à°¯à°¾à°°à± à°šà±‡à°¸à±à°¤à°¾à°°à±.",
      location: "à°®à°œà±à°²à°¿ à°¦à±à°µà±€à°ªà°‚, à°…à°¸à±à°¸à°¾à°‚",
      badge: "à°¯à±à°¨à±†à°¸à±à°•à±‹ à°µà°¾à°°à°¸à°¤à±à°µ à°…à°­à±à°¯à°°à±à°¥à°¿"
    },
    {
      id: 3,
      type: 'video',
      src: '/assets/images/Home page/Handmade craft stall.mp4',
      craftName: "à°¸à°œà±€à°µ à°¹à°¸à±à°¤à°•à°³à°¾ à°•à±‡à°‚à°¦à±à°°à°¾à°²à±",
      tagline: "à°¸à°¾à°‚à°ªà±à°°à°¦à°¾à°¯ à°•à°³à°¾à°•à°¾à°°à±à°² à°¸à±à°Ÿà°¾à°³à±à°²à± à°®à°°à°¿à°¯à± à°ªà±à°°à°¾à°®à°¾à°£à°¿à°•à°®à±ˆà°¨ à°¹à°¸à±à°¤à°•à°³à°² à°ªà±à°°à°¤à±à°¯à°•à±à°· à°…à°¨à±à°­à±‚à°¤à°¿.",
      location: "à°­à°µà°¾à°¨à°¿ à°®à°‚à°¡à°ªà°‚, à°®à°¹à°¾à°°à°¾à°·à±à°Ÿà±à°°",
      badge: "à°¸à°œà±€à°µ à°µà°¾à°°à°¸à°¤à±à°µ à°µà±€à°¡à°¿à°¯à±‹"
    },
    {
      id: 4,
      type: 'image',
      src: '/assets/images/Home page/Bharud.jpg',
      craftName: "à°­à°¾à°°à±à°¦à± â€” à°œà°¾à°¨à°ªà°¦ à°•à°³à°¾à°°à±‚à°ªà°‚",
      tagline: "à°®à°¹à°¾à°°à°¾à°·à±à°Ÿà±à°° à°¯à±Šà°•à±à°• à°œà±€à°µà°‚à°¤à°®à±ˆà°¨ à°œà°¾à°¨à°ªà°¦ à°•à°³ à°¸à°‚à°—à±€à°¤à°‚, à°¨à±ƒà°¤à±à°¯à°‚ à°®à°°à°¿à°¯à± à°­à°•à±à°¤à°¿ à°®à±‡à°³à°µà°¿à°‚à°ªà±.",
      location: "à°—à±à°°à°¾à°®à±€à°£ à°®à°¹à°¾à°°à°¾à°·à±à°Ÿà±à°°",
      badge: "à°œà±€à°µà°‚à°¤à°®à±ˆà°¨ à°…à°®à±‚à°°à±à°¤ à°µà°¾à°°à°¸à°¤à±à°µà°‚"
    }
  ],
  bn: [
    {
      id: 0,
      type: 'image',
      src: '/assets/images/Home page/Kolhapuri_Chappals_in_roadside_shop_in_Kolhapur3.jpeg',
      craftName: "à¦•à§‹à¦²à¦¹à¦¾à¦ªà§à¦°à§€ à¦šà¦¾à¦®à¦¡à¦¼à¦¾à¦¶à¦¿à¦²à§à¦ª",
      tagline: "à¦šà¦¤à§à¦°à§à¦¥ à¦ªà§à¦°à¦œà¦¨à§à¦®à§‡à¦° à¦•à¦¾à¦°à¦¿à¦—à¦°à¦¦à§‡à¦° à¦¬à¦¾à¦¬à¦²à¦¾ à¦›à¦¾à¦² à¦¦à¦¿à¦¯à¦¼à§‡ à¦­à§‡à¦·à¦œ à¦ªà¦¦à§à¦§à¦¤à¦¿à¦¤à§‡ à¦¤à§ˆà¦°à¦¿ à¦•à§‹à¦²à¦¹à¦¾à¦ªà§à¦°à§€ à¦šà¦Ÿà¦¿à¥¤",
      location: "à¦•à§‹à¦²à¦¹à¦¾à¦ªà§à¦°, à¦®à¦¹à¦¾à¦°à¦¾à¦·à§à¦Ÿà§à¦°",
      badge: "à¦œà¦¿à¦†à¦‡ à¦Ÿà§à¦¯à¦¾à¦— à¦ªà§à¦°à¦¾à¦ªà§à¦¤"
    },
    {
      id: 1,
      type: 'video',
      src: '/assets/images/Home page/local artist.mp4',
      craftName: "à¦•à¦°à§à¦®à¦°à¦¤ à¦ªà§à¦°à¦§à¦¾à¦¨ à¦•à¦¾à¦°à¦¿à¦—à¦°",
      tagline: "à¦¬à¦‚à¦¶à¦ªà¦°à¦®à§à¦ªà¦°à¦¾ à¦•à¦¾à¦°à¦¿à¦—à¦°à¦¦à§‡à¦° à¦¸à¦°à¦¾à¦¸à¦°à¦¿ à¦à¦¤à¦¿à¦¹à§à¦¯à¦¬à¦¾à¦¹à§€ à¦¨à¦•à¦¶à¦¾ à¦“ à¦¶à¦¿à¦²à§à¦ªà¦•à¦°à§à¦® à¦¤à§ˆà¦°à¦¿ à¦¦à§‡à¦–à§à¦¨à¥¤",
      location: "à¦¸à¦°à¦¾à¦¸à¦°à¦¿ à¦•à¦°à§à¦®à¦¶à¦¾à¦²à¦¾, à¦­à¦¾à¦°à¦¤",
      badge: "à¦®à¦¾à¦¸à§à¦Ÿà¦¾à¦° à¦†à¦°à§à¦Ÿà¦¿à¦¸à¦¾à¦¨ à¦­à¦¿à¦¡à¦¿à¦“"
    },
    {
      id: 2,
      type: 'image',
      src: '/assets/images/Home page/Making_of_bamboo_and_palm_leaf_handicarft_products.jpg',
      craftName: "à¦¬à¦¾à¦à¦¶ à¦“ à¦¤à¦¾à¦²à¦ªà¦¾à¦¤à¦¾à¦° à¦¹à¦¸à§à¦¤à¦¶à¦¿à¦²à§à¦ª",
      tagline: "à¦¸à§à¦¥à¦¾à¦¨à§€à¦¯à¦¼ à¦•à¦¾à¦°à¦¿à¦—à¦°à¦°à¦¾ à¦¹à¦¾à¦¤à§‡ à¦¬à¦¾à¦à¦¶ à¦“ à¦¤à¦¾à¦²à¦ªà¦¾à¦¤à¦¾ à¦¦à¦¿à¦¯à¦¼à§‡ à¦®à§‚à¦²à§à¦¯à¦¬à¦¾à¦¨ à¦¹à¦¸à§à¦¤à¦¶à¦¿à¦²à§à¦ª à¦¤à§ˆà¦°à¦¿ à¦•à¦°à§‡à¦¨à¥¤",
      location: "à¦®à¦¾à¦œà§à¦²à§€ à¦¦à§à¦¬à§€à¦ª, à¦†à¦¸à¦¾à¦®",
      badge: "à¦‡à¦‰à¦¨à§‡à¦¸à§à¦•à§‹ à¦à¦¤à¦¿à¦¹à§à¦¯ à¦¦à¦¾à¦¬à¦¿à¦¦à¦¾à¦°"
    },
    {
      id: 3,
      type: 'video',
      src: '/assets/images/Home page/Handmade craft stall.mp4',
      craftName: "à¦¸à¦°à¦¾à¦¸à¦°à¦¿ à¦¹à¦¸à§à¦¤à¦¶à¦¿à¦²à§à¦ª à¦¹à¦¾à¦Ÿ",
      tagline: "à¦à¦¤à¦¿à¦¹à§à¦¯à¦¬à¦¾à¦¹à§€ à¦•à¦¾à¦°à¦¿à¦—à¦°à¦¦à§‡à¦° à¦–à¦¾à¦à¦Ÿà¦¿ à¦¸à§à¦Ÿà¦² à¦“ à¦•à¦¾à¦œà§‡à¦° à¦ªà§à¦°à¦¾à¦£à¦¬à¦¨à§à¦¤ à¦ªà¦°à¦¿à¦¬à§‡à¦¶ à¦‰à¦ªà¦­à§‹à¦— à¦•à¦°à§à¦¨à¥¤",
      location: "à¦­à¦¬à¦¾à¦¨à§€ à¦®à¦£à§à¦¡à¦ª, à¦®à¦¹à¦¾à¦°à¦¾à¦·à§à¦Ÿà§à¦°",
      badge: "à¦œà§€à¦¬à¦¨à§à¦¤ à¦à¦¤à¦¿à¦¹à§à¦¯ à¦­à¦¿à¦¡à¦¿à¦“"
    },
    {
      id: 4,
      type: 'image',
      src: '/assets/images/Home page/Bharud.jpg',
      craftName: "à¦­à¦¾à¦°à§à¦¡ â€” à¦²à§‹à¦• à¦¶à¦¿à¦²à§à¦ªà¦•à¦²à¦¾",
      tagline: "à¦®à¦¹à¦¾à¦°à¦¾à¦·à§à¦Ÿà§à¦°à§‡à¦° à¦à¦‡ à¦œà§€à¦¬à¦¨à§à¦¤ à¦²à§‹à¦•à¦¶à¦¿à¦²à§à¦ªà§‡ à¦¸à¦™à§à¦—à§€à¦¤, à¦¨à§ƒà¦¤à§à¦¯ à¦“ à¦­à¦•à§à¦¤à¦¿à¦° à¦…à¦ªà§‚à¦°à§à¦¬ à¦®à¦¿à¦¶à§à¦°à¦£à¥¤",
      location: "à¦—à§à¦°à¦¾à¦®à§€à¦£ à¦®à¦¹à¦¾à¦°à¦¾à¦·à§à¦Ÿà§à¦°",
      badge: "à¦œà§€à¦¬à¦¨à§à¦¤ à¦…à¦®à§‚à¦°à§à¦¤ à¦à¦¤à¦¿à¦¹à§à¦¯"
    }
  ]
};

export const LOCALIZED_HOMEPAGE_UI: Record<SupportedLanguage, {
  discoverHeading: string;
  verifiedArtisansBadge: string;
  giTagBadge: string;
  directIncomeBadge: string;
  searchPlaceholder: string;
  allCraftsCategory: string;
  workshopsHeading: string;
  workshopsSubtitle: string;
  viewAtelierBtn: string;
  bookBtn: string;
  trustScoreLabel: string;
  heritageMapHeading: string;
  heritageMapSubtitle: string;
  activeAteliersLabel: string;
}> = {
  en: {
    discoverHeading: "Discover India's",
    verifiedArtisansBadge: "100% Verified Hereditary Artisans",
    giTagBadge: "GI Tag Protected Crafts",
    directIncomeBadge: "96% Direct-to-Artisan Payouts",
    searchPlaceholder: "Search by craft, artisan name, village or district...",
    allCraftsCategory: "All Crafts",
    workshopsHeading: "Master Artisan Workshops",
    workshopsSubtitle: "Handcrafted living lineages, direct atelier sessions & GI-certified masterclasses",
    viewAtelierBtn: "View Atelier & Book â†’",
    bookBtn: "Book Workshop",
    trustScoreLabel: "Trust Score",
    heritageMapHeading: "Living Heritage Craft Map",
    heritageMapSubtitle: "Locate authentic hereditary artisan clusters across India with Survey of India administrative accuracy",
    activeAteliersLabel: "Verified Craft Ateliers Active"
  },
  hi: {
    discoverHeading: "à¤…à¤¨à¥à¤­à¤µ à¤•à¤°à¥‡à¤‚ à¤­à¤¾à¤°à¤¤ à¤•à¤¾",
    verifiedArtisansBadge: "100% à¤¸à¤¤à¥à¤¯à¤¾à¤ªà¤¿à¤¤ à¤µà¤‚à¤¶à¤¾à¤¨à¥à¤—à¤¤ à¤•à¤¾à¤°à¥€à¤—à¤°",
    giTagBadge: "à¤œà¥€à¤†à¤ˆ à¤Ÿà¥ˆà¤— à¤¸à¤‚à¤°à¤•à¥à¤·à¤¿à¤¤ à¤¹à¤¸à¥à¤¤à¤¶à¤¿à¤²à¥à¤ª",
    directIncomeBadge: "96% à¤¸à¥€à¤§à¤¾ à¤•à¤¾à¤°à¥€à¤—à¤° à¤­à¥à¤—à¤¤à¤¾à¤¨",
    searchPlaceholder: "à¤¶à¤¿à¤²à¥à¤ª, à¤•à¤¾à¤°à¥€à¤—à¤° à¤•à¤¾ à¤¨à¤¾à¤®, à¤—à¤¾à¤‚à¤µ à¤¯à¤¾ à¤œà¤¿à¤²à¤¾ à¤–à¥‹à¤œà¥‡à¤‚...",
    allCraftsCategory: "à¤¸à¤­à¥€ à¤¹à¤¸à¥à¤¤à¤¶à¤¿à¤²à¥à¤ª",
    workshopsHeading: "à¤‰à¤¸à¥à¤¤à¤¾à¤¦ à¤•à¤¾à¤°à¥€à¤—à¤° à¤•à¤¾à¤°à¥à¤¯à¤¶à¤¾à¤²à¤¾à¤à¤‚",
    workshopsSubtitle: "à¤¹à¤¸à¥à¤¤à¤¨à¤¿à¤°à¥à¤®à¤¿à¤¤ à¤œà¥€à¤µà¤‚à¤¤ à¤§à¤°à¥‹à¤¹à¤°, à¤ªà¥à¤°à¤¤à¥à¤¯à¤•à¥à¤· à¤•à¤¾à¤°à¥à¤¯à¤¶à¤¾à¤²à¤¾ à¤¸à¤¤à¥à¤° à¤”à¤° à¤œà¥€à¤†à¤ˆ à¤ªà¥à¤°à¤®à¤¾à¤£à¤¿à¤¤ à¤®à¤¾à¤¸à¥à¤Ÿà¤°à¤•à¥à¤²à¤¾à¤¸",
    viewAtelierBtn: "à¤•à¤¾à¤°à¥à¤¯à¤¶à¤¾à¤²à¤¾ à¤¦à¥‡à¤–à¥‡à¤‚ à¤µ à¤¬à¥à¤• à¤•à¤°à¥‡à¤‚ â†’",
    bookBtn: "à¤µà¤°à¥à¤•à¤¶à¥‰à¤ª à¤¬à¥à¤• à¤•à¤°à¥‡à¤‚",
    trustScoreLabel: "à¤¸à¤¤à¥à¤¯à¤¾à¤ªà¤¨ à¤¸à¥à¤•à¥‹à¤°",
    heritageMapHeading: "à¤¸à¤œà¥€à¤µ à¤§à¤°à¥‹à¤¹à¤° à¤¶à¤¿à¤²à¥à¤ª à¤®à¤¾à¤¨à¤šà¤¿à¤¤à¥à¤°",
    heritageMapSubtitle: "à¤¸à¤°à¥à¤µà¥‡ à¤‘à¤« à¤‡à¤‚à¤¡à¤¿à¤¯à¤¾ à¤ªà¥à¤°à¤¶à¤¾à¤¸à¤¨à¤¿à¤• à¤¸à¤Ÿà¥€à¤•à¤¤à¤¾ à¤•à¥‡ à¤¸à¤¾à¤¥ à¤­à¤¾à¤°à¤¤ à¤­à¤° à¤•à¥‡ à¤ªà¥à¤°à¤¾à¤®à¤¾à¤£à¤¿à¤• à¤•à¤¾à¤°à¥€à¤—à¤° à¤¸à¤®à¥‚à¤¹à¥‹à¤‚ à¤•à¥‹ à¤–à¥‹à¤œà¥‡à¤‚",
    activeAteliersLabel: "à¤¸à¤¤à¥à¤¯à¤¾à¤ªà¤¿à¤¤ à¤¶à¤¿à¤²à¥à¤ª à¤•à¤¾à¤°à¥à¤¯à¤¶à¤¾à¤²à¤¾à¤à¤‚ à¤¸à¤•à¥à¤°à¤¿à¤¯"
  },
  mr: {
    discoverHeading: "à¤…à¤¨à¥à¤­à¤µà¤¾ à¤­à¤¾à¤°à¤¤à¤¾à¤šà¥€",
    verifiedArtisansBadge: "à¥§à¥¦à¥¦% à¤¸à¤¤à¥à¤¯à¤¾à¤ªà¤¿à¤¤ à¤ªà¤¿à¤¢à¥€à¤œà¤¾à¤¤ à¤•à¤¾à¤°à¤¾à¤—à¥€à¤°",
    giTagBadge: "à¤œà¥€à¤†à¤¯ à¤®à¤¾à¤¨à¤¾à¤‚à¤•à¤¨ à¤¸à¤‚à¤°à¤•à¥à¤·à¤¿à¤¤ à¤•à¤²à¤¾",
    directIncomeBadge: "à¥¯à¥¬% à¤¥à¥‡à¤Ÿ à¤•à¤¾à¤°à¤¾à¤—à¤¿à¤°à¤¾à¤‚à¤¨à¤¾ à¤‰à¤¤à¥à¤ªà¤¨à¥à¤¨",
    searchPlaceholder: "à¤¹à¤¸à¥à¤¤à¤•à¤²à¤¾, à¤•à¤¾à¤°à¤¾à¤—à¤¿à¤°à¤¾à¤šà¥‡ à¤¨à¤¾à¤µ, à¤—à¤¾à¤µ à¤•à¤¿à¤‚à¤µà¤¾ à¤œà¤¿à¤²à¥à¤¹à¤¾ à¤¶à¥‹à¤§à¤¾...",
    allCraftsCategory: "à¤¸à¤°à¥à¤µ à¤¹à¤¸à¥à¤¤à¤•à¤²à¤¾",
    workshopsHeading: "à¤®à¤¾à¤¸à¥à¤Ÿà¤° à¤•à¤¾à¤°à¤¾à¤—à¥€à¤° à¤•à¤¾à¤°à¥à¤¯à¤¶à¤¾à¤³à¤¾",
    workshopsSubtitle: "à¤¹à¤¸à¥à¤¤à¤¨à¤¿à¤°à¥à¤®à¤¿à¤¤ à¤œà¤¿à¤µà¤‚à¤¤ à¤ªà¤°à¤‚à¤ªà¤°à¤¾, à¤ªà¥à¤°à¤¤à¥à¤¯à¤•à¥à¤· à¤•à¤¾à¤°à¥à¤¯à¤¶à¤¾à¤³à¤¾ à¤†à¤£à¤¿ à¤œà¥€à¤†à¤¯ à¤ªà¥à¤°à¤®à¤¾à¤£à¤¿à¤¤ à¤®à¤¾à¤¸à¥à¤Ÿà¤°à¤•à¥à¤²à¤¾à¤¸",
    viewAtelierBtn: "à¤•à¤¾à¤°à¥à¤¯à¤¶à¤¾à¤³à¤¾ à¤ªà¤¹à¤¾ à¤µ à¤¨à¥‹à¤‚à¤¦à¤£à¥€ à¤•à¤°à¤¾ â†’",
    bookBtn: "à¤•à¤¾à¤°à¥à¤¯à¤¶à¤¾à¤³à¤¾ à¤¬à¥à¤• à¤•à¤°à¤¾",
    trustScoreLabel: "à¤¸à¤¤à¥à¤¯à¤¾à¤ªà¤¨ à¤¸à¥à¤•à¥‹à¤…à¤°",
    heritageMapHeading: "à¤µà¤¾à¤°à¤¸à¤¾ à¤¹à¤¸à¥à¤¤à¤•à¤²à¤¾ à¤¨à¤•à¤¾à¤¶à¤¾",
    heritageMapSubtitle: "à¤¸à¤°à¥à¤µà¥à¤¹à¥‡ à¤‘à¤« à¤‡à¤‚à¤¡à¤¿à¤¯à¤¾à¤šà¥à¤¯à¤¾ à¤ªà¥à¤°à¤¶à¤¾à¤¸à¤•à¥€à¤¯ à¤…à¤šà¥‚à¤•à¤¤à¥‡à¤¸à¤¹ à¤­à¤¾à¤°à¤¤à¤¾à¤¤à¥€à¤² à¤…à¤¸à¥à¤¸à¤² à¤•à¤¾à¤°à¤¾à¤—à¥€à¤° à¤•à¥à¤²à¤¸à¥à¤Ÿà¤°à¥à¤¸ à¤¶à¥‹à¤§à¤¾",
    activeAteliersLabel: "à¤¸à¤¤à¥à¤¯à¤¾à¤ªà¤¿à¤¤ à¤•à¤¾à¤°à¥à¤¯à¤¶à¤¾à¤³à¤¾ à¤¸à¤•à¥à¤°à¤¿à¤¯"
  },
  ta: {
    discoverHeading: "à®‡à®¨à¯à®¤à®¿à®¯à®¾à®µà®¿à®©à¯ à®…à®©à¯à®ªà®µà®®à¯",
    verifiedArtisansBadge: "100% à®šà®°à®¿à®ªà®¾à®°à¯à®•à¯à®•à®ªà¯à®ªà®Ÿà¯à®Ÿ à®•à¯ˆà®µà®¿à®©à¯ˆà®žà®°à¯à®•à®³à¯",
    giTagBadge: "à®ªà¯à®µà®¿à®šà®¾à®°à¯ à®•à¯à®±à®¿à®¯à¯€à®Ÿà¯ à®ªà®¾à®¤à¯à®•à®¾à®•à¯à®•à®ªà¯à®ªà®Ÿà¯à®Ÿ à®•à®²à¯ˆ",
    directIncomeBadge: "96% à®¨à¯‡à®°à®Ÿà®¿ à®•à®²à¯ˆà®žà®°à¯ à®µà®°à¯à®µà®¾à®¯à¯",
    searchPlaceholder: "à®•à¯ˆà®µà®¿à®©à¯ˆ, à®•à®²à¯ˆà®žà®°à¯ à®ªà¯†à®¯à®°à¯, à®•à®¿à®°à®¾à®®à®®à¯ à®…à®²à¯à®²à®¤à¯ à®®à®¾à®µà®Ÿà¯à®Ÿà®¤à¯à®¤à¯ˆ à®¤à¯‡à®Ÿà¯à®™à¯à®•à®³à¯...",
    allCraftsCategory: "à®…à®©à¯ˆà®¤à¯à®¤à¯ à®•à¯ˆà®µà®¿à®©à¯ˆà®•à®³à¯à®®à¯",
    workshopsHeading: "à®®à¯à®¤à®©à¯à®®à¯ˆ à®•à®²à¯ˆà®žà®°à¯ à®ªà®Ÿà¯à®Ÿà®±à¯ˆà®•à®³à¯",
    workshopsSubtitle: "à®ªà®¾à®°à®®à¯à®ªà®°à®¿à®¯ à®¨à¯‡à®°à®Ÿà®¿ à®ªà®Ÿà¯à®Ÿà®±à¯ˆ à®…à®®à®°à¯à®µà¯à®•à®³à¯ à®®à®±à¯à®±à¯à®®à¯ à®šà®¾à®©à¯à®±à®³à®¿à®•à¯à®•à®ªà¯à®ªà®Ÿà¯à®Ÿ à®µà®•à¯à®ªà¯à®ªà¯à®•à®³à¯",
    viewAtelierBtn: "à®ªà®Ÿà¯à®Ÿà®±à¯ˆà®¯à¯ˆ à®•à®¾à®£à¯à®• & à®®à¯à®©à¯à®ªà®¤à®¿à®µà¯ à®šà¯†à®¯à¯à®• â†’",
    bookBtn: "à®®à¯à®©à¯à®ªà®¤à®¿à®µà¯ à®šà¯†à®¯à¯à®•",
    trustScoreLabel: "à®¨à®®à¯à®ªà®•à®¤à¯à®¤à®©à¯à®®à¯ˆ à®®à®¤à®¿à®ªà¯à®ªà¯€à®Ÿà¯",
    heritageMapHeading: "à®ªà®¾à®°à®®à¯à®ªà®°à®¿à®¯ à®•à¯ˆà®µà®¿à®©à¯ˆ à®µà®°à¯ˆà®ªà®Ÿà®®à¯",
    heritageMapSubtitle: "à®‡à®¨à¯à®¤à®¿à®¯ à®…à®³à®µà®¿à®²à®¾à®© à®…à®¤à®¿à®•à®¾à®°à®ªà¯à®ªà¯‚à®°à¯à®µ à®¨à®¿à®°à¯à®µà®¾à®• à®¤à¯à®²à¯à®²à®¿à®¯à®¤à¯à®¤à¯à®Ÿà®©à¯ à®•à®²à¯ˆà®žà®°à¯ à®®à¯ˆà®¯à®™à¯à®•à®³à¯ˆ à®•à®£à¯à®Ÿà®±à®¿à®¯à®µà¯à®®à¯",
    activeAteliersLabel: "à®šà®°à®¿à®ªà®¾à®°à¯à®•à¯à®•à®ªà¯à®ªà®Ÿà¯à®Ÿ à®ªà®Ÿà¯à®Ÿà®±à¯ˆà®•à®³à¯ à®‡à®¯à®™à¯à®•à¯à®•à®¿à®©à¯à®±à®©"
  },
  te: {
    discoverHeading: "à°­à°¾à°°à°¤à°¦à±‡à°¶ à°…à°¦à±à°­à±à°¤à°®à±ˆà°¨",
    verifiedArtisansBadge: "100% à°§à±ƒà°µà±€à°•à°°à°¿à°‚à°šà°¬à°¡à°¿à°¨ à°µà°‚à°¶à°ªà°¾à°°à°‚à°ªà°°à±à°¯ à°•à°³à°¾à°•à°¾à°°à±à°²à±",
    giTagBadge: "à°œà°¿à° à°Ÿà±à°¯à°¾à°—à± à°°à°•à±à°·à°¿à°¤ à°¹à°¸à±à°¤à°•à°³à°²à±",
    directIncomeBadge: "96% à°•à°³à°¾à°•à°¾à°°à±à°²à°•à± à°¨à±‡à°°à±à°—à°¾ à°šà±†à°²à±à°²à°¿à°‚à°ªà±",
    searchPlaceholder: "à°•à°³, à°•à°³à°¾à°•à°¾à°°à±à°¡à°¿ à°ªà±‡à°°à±, à°—à±à°°à°¾à°®à°‚ à°²à±‡à°¦à°¾ à°œà°¿à°²à±à°²à°¾à°¨à± à°¶à±‹à°§à°¿à°‚à°šà°‚à°¡à°¿...",
    allCraftsCategory: "à°…à°¨à±à°¨à°¿ à°¹à°¸à±à°¤à°•à°³à°²à±",
    workshopsHeading: "à°®à°¾à°¸à±à°Ÿà°°à± à°†à°°à±à°Ÿà°¿à°¸à°¨à± à°µà°°à±à°•à±â€Œà°·à°¾à°ªà±â€Œà°²à±",
    workshopsSubtitle: "à°¹à°¸à±à°¤à°•à°³à°² à°ªà±à°°à°¤à±à°¯à°•à±à°· à°µà°°à±à°•à±â€Œà°·à°¾à°ªà± à°¸à±†à°·à°¨à±â€Œà°²à± à°®à°°à°¿à°¯à± à°œà°¿à° à°¸à°°à±à°Ÿà°¿à°«à±ˆà°¡à± à°®à°¾à°¸à±à°Ÿà°°à±â€Œà°•à±à°²à°¾à°¸à±â€Œà°²à±",
    viewAtelierBtn: "à°µà°°à±à°•à±â€Œà°·à°¾à°ªà±â€Œà°¨à± à°µà±€à°•à±à°·à°¿à°‚à°šà°¿ à°¬à±à°•à± à°šà±‡à°¯à°‚à°¡à°¿ â†’",
    bookBtn: "à°¬à±à°•à± à°šà±‡à°¯à°‚à°¡à°¿",
    trustScoreLabel: "à°¨à°®à±à°®à°• à°¸à±à°•à±‹à°°à±",
    heritageMapHeading: "à°¸à°œà±€à°µ à°µà°¾à°°à°¸à°¤à±à°µ à°¹à°¸à±à°¤à°•à°³à°¾ à°ªà°Ÿà°‚",
    heritageMapSubtitle: "à°¸à°°à±à°µà±‡ à°†à°«à± à°‡à°‚à°¡à°¿à°¯à°¾ à°–à°šà±à°šà°¿à°¤à°¤à±à°µà°‚à°¤à±‹ à°­à°¾à°°à°¤à°¦à±‡à°¶à°‚ à°…à°‚à°¤à°Ÿà°¾ à°ªà±à°°à°¾à°®à°¾à°£à°¿à°•à°®à±ˆà°¨ à°•à°³à°¾à°•à°¾à°°à±à°² à°•à±à°²à°¸à±à°Ÿà°°à±â€Œà°²à°¨à± à°—à±à°°à±à°¤à°¿à°‚à°šà°‚à°¡à°¿",
    activeAteliersLabel: "à°§à±ƒà°µà±€à°•à°°à°¿à°‚à°šà°¬à°¡à°¿à°¨ à°µà°°à±à°•à±â€Œà°·à°¾à°ªà±â€Œà°²à± à°¯à°¾à°•à±à°Ÿà°¿à°µà±â€Œà°—à°¾ à°‰à°¨à±à°¨à°¾à°¯à°¿"
  },
  bn: {
    discoverHeading: "à¦†à¦¬à¦¿à¦·à§à¦•à¦¾à¦° à¦•à¦°à§à¦¨ à¦­à¦¾à¦°à¦¤à§‡à¦°",
    verifiedArtisansBadge: "à§§à§¦à§¦% à¦¯à¦¾à¦šà¦¾à¦‡à¦•à§ƒà¦¤ à¦¬à¦‚à¦¶à¦ªà¦°à¦®à§à¦ªà¦°à¦¾ à¦•à¦¾à¦°à¦¿à¦—à¦°",
    giTagBadge: "à¦œà¦¿à¦†à¦‡ à¦Ÿà§à¦¯à¦¾à¦— à¦¸à§à¦°à¦•à§à¦·à¦¿à¦¤ à¦¹à¦¸à§à¦¤à¦¶à¦¿à¦²à§à¦ª",
    directIncomeBadge: "à§¯à§¬% à¦¸à¦°à¦¾à¦¸à¦°à¦¿ à¦•à¦¾à¦°à¦¿à¦—à¦°à§‡à¦° à¦†à¦¯à¦¼",
    searchPlaceholder: "à¦¶à¦¿à¦²à§à¦ª, à¦•à¦¾à¦°à¦¿à¦—à¦°à§‡à¦° à¦¨à¦¾à¦®, à¦—à§à¦°à¦¾à¦® à¦¬à¦¾ à¦œà§‡à¦²à¦¾ à¦–à§à¦à¦œà§à¦¨...",
    allCraftsCategory: "à¦¸à¦•à¦² à¦¶à¦¿à¦²à§à¦ªà¦•à¦²à¦¾",
    workshopsHeading: "à¦‰à¦¸à§à¦¤à¦¾à¦¦ à¦•à¦¾à¦°à¦¿à¦—à¦° à¦•à¦°à§à¦®à¦¶à¦¾à¦²à¦¾",
    workshopsSubtitle: "à¦¹à¦¸à§à¦¤à¦¨à¦¿à¦°à§à¦®à¦¿à¦¤ à¦œà§€à¦¬à¦¨à§à¦¤ à¦à¦¤à¦¿à¦¹à§à¦¯, à¦¸à¦°à¦¾à¦¸à¦°à¦¿ à¦•à¦°à§à¦®à¦¶à¦¾à¦²à¦¾ à¦“ à¦œà¦¿à¦†à¦‡ à¦ªà§à¦°à¦¤à§à¦¯à¦¯à¦¼à¦¿à¦¤ à¦®à¦¾à¦¸à§à¦Ÿà¦¾à¦°à¦•à§à¦²à¦¾à¦¸",
    viewAtelierBtn: "à¦•à¦°à§à¦®à¦¶à¦¾à¦²à¦¾ à¦¦à§‡à¦–à§à¦¨ à¦“ à¦¬à§à¦• à¦•à¦°à§à¦¨ â†’",
    bookBtn: "à¦¬à§à¦• à¦•à¦°à§à¦¨",
    trustScoreLabel: "à¦¯à¦¾à¦šà¦¾à¦‡à¦•à¦°à¦£ à¦¸à§à¦•à§‹à¦°",
    heritageMapHeading: "à¦à¦¤à¦¿à¦¹à§à¦¯à¦¬à¦¾à¦¹à§€ à¦¹à¦¸à§à¦¤à¦¶à¦¿à¦²à§à¦ª à¦®à¦¾à¦¨à¦šà¦¿à¦¤à§à¦°",
    heritageMapSubtitle: "à¦¸à¦¾à¦°à§à¦­à§‡ à¦…à¦« à¦‡à¦¨à§à¦¡à¦¿à¦¯à¦¼à¦¾à¦° à¦ªà§à¦°à¦¶à¦¾à¦¸à¦¨à¦¿à¦• à¦¨à¦¿à¦°à§à¦­à§à¦²à¦¤à¦¾à¦° à¦¸à¦¾à¦¥à§‡ à¦¸à¦®à¦—à§à¦° à¦­à¦¾à¦°à¦¤à§‡à¦° à¦–à¦¾à¦à¦Ÿà¦¿ à¦•à¦¾à¦°à¦¿à¦—à¦° à¦¦à¦² à¦–à§à¦à¦œà§à¦¨",
    activeAteliersLabel: "à¦¸à¦•à§à¦°à¦¿à¦¯à¦¼ à¦¯à¦¾à¦šà¦¾à¦‡à¦•à§ƒà¦¤ à¦•à¦°à§à¦®à¦¶à¦¾à¦²à¦¾"
  }
};



export const CULTURAL_EXPERIENCES: CulturalExperience[] = [
  {
    id: 'cult_01',
    title: 'Traditional Marma & Indigenous Bone-Setting Lineage',
    tradition_name: 'Marma Chikitsa & Herbal Poultices',
    description: 'Centuries-old hereditary orthopedic healing and joint alignment practiced through botanical oils, bamboo splints, and generational touch techniques.',
    category: 'Community Medicine',
    location_name: 'Puttur & Malabar Belt',
    district: 'Chittoor',
    state: 'Andhra Pradesh',
    lat: 13.4418,
    lng: 79.5539,
    cover_image: '/assets/images/Culture/Traditional_Bone_Setting.jpg',
    season: 'Year-round traditional consultations',
    community_custodians: 'Vaidya Kshatriya & Marma Guilds',
    trust_score: 99,
    significance: 'Recognized under Ministry of AYUSH traditional indigenous medicine repositories.'
  },
  {
    id: 'cult_02',
    title: 'Bodo-Kachari Indigenous Loom Songs & Spring Customs',
    tradition_name: 'Bagurumba Dance & Dokhona Silk Rites',
    description: 'Ancestral butterfly-movement spring rituals accompanied by Kham drums, Sifung flutes, and hand-spun floral Dokhona ceremonial weaving.',
    category: 'Tribal Customs',
    location_name: 'Kokrajhar Bodoland',
    district: 'Kokrajhar',
    state: 'Assam',
    lat: 26.4014,
    lng: 90.2716,
    cover_image: '/assets/images/Culture/Bodo-Kachari_2.jpg',
    season: 'Bwisagu Spring Festival (April)',
    community_custodians: 'Bodo Women Weaving & Cultural Guild',
    trust_score: 97,
    significance: 'UNESCO Intangible Folk Heritage Documentation.'
  },
  {
    id: 'cult_03',
    title: 'Dhunuchi Naach & Kumartuli Clay Deity Invocation',
    tradition_name: 'Sacred Dhunuchi Aarti with Dhak Rhythm',
    description: 'Ecstatic clay-censer devotional dance with burning coconut husk and camphor, celebrating the living artisan deity sculpted from holy Ganges clay.',
    category: 'Sacred Rituals',
    location_name: 'Kumartuli Ghats, Kolkata',
    district: 'Kolkata',
    state: 'West Bengal',
    lat: 22.5986,
    lng: 88.3639,
    cover_image: '/assets/images/Culture/Dancing_mood_of_Durga_Puja.jpg',
    season: 'Sharadotsav (September â€“ October)',
    community_custodians: 'Kumartuli Sculptors Guild & Dhakis',
    trust_score: 98,
    significance: 'UNESCO Representative List of the Intangible Cultural Heritage of Humanity.'
  },
  {
    id: 'cult_04',
    title: 'Kokan Shimga Palakhi Nrutya (Village Deities Palanquin Dance)',
    tradition_name: 'Shimagotsav Ancestral Palanquin Swaying',
    description: 'Spectacular village gathering where hereditary bearers dance through narrow betel-nut groves carrying sacred wooden palanquins of gram-daivatas.',
    category: 'Seasonal Festival',
    location_name: 'Konkan Coastal Villages',
    district: 'Ratnagiri',
    state: 'Maharashtra',
    lat: 16.9902,
    lng: 73.3120,
    cover_image: '/assets/images/Culture/Palakhinrutya_-_Dance_of_Palanquin_of_Village_Dities_-_Shimagotsav_in_Kokan_-_Maharashtra.jpg',
    season: 'Holi / Shimga (March)',
    community_custodians: 'Kokan Gramstha & Tarang Custodians',
    trust_score: 96,
    significance: '400-year-old coastal Konkan agrarian community cohesion ritual.'
  },
  {
    id: 'cult_05',
    title: 'Bhil & Bhilala Bhagoria Haat Festival of Colors',
    tradition_name: 'Tribal Harvest Courtship & Dhol Assemblies',
    description: 'Vibrant tribal carnival of giant dhol drums, brass ornaments, gulal celebrations, and community bonding across the Vindhyan hills.',
    category: 'Seasonal Festival',
    location_name: 'Jhabua Tribal Belt',
    district: 'Jhabua',
    state: 'Madhya Pradesh',
    lat: 22.7699,
    lng: 74.5936,
    cover_image: '/assets/images/Culture/The_Bhagoria_festival.jpg',
    season: 'Week preceding Holi (March)',
    community_custodians: 'Bhil & Bhilala Tribal Elders',
    trust_score: 97,
    significance: 'Ancient indigenous harvest Thanksgiving and agrarian matchmaking fair.'
  },
  {
    id: 'cult_06',
    title: 'Chhath Mahaparv â€” Vedic Riverbank Solar Worship',
    tradition_name: 'Riverbed Arghya with Handmade Bamboo Soop',
    description: 'Austerity festival honoring Surya and Chhathi Maiya on the banks of holy rivers, using 100% organic offerings and bamboo woven winnowing baskets.',
    category: 'Sacred Rituals',
    location_name: 'Ganga Ghats, Patna',
    district: 'Patna',
    state: 'Bihar',
    lat: 25.6120,
    lng: 85.1440,
    cover_image: '/assets/images/Culture/Devotees_offer_prayers_on_the_occasion_of_the_Chhath_Puja_festival.jpg',
    season: 'Kartik Shukla Shashthi (November)',
    community_custodians: 'Ganga Ghat Parvatis & Bamboo Guilds',
    trust_score: 99,
    significance: 'Vedic solar science and ecological reverence unchanged for over 3,000 years.'
  },
  {
    id: 'cult_07',
    title: 'Gond & Baiga Forest Storytelling with Bana Strings',
    tradition_name: 'Pardhan Bardic Oral Epics of Mahua Groves',
    description: 'Mystical musical epics played on the two-stringed Bana instrument, recounting creation myths and sacred relationships with the Narmada valley flora.',
    category: 'Folk Heritage',
    location_name: 'Maikal Hills, Dindori',
    district: 'Dindori',
    state: 'Madhya Pradesh',
    lat: 22.9520,
    lng: 81.0820,
    cover_image: '/assets/images/Culture/Folk_Artist.jpg',
    season: 'Autumn Forest Gatherings',
    community_custodians: 'Pardhan Gond Bards & Elders',
    trust_score: 98,
    significance: 'National Oral Heritage preservation and indigenous tribal mythology.'
  },
  {
    id: 'cult_08',
    title: 'Theyyam Sacred Grove Invocation & Poliyanthram',
    tradition_name: 'Living Deity Embodiment & Fire Walking',
    description: 'Ancestral temple ritual where hereditary performers don massive headdresses and red turmeric body paint to channel protective ancestral spirits.',
    category: 'Sacred Rituals',
    location_name: 'North Malabar Sacred Groves',
    district: 'Kannur',
    state: 'Kerala',
    lat: 11.8745,
    lng: 75.3704,
    cover_image: '/assets/images/Culture/Poliyanthram_podavadukkam.jpg',
    season: 'November to May (Kavu Rituals)',
    community_custodians: 'Vannar & Malayan Hereditary Custodians',
    trust_score: 99,
    significance: 'Over 1,500 years of unbroken sacred grove conservation and spiritual dance.'
  }
];
